-- HOW MANY ON-TIME OPPORTUNITIES ACTUALLY EXISTED?
--
-- Owner 2026-09-20: "30/72 is a phase-based approximation, not a proven
-- maximum. Initial observations and follow-up ticks may have correlated
-- timing. Use recorded observation and tick timestamps to calculate how
-- many on-time opportunities actually existed."
--
-- Correct, and the correlation is not incidental: THE SAME TICK LOOP
-- that writes an observation also runs the follow-up pass. So T0 values
-- are not uniformly distributed relative to tick boundaries -- they are
-- generated by them. A phase argument that assumes independence is
-- therefore the wrong model, and 30/72 cannot be quoted as a ceiling.
--
-- THIS COUNTS THE REAL THING. For every W1 cohort observation and every
-- horizon, did a tick actually occur inside [T0+h, T0+h+30]? That is
-- the window in which an on-time read was POSSIBLE, given that
-- eligibility opens at T0+h and ON_TIME closes at T0+h+30.
--
-- An opportunity here is necessary, not sufficient: the tick also needed
-- follow-up budget, and the horizon needed to be reached before the
-- budget ran out. Those are separate losses, counted separately.
--
-- Read only. No settlement term.

SELECT 'A_OPPORTUNITY_' || lpad(h.horizon::text, 4, '0') AS section,
       k, v
  FROM (VALUES (60), (300), (900), (3600)) AS h(horizon)
 CROSS JOIN LATERAL (
    -- Cohort observations whose on-time band has fully elapsed, so the
    -- question "was there a tick in it" is answerable.
    SELECT 'BAND_ELAPSED' AS k, count(*)::text AS v
      FROM bettor_state_observations o
     WHERE o.observed_at >= '2026-09-20T21:28:19Z'::timestamptz
       AND o.observed_at <  '2026-09-20T21:58:19Z'::timestamptz
       AND o.observed_at < now() - ((h.horizon + 30) || ' seconds')::interval
    UNION ALL
    -- THE MEASURED QUANTITY: a tick actually fell inside the band.
    SELECT 'HAD_A_TICK_IN_BAND', count(*)::text
      FROM bettor_state_observations o
     WHERE o.observed_at >= '2026-09-20T21:28:19Z'::timestamptz
       AND o.observed_at <  '2026-09-20T21:58:19Z'::timestamptz
       AND o.observed_at < now() - ((h.horizon + 30) || ' seconds')::interval
       AND EXISTS (
            SELECT 1 FROM bettor_capture_ticks t
             WHERE t.tick_at >= o.observed_at
                   + (h.horizon || ' seconds')::interval
               AND t.tick_at <= o.observed_at
                   + ((h.horizon + 30) || ' seconds')::interval)
    UNION ALL
    -- Of those, how many ALSO had follow-up budget on that tick. The
    -- difference between this and the row above is the budget loss,
    -- separated from the timing loss.
    SELECT 'TICK_IN_BAND_WITH_FU_BUDGET', count(*)::text
      FROM bettor_state_observations o
     WHERE o.observed_at >= '2026-09-20T21:28:19Z'::timestamptz
       AND o.observed_at <  '2026-09-20T21:58:19Z'::timestamptz
       AND o.observed_at < now() - ((h.horizon + 30) || ' seconds')::interval
       AND EXISTS (
            SELECT 1 FROM bettor_capture_ticks t
             WHERE t.tick_at >= o.observed_at
                   + (h.horizon || ' seconds')::interval
               AND t.tick_at <= o.observed_at
                   + ((h.horizon + 30) || ' seconds')::interval
               AND t.fu_attempted > 0)
 ) x

UNION ALL

-- ── tick spacing, measured rather than assumed ──────────────────────
SELECT 'B_TICK_SPACING', k, v FROM (
    SELECT 'N_INTERVALS' AS k, (count(*) - 1)::text AS v
      FROM bettor_capture_ticks
    UNION ALL
    SELECT 'SPACING_P50_S',
           coalesce(round((percentile_cont(0.5) WITHIN GROUP (
               ORDER BY gap))::numeric, 1)::text, '-')
      FROM (SELECT extract(epoch FROM (tick_at - lag(tick_at)
                   OVER (ORDER BY tick_at))) AS gap
              FROM bettor_capture_ticks) s
     WHERE gap IS NOT NULL
    UNION ALL
    SELECT 'SPACING_MIN_S',
           coalesce(round(min(gap)::numeric, 1)::text, '-')
      FROM (SELECT extract(epoch FROM (tick_at - lag(tick_at)
                   OVER (ORDER BY tick_at))) AS gap
              FROM bettor_capture_ticks) s
     WHERE gap IS NOT NULL
    UNION ALL
    SELECT 'SPACING_MAX_S',
           coalesce(round(max(gap)::numeric, 1)::text, '-')
      FROM (SELECT extract(epoch FROM (tick_at - lag(tick_at)
                   OVER (ORDER BY tick_at))) AS gap
              FROM bettor_capture_ticks) s
     WHERE gap IS NOT NULL
    UNION ALL
    -- Are T0s correlated with tick boundaries? If observations are
    -- written BY ticks, the offset from the nearest preceding tick
    -- should be small and tightly clustered, not uniform over the gap.
    SELECT 'OBS_OFFSET_FROM_ITS_TICK_P50_S',
           coalesce(round((percentile_cont(0.5) WITHIN GROUP (
               ORDER BY off))::numeric, 1)::text, '-')
      FROM (SELECT extract(epoch FROM (o.observed_at - (
                     SELECT max(t.tick_at) FROM bettor_capture_ticks t
                      WHERE t.tick_at <= o.observed_at))) AS off
              FROM bettor_state_observations o
             WHERE o.observed_at >= '2026-09-20T21:28:19Z'::timestamptz) q
     WHERE off IS NOT NULL
) b

ORDER BY 1, 2
