-- ECONOMIC FUNNEL (owner directive section 6), STEP 2b: THE FUNNEL OVER
-- EVERY PAPER DECISION EVER WRITTEN, PER STRATEGY, FROZEN POLICY VERSION AND
-- COHORT -- HISTORICAL (before migration 309 applied_at, the policies that
-- actually traded) and FORWARD_BIND (at or after it).
--
-- READ-ONLY. Every statement is a SELECT. Run through research-sql.yml.
--
-- Same stages and rules as ef_forward_funnel.sql (S1 eligible, S2 exact
-- mapping, S3 fresh inputs, S4 fully priced, S5a policy EV > 0, S5b
-- executable EV > 0, S5c bind all-in EV > 0, S6 qualified = a paper ENTRY
-- order placed, S7 filled, S8 closed = the position holds nothing open, by
-- settlement or by sale, S8s = closed by a settlement). S5b and S5c did not
-- exist before migrations 305 (2026-10-06 05:53Z) and 309 (17:38Z): in the
-- HISTORICAL cohort they are reported for reference only, and S6 there is
-- reached from S5a directly. The code table below was generated by the RC4
-- production code (9b94ef5c) over every code ef_codes_all.sql run
-- 37790226864 returned; a missing code is UNCLASSIFIED at ENTER_PASS.

\echo '== 2b.1 FIXTURE funnel per cohort x strategy x frozen policy'
WITH c AS (SELECT applied_at AS t FROM schema_migrations
            WHERE version = '309_paper_profitability_bind.sql'),
m(code, rnk, stage, cls) AS (VALUES
        ('ANOTHER_STRATEGY_HOLDS_EXPOSURE_TO_THIS_FIXTURE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('BELOW_MIN_GROSS_EDGE', 8, 'EV', 'ECONOMIC'),
        ('BELOW_MIN_NET_EV', 8, 'EV', 'ECONOMIC'),
        ('BOOK_READ_DID_NOT_FINISH_INSIDE_THE_DECISION_DEADLINE', 7, 'BOOK', 'SOFTWARE'),
        ('CALIBRATION_ONLY_RECORD_IS_NOT_AN_ENTRY_CANDIDATE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('CASH_WAIT_ALL_IN_EXECUTABLE_EV_NOT_POSITIVE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('CASH_WAIT_CALIBRATED_ALL_IN_EV_NOT_POSITIVE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('CASH_WAIT_FORWARD_ECONOMICS_NEGATIVE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('CASH_WAIT_TOTAL_EXECUTABLE_EV_NOT_POSITIVE', 8, 'EV', 'ECONOMIC'),
        ('DEPTH_NOT_ESTABLISHED', 7, 'BOOK', 'SOFTWARE'),
        ('DRAW_HANDLING_NOT_RECONCILED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('EXECUTION_ESTIMATE_NOT_IDENTIFIED', 7, 'BOOK', 'SOFTWARE'),
        ('EXPLORATION_ALREADY_HOLDS_THIS_FIXTURE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('FEED_MARKET_NOT_IN_CURRENT_STATE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_OWNERSHIP_NOT_HELD', 5, 'MODEL', 'SOFTWARE'),
        ('FEED_QUOTE_AGE_UNKNOWN_NO_OBSERVED_CHANGE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_QUOTE_CHANGE_TIME_IN_THE_FUTURE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_QUOTE_OLDER_THAN_LIMIT', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_SOCKET_CLOSED', 1, 'PROVIDER', 'SOFTWARE'),
        ('FIXTURE_NOT_SELECTED_BY_THE_EXPLORATION_SAMPLE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('GROSS_EDGE_CLEARS_THRESHOLD_BUT_FEES_CONSUME_IT', 8, 'EV', 'ECONOMIC'),
        ('INDEPENDENT_FAIR_VALUE_NOT_ESTABLISHED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('LINE_EXCEPTIONAL_SETTLEMENT_TERMS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('MARKET_STATE_UNREADABLE', 9, 'ENTER_PASS', 'SOFTWARE'),
        ('NCAAF_STRICT_FORFEIT_PAYOUTS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_POSTPONEMENT_PAYOUTS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_SUSPENSION_PAYOUTS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_TIED_RESULT_VENUE_PAYOUT_NOT_STATED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_VENUE_CHANGE_VENUE_PAYOUT_NOT_STATED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NET_EV_NOT_POSITIVE_AFTER_FEES', 8, 'EV', 'ECONOMIC'),
        ('NO_ACTION_HAS_POSITIVE_NET_EDGE', 8, 'EV', 'ECONOMIC'),
        ('NO_COMPLETED_GAME_TERMS_FOR_THIS_SPORT', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NO_DEPTH_AT_THE_BEST_LEVEL', 9, 'ENTER_PASS', 'UNCLASSIFIED'),
        ('NO_EXECUTABLE_ASK', 7, 'BOOK', 'SOFTWARE'),
        ('NO_QUALIFIED_MODEL', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('NO_QUALIFIED_PINNACLE_PROBABILITY', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('NO_RESEARCH_MODEL_CANDIDATE_EXISTS', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('NO_SIZED_QUANTITY', 8, 'EV', 'ECONOMIC'),
        ('NO_VENUE_CONTRACT_FOR_EVENT', 3, 'MAPPED', 'EXTERNAL'),
        ('NO_VENUE_NATIVE_CONTRACT_IN_PREMAP', 3, 'MAPPED', 'EXTERNAL'),
        ('OUTCOME_DEPTH_BELOW_FLOOR', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNACLE_PROBABILITY_NOT_QUALIFIED_BY_THE_LANE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_LINE_INPUT_CHANGED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_CLOCK_INVALID', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_FEED_HOLDS_NO_FIXTURE_FOR_EITHER_TEAM', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('PINNAPI_PRIMARY_FIXTURE_AMBIGUOUS', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_FIXTURE_CHANGED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_FIXTURE_LISTS_NO_FULL_GAME_MONEYLINE', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('PINNAPI_PRIMARY_FIXTURE_NOT_YET_POSTED', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('PINNAPI_PRIMARY_INPUT_CHANGED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_NO_EXACT_FIXTURE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PROBABILITY_DEADLINE_PASSED_BEFORE_THE_READ_COULD_FINISH', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PROBABILITY_EVIDENCE_STALE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('QUOTE_STALE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('QUOTE_STALE_AS_DELIVERED_BY_THE_PROVIDER', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('QUOTE_STALE_ON_ARRIVAL', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('RISK_GATE_BLOCKED', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('SETTLEMENT_DIFFERENCE_PRICED_VALUE_IS_ZERO', 8, 'EV', 'ECONOMIC'),
        ('SETTLEMENT_NOT_SUPPORTED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('SIZING_POLICY_NOT_APPLICABLE', 9, 'ENTER_PASS', 'SOFTWARE'),
        ('STRATEGY_ENTRIES_DISABLED', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('STRATEGY_LIFECYCLE_QUARANTINED_NO_PAPER_ENTRY', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('STRATEGY_LIFECYCLE_SHADOW_ONLY_NO_PAPER_ENTRY', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('THE_OBSERVED_BOOK_HAS_NO_LEVEL_ON_THE_SIDE_BOUGHT', 7, 'BOOK', 'ECONOMIC'),
        ('THE_OBSERVED_BOOK_WAS_UNREADABLE_OR_EMPTY', 7, 'BOOK', 'SOFTWARE'),
        ('THE_PROVIDER_COMPETITION_FIXTURES_DO_NOT_MATCH_THE_VENUE_COMPETITION', 3, 'MAPPED', 'SOFTWARE'),
        ('THIS_STRATEGY_ALREADY_HOLDS_THIS_CONTRACT', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('VENUE_ASK_HAS_NO_DEPTH', 7, 'BOOK', 'SOFTWARE'),
        ('VENUE_BOOK_CURRENCY_CONTRADICTED_BY_CONTRACT', 7, 'BOOK', 'SOFTWARE'),
        ('VENUE_BOOK_CURRENCY_NOT_ESTABLISHED', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_BOOK_READ_FAILED', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_BOOK_READ_RETURNED_ERROR', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_GATE_COOLDOWN', 7, 'BOOK', 'SOFTWARE'),
        ('VENUE_MAPPING_AMBIGUOUS', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_NATIVE_DISCOVERED_EVENT_NOT_IN_THE_WINDOW', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_NATIVE_EVENT_MATCHES_ONLY_ONE_TEAM', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_NATIVE_LEAGUE_NOT_ADMITTED', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_RATE_LIMITED', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_RULES_TEXT_NOT_RECORDED_ON_THE_VALUATION_ROW', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('VENUE_TIMEOUT', 7, 'BOOK', 'EXTERNAL'),
        ('VOID_ABANDONMENT_BOOK_RULE_NOT_HELD', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('VOID_ABANDONMENT_RULE_CONFLICTS_WITH_BOOK_RULE', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('WS_REFERENCE_NOT_USABLE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('WS_TRIGGER_SUPERSEDED', 1, 'PROVIDER', 'SOFTWARE'),
        ('XAVIER_CANNOT_PROTECT_THIS_ENTRY_NO_PROTECTIVE_PRICE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('XAVIER_HELD_READ_CANNOT_PRICE_THIS_CONTRACT', 9, 'ENTER_PASS', 'SOFTWARE')),
d AS (
    SELECT dd.decision_id, dd.strategy, dd.policy_version, dd.verdict,
           dd.fixture, dd.us_market_slug, dd.holding_side, dd.refusals,
           CASE WHEN dd.decided_at >= c.t THEN 'FORWARD_BIND' ELSE 'HISTORICAL' END AS cohort
      FROM paper_decisions dd CROSS JOIN c),
lc AS (
    SELECT DISTINCT ON (d.decision_id) d.decision_id, x.code,
           coalesce(m.rnk, 9) AS rnk, coalesce(m.stage, 'ENTER_PASS') AS stage,
           coalesce(m.cls, 'UNCLASSIFIED') AS cls
      FROM d CROSS JOIN LATERAL unnest(d.refusals) WITH ORDINALITY AS x(code, pos)
      LEFT JOIN m ON m.code = x.code
     ORDER BY d.decision_id, coalesce(m.rnk, 9),
              (x.code = 'PINNACLE_PROBABILITY_NOT_QUALIFIED_BY_THE_LANE'), x.pos),
ev AS (
    SELECT e.decision_id, bool_or(e.detail ->> 'bind_refusal' IS NULL) AS bind_passed
      FROM paper_profitability_evaluations e
     WHERE e.decision_id IS NOT NULL GROUP BY 1),
gq AS (
    SELECT f.group_id,
           coalesce(sum(f.qty) FILTER (WHERE f.direction = 'BUY'), 0)
         - coalesce(sum(f.qty) FILTER (WHERE f.direction = 'SELL'), 0) AS net_filled
      FROM paper_fills f GROUP BY 1),
gs AS (
    SELECT z.group_id, sum(z.qty) AS settled_qty FROM (
        SELECT DISTINCT ON (position_key) group_id, qty FROM paper_settlements
         ORDER BY position_key, version DESC) z GROUP BY 1),
od AS (
    SELECT o.decision_id, bool_or(o.filled_qty > 0) AS filled,
           bool_or(o.filled_qty > 0 AND gq.net_filled - coalesce(gs.settled_qty, 0) <= 1e-9) AS closed,
           bool_or(gs.group_id IS NOT NULL) AS settled
      FROM paper_orders o
      LEFT JOIN gq ON gq.group_id = o.group_id
      LEFT JOIN gs ON gs.group_id = o.group_id
     WHERE o.role = 'ENTRY' AND o.decision_id IS NOT NULL
     GROUP BY 1),
r AS (
    SELECT d.cohort, d.strategy, d.policy_version, d.decision_id, d.verdict, d.fixture,
           d.us_market_slug || ':' || coalesce(d.holding_side, '?') AS cs,
           CASE WHEN d.verdict = 'ENTER' THEN 10 ELSE coalesce(lc.rnk, 9) END AS rnk,
           CASE WHEN d.verdict = 'ENTER' THEN 'ENTERED' ELSE coalesce(lc.stage, 'ENTER_PASS') END AS stage,
           CASE WHEN d.verdict = 'ENTER' THEN NULL
                WHEN lc.code IS NULL THEN 'PAPER_DECISION_REFUSED_WITHOUT_A_CODE'
                ELSE lc.code END AS code,
           CASE WHEN d.verdict = 'ENTER' THEN NULL ELSE coalesce(lc.cls, 'SOFTWARE') END AS cls,
           (ev.decision_id IS NOT NULL) AS has_eval,
           coalesce(ev.bind_passed, false) AS bind_passed,
           (od.decision_id IS NOT NULL) AS ordered,
           coalesce(od.filled, false) AS filled,
           coalesce(od.closed, false) AS closed,
           coalesce(od.settled, false) AS settled
      FROM d LEFT JOIN lc USING (decision_id)
      LEFT JOIN ev USING (decision_id)
      LEFT JOIN od USING (decision_id)),
fx AS (
    SELECT r.cohort, r.strategy, r.policy_version, r.fixture AS k,
           max(r.rnk) AS rnk,
           bool_or(r.code IS DISTINCT FROM 'NO_SIZED_QUANTITY' AND r.rnk >= 8) AS priced,
           bool_or(r.rnk >= 9 AND r.code IS DISTINCT FROM 'THIS_STRATEGY_ALREADY_HOLDS_THIS_CONTRACT'
                   AND r.code IS DISTINCT FROM 'XAVIER_HELD_READ_CANNOT_PRICE_THIS_CONTRACT'
                   AND r.code IS DISTINCT FROM 'XAVIER_CANNOT_PROTECT_THIS_ENTRY_NO_PROTECTIVE_PRICE'
                   AND r.code IS DISTINCT FROM 'NO_DEPTH_AT_THE_BEST_LEVEL'
                   AND r.code IS DISTINCT FROM 'FIXTURE_NOT_SELECTED_BY_THE_EXPLORATION_SAMPLE'
                   AND r.code IS DISTINCT FROM 'EXPLORATION_ALREADY_HOLDS_THIS_FIXTURE'
                   AND r.code IS DISTINCT FROM 'ANOTHER_STRATEGY_HOLDS_EXPOSURE_TO_THIS_FIXTURE') AS policy_pos,
           bool_or(r.has_eval OR r.verdict = 'ENTER') AS exec_pos,
           bool_or(r.bind_passed) AS bind_pos,
           bool_or(r.ordered) AS ordered, bool_or(r.filled) AS filled,
           bool_or(r.closed) AS closed, bool_or(r.settled) AS settled
      FROM r GROUP BY 1, 2, 3, 4)
SELECT fx.cohort, fx.strategy, fx.policy_version,
       count(*)                                      AS s1_eligible,
       count(*) FILTER (WHERE fx.rnk > 4)            AS s2_exact_mapping,
       count(*) FILTER (WHERE fx.rnk > 7)            AS s3_fresh_inputs,
       count(*) FILTER (WHERE fx.priced)             AS s4_fully_priced,
       count(*) FILTER (WHERE fx.policy_pos)         AS s5a_policy_ev_pos,
       count(*) FILTER (WHERE fx.exec_pos)           AS s5b_exec_ev_pos,
       count(*) FILTER (WHERE fx.bind_pos)           AS s5c_all_in_ev_pos,
       count(*) FILTER (WHERE fx.ordered)            AS s6_qualified,
       count(*) FILTER (WHERE fx.filled)             AS s7_filled,
       count(*) FILTER (WHERE fx.closed)             AS s8_closed,
       count(*) FILTER (WHERE fx.settled)            AS s8s_settled
  FROM fx GROUP BY 1, 2, 3 ORDER BY 1 DESC, 2, 3;

\echo '== 2b.2 CONTRACT-SIDE funnel per cohort x strategy x frozen policy'
WITH c AS (SELECT applied_at AS t FROM schema_migrations
            WHERE version = '309_paper_profitability_bind.sql'),
m(code, rnk, stage, cls) AS (VALUES
        ('ANOTHER_STRATEGY_HOLDS_EXPOSURE_TO_THIS_FIXTURE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('BELOW_MIN_GROSS_EDGE', 8, 'EV', 'ECONOMIC'),
        ('BELOW_MIN_NET_EV', 8, 'EV', 'ECONOMIC'),
        ('BOOK_READ_DID_NOT_FINISH_INSIDE_THE_DECISION_DEADLINE', 7, 'BOOK', 'SOFTWARE'),
        ('CALIBRATION_ONLY_RECORD_IS_NOT_AN_ENTRY_CANDIDATE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('CASH_WAIT_ALL_IN_EXECUTABLE_EV_NOT_POSITIVE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('CASH_WAIT_CALIBRATED_ALL_IN_EV_NOT_POSITIVE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('CASH_WAIT_FORWARD_ECONOMICS_NEGATIVE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('CASH_WAIT_TOTAL_EXECUTABLE_EV_NOT_POSITIVE', 8, 'EV', 'ECONOMIC'),
        ('DEPTH_NOT_ESTABLISHED', 7, 'BOOK', 'SOFTWARE'),
        ('DRAW_HANDLING_NOT_RECONCILED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('EXECUTION_ESTIMATE_NOT_IDENTIFIED', 7, 'BOOK', 'SOFTWARE'),
        ('EXPLORATION_ALREADY_HOLDS_THIS_FIXTURE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('FEED_MARKET_NOT_IN_CURRENT_STATE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_OWNERSHIP_NOT_HELD', 5, 'MODEL', 'SOFTWARE'),
        ('FEED_QUOTE_AGE_UNKNOWN_NO_OBSERVED_CHANGE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_QUOTE_CHANGE_TIME_IN_THE_FUTURE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_QUOTE_OLDER_THAN_LIMIT', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_SOCKET_CLOSED', 1, 'PROVIDER', 'SOFTWARE'),
        ('FIXTURE_NOT_SELECTED_BY_THE_EXPLORATION_SAMPLE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('GROSS_EDGE_CLEARS_THRESHOLD_BUT_FEES_CONSUME_IT', 8, 'EV', 'ECONOMIC'),
        ('INDEPENDENT_FAIR_VALUE_NOT_ESTABLISHED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('LINE_EXCEPTIONAL_SETTLEMENT_TERMS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('MARKET_STATE_UNREADABLE', 9, 'ENTER_PASS', 'SOFTWARE'),
        ('NCAAF_STRICT_FORFEIT_PAYOUTS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_POSTPONEMENT_PAYOUTS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_SUSPENSION_PAYOUTS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_TIED_RESULT_VENUE_PAYOUT_NOT_STATED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_VENUE_CHANGE_VENUE_PAYOUT_NOT_STATED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NET_EV_NOT_POSITIVE_AFTER_FEES', 8, 'EV', 'ECONOMIC'),
        ('NO_ACTION_HAS_POSITIVE_NET_EDGE', 8, 'EV', 'ECONOMIC'),
        ('NO_COMPLETED_GAME_TERMS_FOR_THIS_SPORT', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NO_DEPTH_AT_THE_BEST_LEVEL', 9, 'ENTER_PASS', 'UNCLASSIFIED'),
        ('NO_EXECUTABLE_ASK', 7, 'BOOK', 'SOFTWARE'),
        ('NO_QUALIFIED_MODEL', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('NO_QUALIFIED_PINNACLE_PROBABILITY', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('NO_RESEARCH_MODEL_CANDIDATE_EXISTS', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('NO_SIZED_QUANTITY', 8, 'EV', 'ECONOMIC'),
        ('NO_VENUE_CONTRACT_FOR_EVENT', 3, 'MAPPED', 'EXTERNAL'),
        ('NO_VENUE_NATIVE_CONTRACT_IN_PREMAP', 3, 'MAPPED', 'EXTERNAL'),
        ('OUTCOME_DEPTH_BELOW_FLOOR', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNACLE_PROBABILITY_NOT_QUALIFIED_BY_THE_LANE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_LINE_INPUT_CHANGED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_CLOCK_INVALID', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_FEED_HOLDS_NO_FIXTURE_FOR_EITHER_TEAM', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('PINNAPI_PRIMARY_FIXTURE_AMBIGUOUS', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_FIXTURE_CHANGED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_FIXTURE_LISTS_NO_FULL_GAME_MONEYLINE', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('PINNAPI_PRIMARY_FIXTURE_NOT_YET_POSTED', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('PINNAPI_PRIMARY_INPUT_CHANGED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_NO_EXACT_FIXTURE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PROBABILITY_DEADLINE_PASSED_BEFORE_THE_READ_COULD_FINISH', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PROBABILITY_EVIDENCE_STALE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('QUOTE_STALE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('QUOTE_STALE_AS_DELIVERED_BY_THE_PROVIDER', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('QUOTE_STALE_ON_ARRIVAL', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('RISK_GATE_BLOCKED', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('SETTLEMENT_DIFFERENCE_PRICED_VALUE_IS_ZERO', 8, 'EV', 'ECONOMIC'),
        ('SETTLEMENT_NOT_SUPPORTED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('SIZING_POLICY_NOT_APPLICABLE', 9, 'ENTER_PASS', 'SOFTWARE'),
        ('STRATEGY_ENTRIES_DISABLED', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('STRATEGY_LIFECYCLE_QUARANTINED_NO_PAPER_ENTRY', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('STRATEGY_LIFECYCLE_SHADOW_ONLY_NO_PAPER_ENTRY', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('THE_OBSERVED_BOOK_HAS_NO_LEVEL_ON_THE_SIDE_BOUGHT', 7, 'BOOK', 'ECONOMIC'),
        ('THE_OBSERVED_BOOK_WAS_UNREADABLE_OR_EMPTY', 7, 'BOOK', 'SOFTWARE'),
        ('THE_PROVIDER_COMPETITION_FIXTURES_DO_NOT_MATCH_THE_VENUE_COMPETITION', 3, 'MAPPED', 'SOFTWARE'),
        ('THIS_STRATEGY_ALREADY_HOLDS_THIS_CONTRACT', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('VENUE_ASK_HAS_NO_DEPTH', 7, 'BOOK', 'SOFTWARE'),
        ('VENUE_BOOK_CURRENCY_CONTRADICTED_BY_CONTRACT', 7, 'BOOK', 'SOFTWARE'),
        ('VENUE_BOOK_CURRENCY_NOT_ESTABLISHED', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_BOOK_READ_FAILED', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_BOOK_READ_RETURNED_ERROR', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_GATE_COOLDOWN', 7, 'BOOK', 'SOFTWARE'),
        ('VENUE_MAPPING_AMBIGUOUS', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_NATIVE_DISCOVERED_EVENT_NOT_IN_THE_WINDOW', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_NATIVE_EVENT_MATCHES_ONLY_ONE_TEAM', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_NATIVE_LEAGUE_NOT_ADMITTED', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_RATE_LIMITED', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_RULES_TEXT_NOT_RECORDED_ON_THE_VALUATION_ROW', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('VENUE_TIMEOUT', 7, 'BOOK', 'EXTERNAL'),
        ('VOID_ABANDONMENT_BOOK_RULE_NOT_HELD', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('VOID_ABANDONMENT_RULE_CONFLICTS_WITH_BOOK_RULE', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('WS_REFERENCE_NOT_USABLE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('WS_TRIGGER_SUPERSEDED', 1, 'PROVIDER', 'SOFTWARE'),
        ('XAVIER_CANNOT_PROTECT_THIS_ENTRY_NO_PROTECTIVE_PRICE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('XAVIER_HELD_READ_CANNOT_PRICE_THIS_CONTRACT', 9, 'ENTER_PASS', 'SOFTWARE')),
d AS (
    SELECT dd.decision_id, dd.strategy, dd.policy_version, dd.verdict,
           dd.fixture, dd.us_market_slug, dd.holding_side, dd.refusals,
           CASE WHEN dd.decided_at >= c.t THEN 'FORWARD_BIND' ELSE 'HISTORICAL' END AS cohort
      FROM paper_decisions dd CROSS JOIN c),
lc AS (
    SELECT DISTINCT ON (d.decision_id) d.decision_id, x.code,
           coalesce(m.rnk, 9) AS rnk, coalesce(m.stage, 'ENTER_PASS') AS stage,
           coalesce(m.cls, 'UNCLASSIFIED') AS cls
      FROM d CROSS JOIN LATERAL unnest(d.refusals) WITH ORDINALITY AS x(code, pos)
      LEFT JOIN m ON m.code = x.code
     ORDER BY d.decision_id, coalesce(m.rnk, 9),
              (x.code = 'PINNACLE_PROBABILITY_NOT_QUALIFIED_BY_THE_LANE'), x.pos),
ev AS (
    SELECT e.decision_id, bool_or(e.detail ->> 'bind_refusal' IS NULL) AS bind_passed
      FROM paper_profitability_evaluations e
     WHERE e.decision_id IS NOT NULL GROUP BY 1),
gq AS (
    SELECT f.group_id,
           coalesce(sum(f.qty) FILTER (WHERE f.direction = 'BUY'), 0)
         - coalesce(sum(f.qty) FILTER (WHERE f.direction = 'SELL'), 0) AS net_filled
      FROM paper_fills f GROUP BY 1),
gs AS (
    SELECT z.group_id, sum(z.qty) AS settled_qty FROM (
        SELECT DISTINCT ON (position_key) group_id, qty FROM paper_settlements
         ORDER BY position_key, version DESC) z GROUP BY 1),
od AS (
    SELECT o.decision_id, bool_or(o.filled_qty > 0) AS filled,
           bool_or(o.filled_qty > 0 AND gq.net_filled - coalesce(gs.settled_qty, 0) <= 1e-9) AS closed,
           bool_or(gs.group_id IS NOT NULL) AS settled
      FROM paper_orders o
      LEFT JOIN gq ON gq.group_id = o.group_id
      LEFT JOIN gs ON gs.group_id = o.group_id
     WHERE o.role = 'ENTRY' AND o.decision_id IS NOT NULL
     GROUP BY 1),
r AS (
    SELECT d.cohort, d.strategy, d.policy_version, d.decision_id, d.verdict, d.fixture,
           d.us_market_slug || ':' || coalesce(d.holding_side, '?') AS cs,
           CASE WHEN d.verdict = 'ENTER' THEN 10 ELSE coalesce(lc.rnk, 9) END AS rnk,
           CASE WHEN d.verdict = 'ENTER' THEN 'ENTERED' ELSE coalesce(lc.stage, 'ENTER_PASS') END AS stage,
           CASE WHEN d.verdict = 'ENTER' THEN NULL
                WHEN lc.code IS NULL THEN 'PAPER_DECISION_REFUSED_WITHOUT_A_CODE'
                ELSE lc.code END AS code,
           CASE WHEN d.verdict = 'ENTER' THEN NULL ELSE coalesce(lc.cls, 'SOFTWARE') END AS cls,
           (ev.decision_id IS NOT NULL) AS has_eval,
           coalesce(ev.bind_passed, false) AS bind_passed,
           (od.decision_id IS NOT NULL) AS ordered,
           coalesce(od.filled, false) AS filled,
           coalesce(od.closed, false) AS closed,
           coalesce(od.settled, false) AS settled
      FROM d LEFT JOIN lc USING (decision_id)
      LEFT JOIN ev USING (decision_id)
      LEFT JOIN od USING (decision_id)),
fx AS (
    SELECT r.cohort, r.strategy, r.policy_version, r.cs AS k,
           max(r.rnk) AS rnk,
           bool_or(r.code IS DISTINCT FROM 'NO_SIZED_QUANTITY' AND r.rnk >= 8) AS priced,
           bool_or(r.rnk >= 9 AND r.code IS DISTINCT FROM 'THIS_STRATEGY_ALREADY_HOLDS_THIS_CONTRACT'
                   AND r.code IS DISTINCT FROM 'XAVIER_HELD_READ_CANNOT_PRICE_THIS_CONTRACT'
                   AND r.code IS DISTINCT FROM 'XAVIER_CANNOT_PROTECT_THIS_ENTRY_NO_PROTECTIVE_PRICE'
                   AND r.code IS DISTINCT FROM 'NO_DEPTH_AT_THE_BEST_LEVEL'
                   AND r.code IS DISTINCT FROM 'FIXTURE_NOT_SELECTED_BY_THE_EXPLORATION_SAMPLE'
                   AND r.code IS DISTINCT FROM 'EXPLORATION_ALREADY_HOLDS_THIS_FIXTURE'
                   AND r.code IS DISTINCT FROM 'ANOTHER_STRATEGY_HOLDS_EXPOSURE_TO_THIS_FIXTURE') AS policy_pos,
           bool_or(r.has_eval OR r.verdict = 'ENTER') AS exec_pos,
           bool_or(r.bind_passed) AS bind_pos,
           bool_or(r.ordered) AS ordered, bool_or(r.filled) AS filled,
           bool_or(r.closed) AS closed, bool_or(r.settled) AS settled
      FROM r GROUP BY 1, 2, 3, 4)
SELECT fx.cohort, fx.strategy, fx.policy_version,
       count(*)                                      AS s1_eligible,
       count(*) FILTER (WHERE fx.rnk > 4)            AS s2_exact_mapping,
       count(*) FILTER (WHERE fx.rnk > 7)            AS s3_fresh_inputs,
       count(*) FILTER (WHERE fx.priced)             AS s4_fully_priced,
       count(*) FILTER (WHERE fx.policy_pos)         AS s5a_policy_ev_pos,
       count(*) FILTER (WHERE fx.exec_pos)           AS s5b_exec_ev_pos,
       count(*) FILTER (WHERE fx.bind_pos)           AS s5c_all_in_ev_pos,
       count(*) FILTER (WHERE fx.ordered)            AS s6_qualified,
       count(*) FILTER (WHERE fx.filled)             AS s7_filled,
       count(*) FILTER (WHERE fx.closed)             AS s8_closed,
       count(*) FILTER (WHERE fx.settled)            AS s8s_settled
  FROM fx GROUP BY 1, 2, 3 ORDER BY 1 DESC, 2, 3;

\echo '== 2b.3 HISTORICAL cohort: decisions by the stage and class they were lost at (top codes)'
WITH c AS (SELECT applied_at AS t FROM schema_migrations
            WHERE version = '309_paper_profitability_bind.sql'),
m(code, rnk, stage, cls) AS (VALUES
        ('ANOTHER_STRATEGY_HOLDS_EXPOSURE_TO_THIS_FIXTURE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('BELOW_MIN_GROSS_EDGE', 8, 'EV', 'ECONOMIC'),
        ('BELOW_MIN_NET_EV', 8, 'EV', 'ECONOMIC'),
        ('BOOK_READ_DID_NOT_FINISH_INSIDE_THE_DECISION_DEADLINE', 7, 'BOOK', 'SOFTWARE'),
        ('CALIBRATION_ONLY_RECORD_IS_NOT_AN_ENTRY_CANDIDATE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('CASH_WAIT_ALL_IN_EXECUTABLE_EV_NOT_POSITIVE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('CASH_WAIT_CALIBRATED_ALL_IN_EV_NOT_POSITIVE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('CASH_WAIT_FORWARD_ECONOMICS_NEGATIVE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('CASH_WAIT_TOTAL_EXECUTABLE_EV_NOT_POSITIVE', 8, 'EV', 'ECONOMIC'),
        ('DEPTH_NOT_ESTABLISHED', 7, 'BOOK', 'SOFTWARE'),
        ('DRAW_HANDLING_NOT_RECONCILED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('EXECUTION_ESTIMATE_NOT_IDENTIFIED', 7, 'BOOK', 'SOFTWARE'),
        ('EXPLORATION_ALREADY_HOLDS_THIS_FIXTURE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('FEED_MARKET_NOT_IN_CURRENT_STATE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_OWNERSHIP_NOT_HELD', 5, 'MODEL', 'SOFTWARE'),
        ('FEED_QUOTE_AGE_UNKNOWN_NO_OBSERVED_CHANGE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_QUOTE_CHANGE_TIME_IN_THE_FUTURE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_QUOTE_OLDER_THAN_LIMIT', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('FEED_SOCKET_CLOSED', 1, 'PROVIDER', 'SOFTWARE'),
        ('FIXTURE_NOT_SELECTED_BY_THE_EXPLORATION_SAMPLE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('GROSS_EDGE_CLEARS_THRESHOLD_BUT_FEES_CONSUME_IT', 8, 'EV', 'ECONOMIC'),
        ('INDEPENDENT_FAIR_VALUE_NOT_ESTABLISHED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('LINE_EXCEPTIONAL_SETTLEMENT_TERMS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('MARKET_STATE_UNREADABLE', 9, 'ENTER_PASS', 'SOFTWARE'),
        ('NCAAF_STRICT_FORFEIT_PAYOUTS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_POSTPONEMENT_PAYOUTS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_SUSPENSION_PAYOUTS_DIFFER', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_TIED_RESULT_VENUE_PAYOUT_NOT_STATED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NCAAF_STRICT_VENUE_CHANGE_VENUE_PAYOUT_NOT_STATED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NET_EV_NOT_POSITIVE_AFTER_FEES', 8, 'EV', 'ECONOMIC'),
        ('NO_ACTION_HAS_POSITIVE_NET_EDGE', 8, 'EV', 'ECONOMIC'),
        ('NO_COMPLETED_GAME_TERMS_FOR_THIS_SPORT', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('NO_DEPTH_AT_THE_BEST_LEVEL', 9, 'ENTER_PASS', 'UNCLASSIFIED'),
        ('NO_EXECUTABLE_ASK', 7, 'BOOK', 'SOFTWARE'),
        ('NO_QUALIFIED_MODEL', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('NO_QUALIFIED_PINNACLE_PROBABILITY', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('NO_RESEARCH_MODEL_CANDIDATE_EXISTS', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('NO_SIZED_QUANTITY', 8, 'EV', 'ECONOMIC'),
        ('NO_VENUE_CONTRACT_FOR_EVENT', 3, 'MAPPED', 'EXTERNAL'),
        ('NO_VENUE_NATIVE_CONTRACT_IN_PREMAP', 3, 'MAPPED', 'EXTERNAL'),
        ('OUTCOME_DEPTH_BELOW_FLOOR', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNACLE_PROBABILITY_NOT_QUALIFIED_BY_THE_LANE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_LINE_INPUT_CHANGED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_CLOCK_INVALID', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_FEED_HOLDS_NO_FIXTURE_FOR_EITHER_TEAM', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('PINNAPI_PRIMARY_FIXTURE_AMBIGUOUS', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_FIXTURE_CHANGED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_FIXTURE_LISTS_NO_FULL_GAME_MONEYLINE', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('PINNAPI_PRIMARY_FIXTURE_NOT_YET_POSTED', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('PINNAPI_PRIMARY_INPUT_CHANGED', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PINNAPI_PRIMARY_NO_EXACT_FIXTURE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PROBABILITY_DEADLINE_PASSED_BEFORE_THE_READ_COULD_FINISH', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('PROBABILITY_EVIDENCE_STALE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('QUOTE_STALE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('QUOTE_STALE_AS_DELIVERED_BY_THE_PROVIDER', 6, 'FAIR_VALUE', 'EXTERNAL'),
        ('QUOTE_STALE_ON_ARRIVAL', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('RISK_GATE_BLOCKED', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('SETTLEMENT_DIFFERENCE_PRICED_VALUE_IS_ZERO', 8, 'EV', 'ECONOMIC'),
        ('SETTLEMENT_NOT_SUPPORTED', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('SIZING_POLICY_NOT_APPLICABLE', 9, 'ENTER_PASS', 'SOFTWARE'),
        ('STRATEGY_ENTRIES_DISABLED', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('STRATEGY_LIFECYCLE_QUARANTINED_NO_PAPER_ENTRY', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('STRATEGY_LIFECYCLE_SHADOW_ONLY_NO_PAPER_ENTRY', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('THE_OBSERVED_BOOK_HAS_NO_LEVEL_ON_THE_SIDE_BOUGHT', 7, 'BOOK', 'ECONOMIC'),
        ('THE_OBSERVED_BOOK_WAS_UNREADABLE_OR_EMPTY', 7, 'BOOK', 'SOFTWARE'),
        ('THE_PROVIDER_COMPETITION_FIXTURES_DO_NOT_MATCH_THE_VENUE_COMPETITION', 3, 'MAPPED', 'SOFTWARE'),
        ('THIS_STRATEGY_ALREADY_HOLDS_THIS_CONTRACT', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('VENUE_ASK_HAS_NO_DEPTH', 7, 'BOOK', 'SOFTWARE'),
        ('VENUE_BOOK_CURRENCY_CONTRADICTED_BY_CONTRACT', 7, 'BOOK', 'SOFTWARE'),
        ('VENUE_BOOK_CURRENCY_NOT_ESTABLISHED', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_BOOK_READ_FAILED', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_BOOK_READ_RETURNED_ERROR', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_GATE_COOLDOWN', 7, 'BOOK', 'SOFTWARE'),
        ('VENUE_MAPPING_AMBIGUOUS', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_NATIVE_DISCOVERED_EVENT_NOT_IN_THE_WINDOW', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_NATIVE_EVENT_MATCHES_ONLY_ONE_TEAM', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_NATIVE_LEAGUE_NOT_ADMITTED', 3, 'MAPPED', 'SOFTWARE'),
        ('VENUE_RATE_LIMITED', 7, 'BOOK', 'EXTERNAL'),
        ('VENUE_RULES_TEXT_NOT_RECORDED_ON_THE_VALUATION_ROW', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('VENUE_TIMEOUT', 7, 'BOOK', 'EXTERNAL'),
        ('VOID_ABANDONMENT_BOOK_RULE_NOT_HELD', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('VOID_ABANDONMENT_RULE_CONFLICTS_WITH_BOOK_RULE', 4, 'SETTLEMENT', 'SOFTWARE'),
        ('WS_REFERENCE_NOT_USABLE', 6, 'FAIR_VALUE', 'SOFTWARE'),
        ('WS_TRIGGER_SUPERSEDED', 1, 'PROVIDER', 'SOFTWARE'),
        ('XAVIER_CANNOT_PROTECT_THIS_ENTRY_NO_PROTECTIVE_PRICE', 9, 'ENTER_PASS', 'ECONOMIC'),
        ('XAVIER_HELD_READ_CANNOT_PRICE_THIS_CONTRACT', 9, 'ENTER_PASS', 'SOFTWARE')),
d AS (
    SELECT dd.decision_id, dd.strategy, dd.policy_version, dd.verdict,
           dd.fixture, dd.us_market_slug, dd.holding_side, dd.refusals,
           CASE WHEN dd.decided_at >= c.t THEN 'FORWARD_BIND' ELSE 'HISTORICAL' END AS cohort
      FROM paper_decisions dd CROSS JOIN c),
lc AS (
    SELECT DISTINCT ON (d.decision_id) d.decision_id, x.code,
           coalesce(m.rnk, 9) AS rnk, coalesce(m.stage, 'ENTER_PASS') AS stage,
           coalesce(m.cls, 'UNCLASSIFIED') AS cls
      FROM d CROSS JOIN LATERAL unnest(d.refusals) WITH ORDINALITY AS x(code, pos)
      LEFT JOIN m ON m.code = x.code
     ORDER BY d.decision_id, coalesce(m.rnk, 9),
              (x.code = 'PINNACLE_PROBABILITY_NOT_QUALIFIED_BY_THE_LANE'), x.pos),
ev AS (
    SELECT e.decision_id, bool_or(e.detail ->> 'bind_refusal' IS NULL) AS bind_passed
      FROM paper_profitability_evaluations e
     WHERE e.decision_id IS NOT NULL GROUP BY 1),
gq AS (
    SELECT f.group_id,
           coalesce(sum(f.qty) FILTER (WHERE f.direction = 'BUY'), 0)
         - coalesce(sum(f.qty) FILTER (WHERE f.direction = 'SELL'), 0) AS net_filled
      FROM paper_fills f GROUP BY 1),
gs AS (
    SELECT z.group_id, sum(z.qty) AS settled_qty FROM (
        SELECT DISTINCT ON (position_key) group_id, qty FROM paper_settlements
         ORDER BY position_key, version DESC) z GROUP BY 1),
od AS (
    SELECT o.decision_id, bool_or(o.filled_qty > 0) AS filled,
           bool_or(o.filled_qty > 0 AND gq.net_filled - coalesce(gs.settled_qty, 0) <= 1e-9) AS closed,
           bool_or(gs.group_id IS NOT NULL) AS settled
      FROM paper_orders o
      LEFT JOIN gq ON gq.group_id = o.group_id
      LEFT JOIN gs ON gs.group_id = o.group_id
     WHERE o.role = 'ENTRY' AND o.decision_id IS NOT NULL
     GROUP BY 1),
r AS (
    SELECT d.cohort, d.strategy, d.policy_version, d.decision_id, d.verdict, d.fixture,
           d.us_market_slug || ':' || coalesce(d.holding_side, '?') AS cs,
           CASE WHEN d.verdict = 'ENTER' THEN 10 ELSE coalesce(lc.rnk, 9) END AS rnk,
           CASE WHEN d.verdict = 'ENTER' THEN 'ENTERED' ELSE coalesce(lc.stage, 'ENTER_PASS') END AS stage,
           CASE WHEN d.verdict = 'ENTER' THEN NULL
                WHEN lc.code IS NULL THEN 'PAPER_DECISION_REFUSED_WITHOUT_A_CODE'
                ELSE lc.code END AS code,
           CASE WHEN d.verdict = 'ENTER' THEN NULL ELSE coalesce(lc.cls, 'SOFTWARE') END AS cls,
           (ev.decision_id IS NOT NULL) AS has_eval,
           coalesce(ev.bind_passed, false) AS bind_passed,
           (od.decision_id IS NOT NULL) AS ordered,
           coalesce(od.filled, false) AS filled,
           coalesce(od.closed, false) AS closed,
           coalesce(od.settled, false) AS settled
      FROM d LEFT JOIN lc USING (decision_id)
      LEFT JOIN ev USING (decision_id)
      LEFT JOIN od USING (decision_id))
SELECT r.strategy, r.policy_version, r.stage, coalesce(r.cls, '-') AS class,
       coalesce(r.code, '(entered)') AS code,
       count(*) AS decisions, count(DISTINCT r.cs) AS contract_sides,
       count(DISTINCT r.fixture) AS fixtures
  FROM r WHERE r.cohort = 'HISTORICAL'
 GROUP BY 1, 2, 3, 4, 5
HAVING count(*) >= 20 OR min(r.rnk) >= 9
 ORDER BY 1, 2, min(r.rnk), decisions DESC;
