-- READ-ONLY. RC6.3b root-cause audit, group software-reds, lane H0 (the
-- replay harness, backend/tests/test_rc63_software_reds_replay.py). THE
-- FIRST-LOSS CENSUS'S INPUTS FOR AN HOURLY SERIES: for each of `hours`
-- one-hour windows ending at `now`, `now` - 1 h, ... -- hour k is
-- [now - (k+1)*3600, now - k*3600 + 1), the window the approved-judge gate
-- software_reds_zero reads (capital_readiness.feeds.gate_software_reds_zero:
-- coverage_first_loss.read(since = now - 3600, until = now + 1)) -- the
-- production statements of coverage_first_loss (ledger_events_sql(),
-- VALUATIONS_SQL, DECISIONS_SQL) verbatim with their parameters bound, one
-- JSON line per row: kind `hour` (the window), `ev` (one furthest
-- ext_candidate_outcomes row per provider event), `val` (the linked
-- external_valuations), `dec` (the paper_decisions on them). The replay
-- (backend/tools/sw_reds_hourly_census.py --log <run log>) runs
-- coverage_first_loss.census over each hour with the taxonomy of the
-- checked-out source and renders the hourly SOFTWARE-by-code table.
--
-- GENERATED: backend/tools/sw_reds_hourly_census.py --sql <now> --hours <n>
-- (the test pins this file to the generator, so a change to the production
-- statements regenerates it rather than letting the export drift).
--
-- PARAMETER: `now` (epoch seconds, the instant the newest window ends at)
-- and `hours` on the first WITH line. The two fixed windows of the first
-- version of this file (now = 1791626074.8284767 and 1791626141.534181,
-- the packet's completion.json and capital_readiness.json instants, sha256
-- 5d72395ad2b0f67dc745e256fab130da19c321fb0b6438a770efeb4960c339fb) were
-- run as research-sql 38055963121 and are tests/fixtures/
-- rc63_sw_reds_104_events.json.
--
-- SELECT only: no mutating keyword, no psql meta-command but \echo.

\echo == RC63_SW_REDS_HOURLY_CENSUS_V1 now=1791651274.8284767 hours=24: one JSON line per row, kinds hour / ev / val / dec ==
WITH p AS (SELECT 1791651274.8284767::float8 AS now, 24::int AS hours),
h AS (
    SELECT k, p.now - k * 3600 AS now_k,
           p.now - (k + 1) * 3600 AS since,
           p.now - k * 3600 + 1 AS until
      FROM p, generate_series(0, p.hours - 1) AS k),
-- coverage_first_loss.ledger_events_sql(): $1 since, $2 until, $3 the cap
ev AS (
    SELECT h.k, e.* FROM h CROSS JOIN LATERAL (
            WITH r AS (
                SELECT id, sport_key, family, provider_event_id, cycle_at, outcome,
                       first_refusal, codes, us_market_slug, home, away,
                       commence_time, coalesce(stage, CASE split_part(coalesce(first_refusal, ''), ':', 1) WHEN 'ACTION_EXPOSURE_EFFECT_NOT_IDENTIFIED' THEN '7_RISK' WHEN 'EXECUTION_ESTIMATE_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'LINE_EXCEPTIONAL_SETTLEMENT_TERMS_DIFFER' THEN '4_SETTLEMENT_SCOPE' WHEN 'NO_ACTION_HAS_POSITIVE_NET_EDGE' THEN '8_ECONOMICS' WHEN 'NO_OBSERVED_DEPTH_INSIDE_THE_BREAK_EVEN_LIMIT' THEN '5_EXECUTION_ESTIMATE' WHEN 'NO_PREMAP_CONTRACT_FOR_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'NO_RAIL_HEADROOM_FOR_ANY_POSITION' THEN '6_SIZING' WHEN 'NO_VENUE_CONTRACT_FOR_EVENT' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_CONTRACT_IN_PREMAP' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_EVENT_FOR_FIXTURE' THEN '3_IDENTITY' WHEN 'OPEN_SHADOW_BOOK_NOT_READ' THEN '7_RISK' WHEN 'OVERTIME_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'PAYOUT_OUTCOME_DISAGREES_WITH_THE_VENUE_INTENT' THEN '3_IDENTITY' WHEN 'PAYOUT_OUTCOME_INDEX_NOT_BOUND_TO_A_TOKEN' THEN '3_IDENTITY' WHEN 'PRICED_OUTCOME_NOT_IN_THE_PROVIDER_QUOTE' THEN '3_IDENTITY' WHEN 'P_FILL_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'RAIL_HEADROOM_NOT_MEASURED' THEN '6_SIZING' WHEN 'RISK_GATE_BLOCKED' THEN '7_RISK' WHEN 'SETTLEMENT_SCOPE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'SETTLEMENT_TERMS_CONFLICT' THEN '4_SETTLEMENT_SCOPE' WHEN 'SIZING_POLICY_NOT_APPLICABLE' THEN '6_SIZING' WHEN 'UNFILLED_NOTIONAL' THEN '6_SIZING' WHEN 'UNRESOLVED_SETTLEMENT_SEMANTICS' THEN '4_SETTLEMENT_SCOPE' WHEN 'VENUE_BOOK_NOT_READ' THEN '5_EXECUTION_ESTIMATE' WHEN 'VENUE_CONTRACT_IS_A_LINE_MARKET_NOT_A_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_IS_A_SEGMENT_NOT_FULL_GAME' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_KIND_IS_NOT_A_CONFIRMED_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_PERIOD_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_DOES_NOT_LIST_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_IS_NOT_A_TWO_PARTICIPANT_MATCH' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_TITLE_NOT_CAPTURED' THEN '3_IDENTITY' WHEN 'VENUE_MAPPING_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_CLOSED_OR_RESOLVED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_CONFLICTS_WITH_THE_IDENTIFIER' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_IS_A_SEGMENT' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_NOT_A_WINNER_STRUCTURE' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_UNSPECIFIED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_METADATA_NOT_RETAINED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CANDIDATE_READ_TRUNCATED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CATALOGUE_READ_FAILED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_COMPETITION_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_SIDES_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DISCOVERED_EVENT_NOT_IN_THE_WINDOW' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_MATCHES_ONLY_ONE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_HAS_NO_DRAW_OUTCOME' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_NOT_SUPPORTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_NOT_ADMITTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_TEAM_NOT_IN_THE_LEAGUE_TABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_MATCH_RAISED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_NICKNAME_DOES_NOT_CONFIRM_THE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PRICED_OUTCOME_NOT_A_DESIGNATION' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PROVIDER_EVENT_NOT_MATCHABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_TEAM_ASSIGNMENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_SLUG_DOES_NOT_DECOMPOSE_INTO_EVENT_AND_SIDE' THEN '3_IDENTITY' WHEN 'VOID_ABANDONMENT_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' END) AS stage_d, 
            CASE
              WHEN outcome IN ('ADMITTED', 'ALREADY_RECORDED') THEN 99
              WHEN outcome = 'REFUSED' AND coalesce(stage, CASE split_part(coalesce(first_refusal, ''), ':', 1) WHEN 'ACTION_EXPOSURE_EFFECT_NOT_IDENTIFIED' THEN '7_RISK' WHEN 'EXECUTION_ESTIMATE_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'LINE_EXCEPTIONAL_SETTLEMENT_TERMS_DIFFER' THEN '4_SETTLEMENT_SCOPE' WHEN 'NO_ACTION_HAS_POSITIVE_NET_EDGE' THEN '8_ECONOMICS' WHEN 'NO_OBSERVED_DEPTH_INSIDE_THE_BREAK_EVEN_LIMIT' THEN '5_EXECUTION_ESTIMATE' WHEN 'NO_PREMAP_CONTRACT_FOR_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'NO_RAIL_HEADROOM_FOR_ANY_POSITION' THEN '6_SIZING' WHEN 'NO_VENUE_CONTRACT_FOR_EVENT' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_CONTRACT_IN_PREMAP' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_EVENT_FOR_FIXTURE' THEN '3_IDENTITY' WHEN 'OPEN_SHADOW_BOOK_NOT_READ' THEN '7_RISK' WHEN 'OVERTIME_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'PAYOUT_OUTCOME_DISAGREES_WITH_THE_VENUE_INTENT' THEN '3_IDENTITY' WHEN 'PAYOUT_OUTCOME_INDEX_NOT_BOUND_TO_A_TOKEN' THEN '3_IDENTITY' WHEN 'PRICED_OUTCOME_NOT_IN_THE_PROVIDER_QUOTE' THEN '3_IDENTITY' WHEN 'P_FILL_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'RAIL_HEADROOM_NOT_MEASURED' THEN '6_SIZING' WHEN 'RISK_GATE_BLOCKED' THEN '7_RISK' WHEN 'SETTLEMENT_SCOPE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'SETTLEMENT_TERMS_CONFLICT' THEN '4_SETTLEMENT_SCOPE' WHEN 'SIZING_POLICY_NOT_APPLICABLE' THEN '6_SIZING' WHEN 'UNFILLED_NOTIONAL' THEN '6_SIZING' WHEN 'UNRESOLVED_SETTLEMENT_SEMANTICS' THEN '4_SETTLEMENT_SCOPE' WHEN 'VENUE_BOOK_NOT_READ' THEN '5_EXECUTION_ESTIMATE' WHEN 'VENUE_CONTRACT_IS_A_LINE_MARKET_NOT_A_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_IS_A_SEGMENT_NOT_FULL_GAME' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_KIND_IS_NOT_A_CONFIRMED_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_PERIOD_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_DOES_NOT_LIST_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_IS_NOT_A_TWO_PARTICIPANT_MATCH' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_TITLE_NOT_CAPTURED' THEN '3_IDENTITY' WHEN 'VENUE_MAPPING_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_CLOSED_OR_RESOLVED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_CONFLICTS_WITH_THE_IDENTIFIER' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_IS_A_SEGMENT' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_NOT_A_WINNER_STRUCTURE' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_UNSPECIFIED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_METADATA_NOT_RETAINED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CANDIDATE_READ_TRUNCATED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CATALOGUE_READ_FAILED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_COMPETITION_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_SIDES_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DISCOVERED_EVENT_NOT_IN_THE_WINDOW' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_MATCHES_ONLY_ONE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_HAS_NO_DRAW_OUTCOME' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_NOT_SUPPORTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_NOT_ADMITTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_TEAM_NOT_IN_THE_LEAGUE_TABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_MATCH_RAISED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_NICKNAME_DOES_NOT_CONFIRM_THE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PRICED_OUTCOME_NOT_A_DESIGNATION' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PROVIDER_EVENT_NOT_MATCHABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_TEAM_ASSIGNMENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_SLUG_DOES_NOT_DECOMPOSE_INTO_EVENT_AND_SIDE' THEN '3_IDENTITY' WHEN 'VOID_ABANDONMENT_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' END) ~ '^[1-8]_' THEN
                   greatest(substr(coalesce(stage, CASE split_part(coalesce(first_refusal, ''), ':', 1) WHEN 'ACTION_EXPOSURE_EFFECT_NOT_IDENTIFIED' THEN '7_RISK' WHEN 'EXECUTION_ESTIMATE_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'LINE_EXCEPTIONAL_SETTLEMENT_TERMS_DIFFER' THEN '4_SETTLEMENT_SCOPE' WHEN 'NO_ACTION_HAS_POSITIVE_NET_EDGE' THEN '8_ECONOMICS' WHEN 'NO_OBSERVED_DEPTH_INSIDE_THE_BREAK_EVEN_LIMIT' THEN '5_EXECUTION_ESTIMATE' WHEN 'NO_PREMAP_CONTRACT_FOR_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'NO_RAIL_HEADROOM_FOR_ANY_POSITION' THEN '6_SIZING' WHEN 'NO_VENUE_CONTRACT_FOR_EVENT' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_CONTRACT_IN_PREMAP' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_EVENT_FOR_FIXTURE' THEN '3_IDENTITY' WHEN 'OPEN_SHADOW_BOOK_NOT_READ' THEN '7_RISK' WHEN 'OVERTIME_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'PAYOUT_OUTCOME_DISAGREES_WITH_THE_VENUE_INTENT' THEN '3_IDENTITY' WHEN 'PAYOUT_OUTCOME_INDEX_NOT_BOUND_TO_A_TOKEN' THEN '3_IDENTITY' WHEN 'PRICED_OUTCOME_NOT_IN_THE_PROVIDER_QUOTE' THEN '3_IDENTITY' WHEN 'P_FILL_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'RAIL_HEADROOM_NOT_MEASURED' THEN '6_SIZING' WHEN 'RISK_GATE_BLOCKED' THEN '7_RISK' WHEN 'SETTLEMENT_SCOPE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'SETTLEMENT_TERMS_CONFLICT' THEN '4_SETTLEMENT_SCOPE' WHEN 'SIZING_POLICY_NOT_APPLICABLE' THEN '6_SIZING' WHEN 'UNFILLED_NOTIONAL' THEN '6_SIZING' WHEN 'UNRESOLVED_SETTLEMENT_SEMANTICS' THEN '4_SETTLEMENT_SCOPE' WHEN 'VENUE_BOOK_NOT_READ' THEN '5_EXECUTION_ESTIMATE' WHEN 'VENUE_CONTRACT_IS_A_LINE_MARKET_NOT_A_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_IS_A_SEGMENT_NOT_FULL_GAME' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_KIND_IS_NOT_A_CONFIRMED_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_PERIOD_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_DOES_NOT_LIST_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_IS_NOT_A_TWO_PARTICIPANT_MATCH' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_TITLE_NOT_CAPTURED' THEN '3_IDENTITY' WHEN 'VENUE_MAPPING_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_CLOSED_OR_RESOLVED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_CONFLICTS_WITH_THE_IDENTIFIER' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_IS_A_SEGMENT' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_NOT_A_WINNER_STRUCTURE' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_UNSPECIFIED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_METADATA_NOT_RETAINED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CANDIDATE_READ_TRUNCATED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CATALOGUE_READ_FAILED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_COMPETITION_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_SIDES_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DISCOVERED_EVENT_NOT_IN_THE_WINDOW' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_MATCHES_ONLY_ONE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_HAS_NO_DRAW_OUTCOME' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_NOT_SUPPORTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_NOT_ADMITTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_TEAM_NOT_IN_THE_LEAGUE_TABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_MATCH_RAISED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_NICKNAME_DOES_NOT_CONFIRM_THE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PRICED_OUTCOME_NOT_A_DESIGNATION' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PROVIDER_EVENT_NOT_MATCHABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_TEAM_ASSIGNMENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_SLUG_DOES_NOT_DECOMPOSE_INTO_EVENT_AND_SIDE' THEN '3_IDENTITY' WHEN 'VOID_ABANDONMENT_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' END), 1, 1)::int,
                            CASE WHEN us_market_slug IS NOT NULL THEN 4 ELSE 0 END)
              WHEN us_market_slug IS NOT NULL THEN 4
              ELSE 0
            END AS reach
                  FROM ext_candidate_outcomes
                 WHERE cycle_at >= to_timestamp(h.since) AND cycle_at < to_timestamp(h.until)
                   AND provider_event_id IS NOT NULL)
            SELECT sport_key, provider_event_id, max(family) AS family,
                   count(*) AS rows, max(reach) AS reach,
                   (array_agg(stage_d ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS stage,
                   (array_agg(outcome ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS outcome,
                   (array_agg(first_refusal ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS first_refusal,
                   (array_agg(codes ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS codes,
                   (array_agg(us_market_slug ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS us_market_slug,
                   array_remove(array_agg(DISTINCT us_market_slug), NULL) AS slugs,
                   max(home) AS home, max(away) AS away,
                   max(commence_time) AS commence_time,
                   extract(epoch FROM max(cycle_at))::float8 AS last_cycle_at
              FROM r GROUP BY sport_key, provider_event_id
             ORDER BY sport_key, provider_event_id
             LIMIT 20000
    ) e),
-- coverage_first_loss.VALUATIONS_SQL: $1 since, $2 until, $3 the hour's
-- provider event ids, $4 the hour's venue contracts, $5 the cap
vl AS (
    SELECT h.k, v.* FROM h CROSS JOIN LATERAL (
            SELECT id, event_key, us_market_slug, sport_family, record_purpose,
                   refusals, admissible
              FROM external_valuations
             WHERE decided_at >= to_timestamp(h.since) AND decided_at < to_timestamp(h.until)
               AND record_purpose IN ('ENTRY_DECISION', 'CALIBRATION_ONLY')
               AND (event_key = ANY((SELECT coalesce(array_agg(DISTINCT e.provider_event_id::text), ARRAY[]::text[]) FROM ev e WHERE e.k = h.k)::text[]) OR us_market_slug = ANY((SELECT coalesce(array_agg(DISTINCT s), ARRAY[]::text[]) FROM ev e, unnest(e.slugs) AS s WHERE e.k = h.k)::text[]))
             ORDER BY id
             LIMIT 50000
    ) v),
-- coverage_first_loss.DECISIONS_SQL: $1 the hour's valuation ids, $2 since,
-- $3 the cap
dc AS (
    SELECT h.k, d.* FROM h CROSS JOIN LATERAL (
            SELECT valuation_id, verdict, refusal, refusals, strategy
              FROM paper_decisions
             WHERE valuation_id = ANY((SELECT coalesce(array_agg(v.id::bigint), ARRAY[]::bigint[]) FROM vl v WHERE v.k = h.k)::bigint[])
               AND decided_at >= to_timestamp(h.since) - interval '1 day'
             ORDER BY decided_at
             LIMIT 50000
    ) d)
SELECT j FROM (
    SELECT k, -1 AS ord, '' AS o1, '' AS o2,
           json_build_object('kind', 'hour', 'k', k, 'now', now_k,
                             'since', since, 'until', until)::text AS j
      FROM h
    UNION ALL
    SELECT k, 0, sport_key, provider_event_id::text,
           json_build_object('kind', 'ev', 'k', k,
                             'row', to_jsonb(ev) - 'k')::text
      FROM ev
    UNION ALL
    SELECT k, 1, lpad(id::text, 12, '0'), '',
           json_build_object('kind', 'val', 'k', k,
                             'row', to_jsonb(vl) - 'k')::text
      FROM vl
    UNION ALL
    SELECT k, 2, lpad(valuation_id::text, 12, '0'), coalesce(strategy, ''),
           json_build_object('kind', 'dec', 'k', k,
                             'row', to_jsonb(dc) - 'k')::text
      FROM dc
) x ORDER BY k, ord, o1, o2, j;
