-- RC6.3b post-deploy proof: consecutive PAPER passes sampled every 30 s for 6 minutes -- the heartbeat
-- (ran, elapsed, errors, exceeded / skipped steps, written_at) and paper_session_health passes / heartbeat.
-- SELECT only.
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
SELECT pg_sleep(30);
SELECT to_char(clock_timestamp(), 'HH24:MI:SS') AS sampled, to_char(to_timestamp((h.value->>'written_at')::float), 'HH24:MI:SS') AS hb_written, h.value->>'ran' AS ran, h.value->>'trigger' AS trigger, h.value->>'refusal' AS refusal, h.value->>'elapsed_s' AS elapsed_s, h.value->>'exceeded_step' AS exceeded_step, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'skipped_steps', '{}'::jsonb)) k) AS skipped, (SELECT string_agg(k, ',') FROM jsonb_object_keys(coalesce(h.value->'errors', '{}'::jsonb)) k) AS error_keys, h.value->>'decisions_recorded' AS decisions, h.value->>'orders_submitted' AS orders, h.value->>'reviews' AS reviews, s.passes, to_char(s.heartbeat_at, 'HH24:MI:SS') AS health_at, s.errors AS health_errors FROM ingestion_state h CROSS JOIN LATERAL (SELECT passes, heartbeat_at, errors FROM paper_session_health ORDER BY heartbeat_at DESC LIMIT 1) s WHERE h.key = 'paper_session_last_pass';
\echo P2 the last pass in full: per-step elapsed seconds and errors
SELECT key, value FROM jsonb_each(coalesce((SELECT value->'step_elapsed_s' FROM ingestion_state WHERE key = 'paper_session_last_pass'), '{}'::jsonb)) ORDER BY (value::text)::float DESC NULLS LAST;
SELECT key, left(value::text, 300) AS error FROM jsonb_each(coalesce((SELECT value->'errors' FROM ingestion_state WHERE key = 'paper_session_last_pass'), '{}'::jsonb));
\echo P3 coverage watermark and newest snapshot
SELECT value, to_timestamp((value->>'at')::float) AS at FROM ingestion_state WHERE key = 'coverage_integrity_last';
SELECT max(computed_at) AS newest_snapshot FROM coverage_funnel_snapshots;
