-- READ-ONLY. RC6 lane C (software reds), part 2 of the census inputs: the
-- valuations and decisions linked to each window's events. The first-loss census's own inputs,
-- per window, so coverage_first_loss.census() can be re-run off production on
-- exactly what software_red_count reads (capital_readiness gate
-- software_reds_zero -> coverage_first_loss.read). The ledger statement is
-- coverage_first_loss.ledger_events_sql() verbatim with the window taken from
-- the windows list instead of $1/$2. Windows: every UTC hour of the RC5
-- runtime (2026-10-08 16:00Z on), the packet's gate hour (20:03:19Z), the
-- earlier lane's 90 min read, and the feed-up / feed-down periods of the API's
-- PinnAPI owner (EVICTION_LOOP_SUSPECTED at 19:00:51Z). SELECT only.

\echo W windows
WITH w AS (
    SELECT row_number() OVER (ORDER BY since, until) AS wid, label, since, until
      FROM (
        SELECT 'H ' || to_char(h, 'MM-DD HH24') AS label, h AS since,
               h + interval '1 hour' AS until
          FROM generate_series(timestamptz '2026-10-08 16:00:00+00',
                               date_trunc('hour', now()), interval '1 hour') h
        UNION ALL
        SELECT 'PACKET_GATE_1H_20:03:19Z', to_timestamp(1791489799.1995766 - 3600),
               to_timestamp(1791489799.1995766 + 1)
        UNION ALL
        SELECT 'PRIOR_LANE_90MIN_21:19Z', timestamptz '2026-10-08 19:49:00+00',
               timestamptz '2026-10-08 21:19:00+00'
        UNION ALL
        SELECT 'FEED_UP_16:30-19:00:51Z', timestamptz '2026-10-08 16:30:10+00',
               timestamptz '2026-10-08 19:00:51+00'
        UNION ALL
        SELECT 'FEED_DOWN_19:00:51Z-NOW', timestamptz '2026-10-08 19:00:51+00', now()
      ) x)
SELECT wid, label, since, until FROM w ORDER BY wid;

\echo V valuations linked to the events of each window (VALUATIONS_SQL) with their decisions (DECISIONS_SQL), distinct shapes, 40 per line
WITH w AS (
    SELECT row_number() OVER (ORDER BY since, until) AS wid, label, since, until
      FROM (
        SELECT 'H ' || to_char(h, 'MM-DD HH24') AS label, h AS since,
               h + interval '1 hour' AS until
          FROM generate_series(timestamptz '2026-10-08 16:00:00+00',
                               date_trunc('hour', now()), interval '1 hour') h
        UNION ALL
        SELECT 'PACKET_GATE_1H_20:03:19Z', to_timestamp(1791489799.1995766 - 3600),
               to_timestamp(1791489799.1995766 + 1)
        UNION ALL
        SELECT 'PRIOR_LANE_90MIN_21:19Z', timestamptz '2026-10-08 19:49:00+00',
               timestamptz '2026-10-08 21:19:00+00'
        UNION ALL
        SELECT 'FEED_UP_16:30-19:00:51Z', timestamptz '2026-10-08 16:30:10+00',
               timestamptz '2026-10-08 19:00:51+00'
        UNION ALL
        SELECT 'FEED_DOWN_19:00:51Z-NOW', timestamptz '2026-10-08 19:00:51+00', now()
      ) x),
r AS (
        SELECT w.wid, id, sport_key, family, provider_event_id, cycle_at, outcome,
               first_refusal, codes, us_market_slug, home, away,
               commence_time, coalesce(stage, CASE split_part(coalesce(first_refusal, ''), ':', 1) WHEN 'ACTION_EXPOSURE_EFFECT_NOT_IDENTIFIED' THEN '7_RISK' WHEN 'EXECUTION_ESTIMATE_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'LINE_EXCEPTIONAL_SETTLEMENT_TERMS_DIFFER' THEN '4_SETTLEMENT_SCOPE' WHEN 'NO_ACTION_HAS_POSITIVE_NET_EDGE' THEN '8_ECONOMICS' WHEN 'NO_OBSERVED_DEPTH_INSIDE_THE_BREAK_EVEN_LIMIT' THEN '5_EXECUTION_ESTIMATE' WHEN 'NO_PREMAP_CONTRACT_FOR_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'NO_RAIL_HEADROOM_FOR_ANY_POSITION' THEN '6_SIZING' WHEN 'NO_VENUE_CONTRACT_FOR_EVENT' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_CONTRACT_IN_PREMAP' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_EVENT_FOR_FIXTURE' THEN '3_IDENTITY' WHEN 'OPEN_SHADOW_BOOK_NOT_READ' THEN '7_RISK' WHEN 'OVERTIME_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'PAYOUT_OUTCOME_DISAGREES_WITH_THE_VENUE_INTENT' THEN '3_IDENTITY' WHEN 'PAYOUT_OUTCOME_INDEX_NOT_BOUND_TO_A_TOKEN' THEN '3_IDENTITY' WHEN 'PRICED_OUTCOME_NOT_IN_THE_PROVIDER_QUOTE' THEN '3_IDENTITY' WHEN 'P_FILL_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'RAIL_HEADROOM_NOT_MEASURED' THEN '6_SIZING' WHEN 'RISK_GATE_BLOCKED' THEN '7_RISK' WHEN 'SETTLEMENT_SCOPE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'SETTLEMENT_TERMS_CONFLICT' THEN '4_SETTLEMENT_SCOPE' WHEN 'SIZING_POLICY_NOT_APPLICABLE' THEN '6_SIZING' WHEN 'UNFILLED_NOTIONAL' THEN '6_SIZING' WHEN 'UNRESOLVED_SETTLEMENT_SEMANTICS' THEN '4_SETTLEMENT_SCOPE' WHEN 'VENUE_BOOK_NOT_READ' THEN '5_EXECUTION_ESTIMATE' WHEN 'VENUE_CONTRACT_IS_A_LINE_MARKET_NOT_A_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_IS_A_SEGMENT_NOT_FULL_GAME' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_KIND_IS_NOT_A_CONFIRMED_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_PERIOD_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_DOES_NOT_LIST_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_IS_NOT_A_TWO_PARTICIPANT_MATCH' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_TITLE_NOT_CAPTURED' THEN '3_IDENTITY' WHEN 'VENUE_MAPPING_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_CLOSED_OR_RESOLVED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_CONFLICTS_WITH_THE_IDENTIFIER' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_IS_A_SEGMENT' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_NOT_A_WINNER_STRUCTURE' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_UNSPECIFIED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_METADATA_NOT_RETAINED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CANDIDATE_READ_TRUNCATED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CATALOGUE_READ_FAILED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_COMPETITION_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_SIDES_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DISCOVERED_EVENT_NOT_IN_THE_WINDOW' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_MATCHES_ONLY_ONE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_HAS_NO_DRAW_OUTCOME' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_NOT_SUPPORTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_NOT_ADMITTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_TEAM_NOT_IN_THE_LEAGUE_TABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_MATCH_RAISED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_NICKNAME_DOES_NOT_CONFIRM_THE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PRICED_OUTCOME_NOT_A_DESIGNATION' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PROVIDER_EVENT_NOT_MATCHABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_TEAM_ASSIGNMENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_SLUG_DOES_NOT_DECOMPOSE_INTO_EVENT_AND_SIDE' THEN '3_IDENTITY' WHEN 'VOID_ABANDONMENT_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' END) AS stage_d, 
    CASE
      WHEN outcome IN ('ADMITTED', 'ALREADY_RECORDED') THEN 99
      WHEN outcome = 'REFUSED' AND coalesce(stage, CASE split_part(coalesce(first_refusal, ''), ':', 1) WHEN 'ACTION_EXPOSURE_EFFECT_NOT_IDENTIFIED' THEN '7_RISK' WHEN 'EXECUTION_ESTIMATE_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'LINE_EXCEPTIONAL_SETTLEMENT_TERMS_DIFFER' THEN '4_SETTLEMENT_SCOPE' WHEN 'NO_ACTION_HAS_POSITIVE_NET_EDGE' THEN '8_ECONOMICS' WHEN 'NO_OBSERVED_DEPTH_INSIDE_THE_BREAK_EVEN_LIMIT' THEN '5_EXECUTION_ESTIMATE' WHEN 'NO_PREMAP_CONTRACT_FOR_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'NO_RAIL_HEADROOM_FOR_ANY_POSITION' THEN '6_SIZING' WHEN 'NO_VENUE_CONTRACT_FOR_EVENT' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_CONTRACT_IN_PREMAP' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_EVENT_FOR_FIXTURE' THEN '3_IDENTITY' WHEN 'OPEN_SHADOW_BOOK_NOT_READ' THEN '7_RISK' WHEN 'OVERTIME_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'PAYOUT_OUTCOME_DISAGREES_WITH_THE_VENUE_INTENT' THEN '3_IDENTITY' WHEN 'PAYOUT_OUTCOME_INDEX_NOT_BOUND_TO_A_TOKEN' THEN '3_IDENTITY' WHEN 'PRICED_OUTCOME_NOT_IN_THE_PROVIDER_QUOTE' THEN '3_IDENTITY' WHEN 'P_FILL_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'RAIL_HEADROOM_NOT_MEASURED' THEN '6_SIZING' WHEN 'RISK_GATE_BLOCKED' THEN '7_RISK' WHEN 'SETTLEMENT_SCOPE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'SETTLEMENT_TERMS_CONFLICT' THEN '4_SETTLEMENT_SCOPE' WHEN 'SIZING_POLICY_NOT_APPLICABLE' THEN '6_SIZING' WHEN 'UNFILLED_NOTIONAL' THEN '6_SIZING' WHEN 'UNRESOLVED_SETTLEMENT_SEMANTICS' THEN '4_SETTLEMENT_SCOPE' WHEN 'VENUE_BOOK_NOT_READ' THEN '5_EXECUTION_ESTIMATE' WHEN 'VENUE_CONTRACT_IS_A_LINE_MARKET_NOT_A_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_IS_A_SEGMENT_NOT_FULL_GAME' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_KIND_IS_NOT_A_CONFIRMED_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_PERIOD_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_DOES_NOT_LIST_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_IS_NOT_A_TWO_PARTICIPANT_MATCH' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_TITLE_NOT_CAPTURED' THEN '3_IDENTITY' WHEN 'VENUE_MAPPING_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_CLOSED_OR_RESOLVED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_CONFLICTS_WITH_THE_IDENTIFIER' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_IS_A_SEGMENT' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_NOT_A_WINNER_STRUCTURE' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_UNSPECIFIED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_METADATA_NOT_RETAINED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CANDIDATE_READ_TRUNCATED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CATALOGUE_READ_FAILED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_COMPETITION_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_SIDES_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DISCOVERED_EVENT_NOT_IN_THE_WINDOW' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_MATCHES_ONLY_ONE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_HAS_NO_DRAW_OUTCOME' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_NOT_SUPPORTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_NOT_ADMITTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_TEAM_NOT_IN_THE_LEAGUE_TABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_MATCH_RAISED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_NICKNAME_DOES_NOT_CONFIRM_THE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PRICED_OUTCOME_NOT_A_DESIGNATION' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PROVIDER_EVENT_NOT_MATCHABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_TEAM_ASSIGNMENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_SLUG_DOES_NOT_DECOMPOSE_INTO_EVENT_AND_SIDE' THEN '3_IDENTITY' WHEN 'VOID_ABANDONMENT_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' END) ~ '^[1-8]_' THEN
           greatest(substr(coalesce(stage, CASE split_part(coalesce(first_refusal, ''), ':', 1) WHEN 'ACTION_EXPOSURE_EFFECT_NOT_IDENTIFIED' THEN '7_RISK' WHEN 'EXECUTION_ESTIMATE_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'LINE_EXCEPTIONAL_SETTLEMENT_TERMS_DIFFER' THEN '4_SETTLEMENT_SCOPE' WHEN 'NO_ACTION_HAS_POSITIVE_NET_EDGE' THEN '8_ECONOMICS' WHEN 'NO_OBSERVED_DEPTH_INSIDE_THE_BREAK_EVEN_LIMIT' THEN '5_EXECUTION_ESTIMATE' WHEN 'NO_PREMAP_CONTRACT_FOR_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'NO_RAIL_HEADROOM_FOR_ANY_POSITION' THEN '6_SIZING' WHEN 'NO_VENUE_CONTRACT_FOR_EVENT' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_CONTRACT_IN_PREMAP' THEN '3_IDENTITY' WHEN 'NO_VENUE_NATIVE_EVENT_FOR_FIXTURE' THEN '3_IDENTITY' WHEN 'OPEN_SHADOW_BOOK_NOT_READ' THEN '7_RISK' WHEN 'OVERTIME_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'PAYOUT_OUTCOME_DISAGREES_WITH_THE_VENUE_INTENT' THEN '3_IDENTITY' WHEN 'PAYOUT_OUTCOME_INDEX_NOT_BOUND_TO_A_TOKEN' THEN '3_IDENTITY' WHEN 'PRICED_OUTCOME_NOT_IN_THE_PROVIDER_QUOTE' THEN '3_IDENTITY' WHEN 'P_FILL_NOT_IDENTIFIED' THEN '5_EXECUTION_ESTIMATE' WHEN 'RAIL_HEADROOM_NOT_MEASURED' THEN '6_SIZING' WHEN 'RISK_GATE_BLOCKED' THEN '7_RISK' WHEN 'SETTLEMENT_SCOPE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' WHEN 'SETTLEMENT_TERMS_CONFLICT' THEN '4_SETTLEMENT_SCOPE' WHEN 'SIZING_POLICY_NOT_APPLICABLE' THEN '6_SIZING' WHEN 'UNFILLED_NOTIONAL' THEN '6_SIZING' WHEN 'UNRESOLVED_SETTLEMENT_SEMANTICS' THEN '4_SETTLEMENT_SCOPE' WHEN 'VENUE_BOOK_NOT_READ' THEN '5_EXECUTION_ESTIMATE' WHEN 'VENUE_CONTRACT_IS_A_LINE_MARKET_NOT_A_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_IS_A_SEGMENT_NOT_FULL_GAME' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_KIND_IS_NOT_A_CONFIRMED_MONEYLINE' THEN '3_IDENTITY' WHEN 'VENUE_CONTRACT_PERIOD_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_DOES_NOT_LIST_THIS_FIXTURE' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_IS_NOT_A_TWO_PARTICIPANT_MATCH' THEN '3_IDENTITY' WHEN 'VENUE_EVENT_TITLE_NOT_CAPTURED' THEN '3_IDENTITY' WHEN 'VENUE_MAPPING_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_CLOSED_OR_RESOLVED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_CONFLICTS_WITH_THE_IDENTIFIER' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_IS_A_SEGMENT' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_SCOPE_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_NOT_A_WINNER_STRUCTURE' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_IS_UNSPECIFIED' THEN '3_IDENTITY' WHEN 'VENUE_MARKET_TYPE_METADATA_NOT_RETAINED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CANDIDATE_READ_TRUNCATED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CATALOGUE_READ_FAILED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_COMPETITION_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_FOR_THE_PRICED_TEAM_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_CONTRACT_SIDES_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DISCOVERED_EVENT_NOT_IN_THE_WINDOW' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_ESTABLISHED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_DRAW_CONTRACT_NOT_FOUND' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_EVENT_MATCHES_ONLY_ONE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_HAS_NO_DRAW_OUTCOME' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_FAMILY_NOT_SUPPORTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_NOT_ADMITTED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_LEAGUE_TEAM_NOT_IN_THE_LEAGUE_TABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_MATCH_RAISED' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_NICKNAME_DOES_NOT_CONFIRM_THE_TEAM' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PRICED_OUTCOME_NOT_A_DESIGNATION' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_PROVIDER_EVENT_NOT_MATCHABLE' THEN '3_IDENTITY' WHEN 'VENUE_NATIVE_TEAM_ASSIGNMENT_AMBIGUOUS' THEN '3_IDENTITY' WHEN 'VENUE_SLUG_DOES_NOT_DECOMPOSE_INTO_EVENT_AND_SIDE' THEN '3_IDENTITY' WHEN 'VOID_ABANDONMENT_RULE_NOT_ESTABLISHED' THEN '4_SETTLEMENT_SCOPE' END), 1, 1)::int,
                    CASE WHEN us_market_slug IS NOT NULL THEN 4 ELSE 0 END)
      WHEN us_market_slug IS NOT NULL THEN 4
      ELSE 0
    END AS reach
          FROM ext_candidate_outcomes JOIN w ON cycle_at >= w.since AND cycle_at < w.until
         WHERE true
           AND provider_event_id IS NOT NULL)
    ,
ev AS (SELECT wid, sport_key, provider_event_id, max(family) AS family,
           count(*) AS rows, max(reach) AS reach,
           (array_agg(stage_d ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS stage,
           (array_agg(outcome ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS outcome,
           (array_agg(first_refusal ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS first_refusal,
           (array_agg(codes ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS codes,
           (array_agg(us_market_slug ORDER BY reach DESC, cycle_at DESC, id DESC))[1] AS us_market_slug,
           array_remove(array_agg(DISTINCT us_market_slug), NULL) AS slugs,
           max(home) AS home, max(away) AS away,
           max(commence_time) AS commence_time,
           extract(epoch FROM max(cycle_at))::float8 AS last_cycle_at
      FROM r GROUP BY wid, sport_key, provider_event_id
     ),
ids AS (SELECT DISTINCT wid, provider_event_id AS k FROM ev),
sl AS (SELECT DISTINCT wid, unnest(slugs) AS s FROM ev),
v AS (
    SELECT w.wid, x.id, x.event_key, x.us_market_slug, x.refusals
      FROM w JOIN external_valuations x
        ON x.decided_at >= w.since AND x.decided_at < w.until
     WHERE x.record_purpose IN ('ENTRY_DECISION', 'CALIBRATION_ONLY')
       AND (EXISTS (SELECT 1 FROM ids WHERE ids.wid = w.wid AND ids.k = x.event_key)
            OR EXISTS (SELECT 1 FROM sl WHERE sl.wid = w.wid AND sl.s = x.us_market_slug))),
vd AS (
    SELECT v.wid, v.event_key, v.us_market_slug, v.refusals,
           (SELECT jsonb_agg(jsonb_build_array(d.verdict, d.refusal, d.refusals, d.strategy)
                             ORDER BY d.verdict, d.strategy, d.refusals)
              FROM paper_decisions d JOIN w w2 ON w2.wid = v.wid
             WHERE d.valuation_id = v.id
               AND d.decided_at >= w2.since - interval '1 day') AS decs
      FROM v),
g AS (SELECT wid, event_key, us_market_slug, refusals, decs, count(*) AS n
        FROM vd GROUP BY 1, 2, 3, 4, 5),
n AS (SELECT g.*, (row_number() OVER (PARTITION BY wid ORDER BY event_key, us_market_slug, n) - 1) / 40 AS chunk
        FROM g)
SELECT 'V' AS k, wid, chunk,
       jsonb_agg(jsonb_build_array(event_key, us_market_slug, refusals, decs, n))::text AS j
  FROM n GROUP BY wid, chunk ORDER BY wid, chunk;

