// Local synthetic acceptance; never authenticates to or writes production.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert'),http=require('http');
const now=Date.now()/1000,out=__dirname,root=path.resolve(__dirname,'../..');
const work=['DEREK','XAVIER','AUDREY'].map((a,i)=>({task_id:'capwork:sample-'+a,assignee:a,title:'Explain missed evaluations and define a measurable improvement',status:i===0?'CLOSED_NO_CHANGE':'WAITING',spec:{priority:4,due_at:now+86400,dependencies:i?['capwork:sample-DEREK']:[],next_action:'Review the evidence and specify the next measurement.'},outcome:i===0?{reviewed:true,message_id:'sample-message-1',answer:'The recorded timeout findings support a scheduling investigation. A reduction in missing reviews has not yet been measured.',source_ids:['sample-finding-1']}: {},overdue:false}));
const payload={status:'OK',read_at:now,work,work_limit:60,account_id:'paper_acct_main',data_label:'LOCAL SYNTHETIC TEST RECORDS',control:{enabled:true,hourly_limit:24},tool_names:['account','decision','rules','recommendation'],experiments:[],experiment_catalog:{classes:{DEREK_ENTRY_EDGE_THRESHOLD:{min_evaluation_outcomes:10},XAVIER_EXIT_WHEN_MEASURE_STALE:{min_evaluation_outcomes:5}},parameter_bounds:{min_gross_edge_pp:[.5,6]},parameter_grid_pp:.5,parameter_policy:'PINNACLE_COMPLETED_GAME_PAPER'},scorecards:{window:{start:now-86400,end:now},derek:{decisions:120,entries:{numerator:3,denominator:120,rate:.025},sample_limited:false},xavier:{reviews:24,stale_measures:{numerator:2,denominator:22},missing_measures:2,sample_limited:false},audrey:{findings:6,critical_findings:0,genuine_reviews_in_visible_work:1,sample_limited:false},forecast_quality:{why:'Forecast calibration requires a frozen cohort.'},improvement_claim:'No improvement has been established by these sample records.'}};
const checks=[];let errors=[],goal,protocol,chat,toolURL,fail=false;
function pass(name){checks.push(name);}
function localTime(t){const d=new Date(t);return new Date(t-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
(async()=>{
 const server=http.createServer((req,res)=>{let file;if(['/derek','/xavier','/audrey'].includes(req.url))file=path.join(out,req.url.slice(1)+'.html');else if(req.url.startsWith('/api/command/agents/static/'))file=path.join(root,'backend/sportsassets/assets/agents',req.url.split('/static/')[1]);if(!file||!fs.existsSync(file)){res.writeHead(404).end('{}');return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.glb')?'model/gltf-binary':file.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(file));});
 await new Promise(r=>server.listen(8785,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:'/tmp/office138/chromium',args:['--no-sandbox','--disable-dev-shm-usage','--in-process-gpu','--single-process','--no-zygote'],env:{...process.env,LD_LIBRARY_PATH:'/tmp/office138'}});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**',async route=>{let u=new URL(route.request().url());if(u.pathname.includes('/static/'))return route.continue();let data={};let code=u.pathname.includes('/capabilities')||u.pathname.endsWith('/persona/chat')||u.pathname.endsWith('/history')?200:503;
  if(u.pathname.endsWith('/capabilities')){data=payload;code=fail?503:200;}
  else if(u.pathname.endsWith('/capabilities/goals')){goal=route.request().postDataJSON();data={created:true,task_ids:['a','b','c']};}
  else if(u.pathname.endsWith('/capabilities/experiments')){protocol=route.request().postDataJSON();data={ok:true,proposal_id:'sample-proposal'};}
  else if(u.pathname.includes('/capabilities/tools/')){toolURL=u;data={status:'OK',account_id:'paper_acct_main',data:{source:'SYNTHETIC_EVIDENCE',record_id:u.searchParams.get('record_id')}};}
  else if(u.pathname.endsWith('/persona/chat')){chat=route.request().postDataJSON();data={status:'ANSWERED',message_id:'sample-answer',answer:'This is a synthetic browser acceptance response.',conversation_id:'pc-derek-sample',provider:{mode:'LLM'},facts:[]};}
  else if(u.pathname.endsWith('/history'))data={messages:[]};
  await route.fulfill({status:code,contentType:'application/json',body:JSON.stringify(data)});
 });
 for(const agent of ['derek','xavier','audrey']){
  await page.goto('http://127.0.0.1:8785/'+agent);await page.waitForSelector('.cap-card[data-cap-task]');
  assert.equal(await page.locator('.cap-tabs button').count(),5);
  assert.equal(await page.locator('[data-cap-task]').count(),1);pass(agent+' scoped plans and five views');
  await page.getByRole('tab',{name:'Collaboration',exact:true}).click();assert.equal(await page.locator('[data-cap-task]').count(),3);pass(agent+' linked collaboration');
  await page.getByRole('tab',{name:'Investigate',exact:true}).click();await page.locator('#cap-tool select').selectOption('rules');await page.locator('#cap-tool input').fill('sample-decision');await page.getByRole('button',{name:'Read evidence',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#cap-tool-result').textContent.includes('SYNTHETIC_EVIDENCE'));assert.equal(toolURL.searchParams.get('agent'),agent.toUpperCase());assert.equal(toolURL.searchParams.get('record_id'),'sample-decision');pass(agent+' typed evidence request');
  await page.getByRole('tab',{name:'Scorecard',exact:true}).click();assert((await page.locator('.cap-body').innerText()).includes('No improvement has been established'));pass(agent+' sample metrics and honest outcome disclosure');
  await page.setViewportSize({width:390,height:844});await page.locator('#agent-capabilities').scrollIntoViewIfNeeded();assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));pass(agent+' phone layout no horizontal overflow');await page.setViewportSize({width:1440,height:1050});
 }
 await page.goto('http://127.0.0.1:8785/derek');await page.waitForSelector('[data-cap-task]');
 await page.locator('#cap-goal').evaluate(e=>e.parentElement.open=true);await page.locator('#cap-goal [name=actor]').fill('Test manager');await page.locator('#cap-goal [name=title]').fill('Investigate stale quotes and quantify missing evaluations');await page.locator('#cap-goal [name=due]').fill(localTime(Date.now()+86400000));await page.getByRole('button',{name:'Create team work plan'}).click();await page.waitForFunction(()=>document.querySelector('#cap-submit').textContent.includes('Plan saved'));assert.equal(goal.title,'Investigate stale quotes and quantify missing evaluations');assert.equal(goal.first,'DEREK');assert.equal(goal.priority,3);pass('Goal form sends typed fields and one stable request ID');
 await page.evaluate(()=>CCCapabilities.refresh());assert.equal(await page.locator('#cap-goal [name=title]').inputValue(),goal.title);pass('Periodic read retains edited form');
 await page.locator('[data-cap-task] summary').click();await page.getByRole('button',{name:'Discuss this work ↗'}).click();await page.locator('#talk-form').evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>document.querySelector('.talk-msg.a[data-mid]'));assert.equal(chat.context.capability_task_id,'capwork:sample-DEREK');pass('Task discussion carries exact scoped task ID into real chat path');
 await page.getByRole('tab',{name:'Experiments',exact:true}).click();await page.locator('#cap-experiment').evaluate(e=>e.parentElement.open=true);const f=page.locator('#cap-experiment');await f.locator('[name=actor]').fill('Test manager');await f.locator('[name=rationale]').fill('A stricter threshold may improve mean net result in the future cohort.');for(const [n,t] of Object.entries({training_start:Date.now()-8*86400000,training_end:Date.now()-86400000,evaluation_start:Date.now()+86400000,evaluation_end:Date.now()+8*86400000}))await f.locator('[name='+n+']').fill(localTime(t));await page.getByRole('button',{name:'Register protocol'}).click();await page.waitForFunction(()=>document.querySelector('#cap-experiment-state').textContent.includes('Registered'));assert.equal(protocol.min_outcomes,10);assert.deepEqual(protocol.change,{parameter:'min_gross_edge_pp',from:.5,to:1});assert(protocol.training[1]<protocol.evaluation[0]);pass('Prospective experiment form registers hypothesis and fixed cohort');
 await page.getByRole('tab',{name:'Plans',exact:true}).click();fail=true;await page.evaluate(()=>CCCapabilities.refresh());assert.equal(await page.locator('[data-cap-task]').count(),1);assert((await page.locator('.cap-state').innerText()).includes('retaining records'));pass('503 preserves last known plans and labels stale read');fail=false;
 await page.evaluate(()=>{document.querySelector('.cap-eyebrow').textContent='LOCAL DESIGN PREVIEW · SYNTHETIC RECORDS';document.querySelector('.cap-state').textContent='Synthetic acceptance fixture — not production';});await page.locator('[data-cap-task] summary').click();await page.locator('#agent-capabilities').screenshot({path:path.join(out,'workbench-desktop.png')});await page.setViewportSize({width:390,height:844});await page.locator('#agent-capabilities').screenshot({path:path.join(out,'workbench-mobile.png')});
 assert.deepEqual(errors,[]);pass('No JavaScript errors');fs.writeFileSync(path.join(out,'browser-receipt.json'),JSON.stringify({pass:true,checks,records:'LOCAL SYNTHETIC FIXTURES',browsers:['Chromium desktop and phone viewport'],not_verified:['Real Postgres concurrency','Production provider and Slack delivery','iPhone Safari']},null,2));console.log(JSON.stringify({pass:true,checks:checks.length}));await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
