const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert');
const out=process.env.OFFICE_PROOF_DIR||__dirname, assets=path.resolve(process.env.REPO_ROOT||process.cwd(),'backend/sportsassets/assets/agents');
const ok=data=>({status:'OK',data});const stamp=Date.now()/1000;
const x={owned_positions:ok(['Yankees Moneyline','Padres Moneyline','Phillies Moneyline'].map((n,i)=>({group_id:'paper-test-'+i,strategy:'PINNACLE_EXPLORATION_PAPER',us_market_slug:['aec-mlb-nyy-bos-2026-10-03','aec-mlb-sd-mil-2026-10-03','aec-mlb-phi-atl-2026-10-03'][i],market:{selection:n,title:['Yankees vs Red Sox','Padres vs Brewers','Phillies vs Braves'][i]},remaining:{open_qty:100,cost_basis_usd:53.73,marked_value_usd:i===2?null:56,unrealized_pnl_usd:i===2?null:2.27,open_management_orders:i===0?1:0,ordinary_completion:{win_usd:46.27,lose_usd:-53.73}},recommendation:{recommendation:'HOLD',trigger:'SCHEDULED_REVIEW',reviewed_at:stamp-(i===1?300:12),selection:{selection_reason:'Hold has the highest recorded expected value after fees.'},action:{taken:i===0?'KEEP_STANDING':'NONE'},review_id:'review-'+i}}))),standing_orders:ok([{group_id:'paper-test-0',open:true,role:'STANDING_PROTECTION',direction:'SELL',qty:100,filled_qty:20,limit_price:.59,state:'PARTIALLY_FILLED'}]),exposure:ok({cost_basis_at_risk_usd:161.19,realized_pnl_usd:0})};
const d={strategies:[{recent:ok([{us_market_slug:'aec-mlb-nyy-bos-2026-10-03',market:{selection:'Yankees Moneyline',title:'Yankees vs Red Sox'},strategy:'PINNACLE_COMPLETED_GAME_PAPER',decision_id:'decision-demo',verdict:'REFUSE',refusal_words:'Fees consume the edge',purchase_price:.52,p_pinnacle:.53,edge_pp:1,fees_usd:1.73,net_ev_usd:-.73,decided_at:stamp,explanation:'Expected payout does not cover cost plus fees.'}])}],standing_entry_orders:ok([])};
d.strategies[0].version='PINNACLE_COMPLETED_GAME_PAPER_V2';d.strategies[0].title='Completed-game policy';d.strategies[0].recent.data[0].policy_version='PINNACLE_COMPLETED_GAME_PAPER_V2';d.strategies[0].recent.data.push({...d.strategies[0].recent.data[0],decision_id:'old-policy-decision',policy_version:'PINNACLE_COMPLETED_GAME_PAPER_V1',edge_pp:4,refusal_words:'Below minimum gross edge',decided_at:stamp-3600});
const a={account:ok({realized_pnl_usd:0,unrealized_pnl_usd:4.54,ledger_consistent:true}),operational_audit:ok([{recommendation_id:'rec-demo',owner_agent:'DEREK',kind:'BOOK_READ_CUTS',status:'MEASURING',recommendation:'Use bounded book reads and measure missed evaluations.',created_at:stamp}])};
for(const j of [x,d,a])j.freshness={agent_heartbeat:ok({heartbeat_at:stamp-10,stale_after_s:300})};
(async()=>{const server=require('http').createServer((req,res)=>{let p;if(req.url.startsWith('/api/command/agents/static/'))p=path.join(assets,req.url.split('/static/')[1]);else if(['/xavier','/derek','/audrey'].includes(req.url))p=path.join(out,req.url.slice(1)+'.html');else {res.setHeader('Content-Type','application/json');res.statusCode=404;res.end('{}');return;}try{res.setHeader('Content-Type',p.endsWith('.svg')?'image/svg+xml':p.endsWith('.js')?'text/javascript':p.endsWith('.glb')?'model/gltf-binary':p.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(p));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(8783,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/tmp/office138/chromium',args:['--no-sandbox','--disable-dev-shm-usage','--in-process-gpu','--single-process','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:{...process.env,LD_LIBRARY_PATH:'/tmp/office138',VK_ICD_FILENAMES:'/tmp/office138/vk_swiftshader_icd.json'}});const page=await browser.newPage({viewport:{width:1536,height:1100}});let errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});

const checks=[];const count=async()=>page.locator('.work-item[data-work-key]:not([hidden])').count();
async function seed(k,json){await page.goto('http://127.0.0.1:8783/'+k);await page.waitForFunction(()=>window.CCDesk);await page.evaluate(({json,at})=>CCOffice.render({json,okAt:at}),{json,at:stamp});}
await seed('xavier',x);
await page.locator('[data-desk-filter=attention]').click();assert.equal(await count(),1);assert((await page.locator('.work-item:not([hidden])').innerText()).includes('Padres'));checks.push('stale review filter');
await page.locator('[data-desk-filter=orders]').click();assert.equal(await count(),1);assert((await page.locator('.work-item:not([hidden])').innerText()).includes('Sell 80'));checks.push('partial working order filter');
await page.locator('[data-desk-filter=all]').click();await page.locator('#desk-search').fill('Phillies');assert.equal(await count(),1);await page.locator('#desk-search').fill('unknown club');assert(await page.locator('.desk-no-match').isVisible());await page.locator('#desk-search').fill('');checks.push('search and empty match');
await page.locator('[data-office-position=paper-test-1] > summary').click();assert((await page.locator('.desk-brief').innerText()).includes('Padres Moneyline'));assert((await page.locator('.desk-brief').innerText()).includes('older than 2 minutes'));checks.push('selected recorded rationale and age');
await page.locator('[data-desk-ask]').click();assert((await page.locator('#talk-in').inputValue()).includes('paper-test-1'));assert.equal(await page.locator('.talk-msg.q').count(),0);checks.push('record question drafted, never auto-sent');
await page.evaluate(()=>CCOffice.render({fail:{state:'UNAVAILABLE',why:'network down'},json:null}));assert((await page.locator('.desk-brief').innerText()).includes('Connection interrupted'));assert.equal(await count(),3);checks.push('failed read retains records and labels briefing');
await page.setViewportSize({width:390,height:844});await page.locator('.desk-mobile-talk').click();assert.equal(await page.locator('.office-side').getAttribute('role'),'dialog');assert(await page.locator('.office-board').evaluate(e=>!!e.closest('[inert]')));await page.locator('[data-desk-prompt="Brief me"]').click();assert(await page.locator('.office-side').isVisible());assert((await page.locator('#talk-in').inputValue()).includes('paper-test-1'));await page.keyboard.press('Escape');assert(!await page.locator('.office-board').evaluate(e=>!!e.closest('[inert]')));assert(!await page.locator('.office-side').isVisible());assert(await page.locator('.desk-mobile-talk').evaluate(e=>document.activeElement===e));checks.push('mobile modal repeat-open, inert cleanup, Escape and focus restore');
await page.locator('.desk-mobile-talk').click();await page.locator('.desk-conversation-close').focus();await page.keyboard.press('Shift+Tab');assert(await page.locator('.office-side').evaluate(e=>e.contains(document.activeElement)));await page.locator('.desk-conversation-close').click();checks.push('mobile modal keyboard trap');
await page.evaluate(()=>{document.querySelector('.office-kicker').textContent='DESIGN PREVIEW · SAMPLE RECORDS';scrollTo(0,document.querySelector('.office-heading').getBoundingClientRect().top+scrollY-110)});await page.screenshot({path:path.join(out,'xavier-mobile-workboard-v4.png')});await page.locator('.desk-mobile-talk').click();await page.waitForFunction(()=>document.querySelector('#cc-stage').classList.contains('cc-real-model'));assert((await page.locator('#cc-stage').boundingBox()).height<=180);await page.locator('#talk-in').scrollIntoViewIfNeeded();assert((await page.locator('#talk-in').boundingBox()).y<844);await page.screenshot({path:path.join(out,'xavier-mobile-conversation-v4.png')});await page.locator('.desk-conversation-close').click();
await page.setViewportSize({width:1536,height:1100});await seed('derek',d);await page.locator('[data-desk-filter=current]').click();assert.equal(await count(),1);await page.locator('[data-desk-filter=approved]').click();assert.equal(await count(),0);checks.push('current-policy and approval filters');await page.locator('[data-desk-filter=all]').click();await page.locator('#desk-search').fill('old-policy-decision');const download=page.waitForEvent('download');await page.locator('#desk-export').click();const file=await (await download).path(),csv=fs.readFileSync(file,'utf8');assert(csv.includes('old-policy-decision'));assert(!csv.includes('"decision-demo"'));assert(csv.includes('V1'));checks.push('CSV exactly matches visible records and keeps policy version');
const injected=JSON.parse(JSON.stringify(d));injected.strategies[0].recent.data[0].market.selection='=HYPERLINK("https://example.invalid")';await page.evaluate(({json,at})=>CCOffice.render({json,okAt:at}),{json:injected,at:stamp});await page.locator('#desk-search').fill('');const dl=page.waitForEvent('download');await page.locator('#desk-export').click();assert(fs.readFileSync(await(await dl).path(),'utf8').includes("'=HYPERLINK"));checks.push('CSV spreadsheet formula protection');
await seed('audrey',a);await page.locator('[data-desk-filter=pending]').click();assert.equal(await count(),1);await page.locator('[data-desk-filter=measured]').click();assert.equal(await count(),0);assert((await page.locator('.desk-brief').innerText()).includes('Awaiting genuine'));checks.push('audit has no fabricated review or measurement');
await page.locator('body').click({position:{x:5,y:100}});await page.keyboard.press('/');assert(await page.locator('#desk-search').evaluate(e=>document.activeElement===e));checks.push('keyboard search shortcut');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'experience-verification.json'),JSON.stringify({pass:true,checks,data:'synthetic layout records; not live or provider acceptance'},null,2));console.log(JSON.stringify({pass:true,checks}));await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
