"""Regenerate `api/xavier_page.py` from the static bundle. One source, two hosts.

The Xavier panel is authored once under `frontend/public/command/` --
xavier.html, xavier.css, xavier.js -- and served two ways: as static files
beside the Command Centre (whose shell loads xavier.js for its Xavier tab),
and inlined into one self-contained page on the API's own origin, which is
the origin this repository can deploy and which is same-origin with
`/api/command/*` without a proxy rule. The same arrangement as the desk
(`tools/build_desk_page.py`).

Run after editing any of the three:  python3 -m tools.build_xavier_page
A test compares the two copies exactly, so a forgotten run is caught.
"""

from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))))
BUNDLE = os.path.join(ROOT, "frontend", "public", "command")
TARGET = os.path.join(ROOT, "backend", "sportsassets", "api",
                      "xavier_page.py")

HEAD = '''"""THE XAVIER PANEL, SERVED FROM THE API'S OWN ORIGIN.

GENERATED by `tools/build_xavier_page.py` from `frontend/public/command/`
xavier.html, xavier.css and xavier.js; a test compares this copy with a fresh
build, so editing it by hand is how the two would diverge. The route that
serves it sits behind `require_command`, and the page's only fetch is the one
same-origin read of `/api/command/xavier`. It sends no order and holds no
credential.
"""

'''


def build() -> str:
    html = open(os.path.join(BUNDLE, "xavier.html")).read()
    css = open(os.path.join(BUNDLE, "xavier.css")).read()
    js = open(os.path.join(BUNDLE, "xavier.js")).read()
    html = html.replace('<link rel="stylesheet" href="xavier.css">',
                        "<style>__CSS__</style>")
    html = re.sub(r'  <script src="[^"]+"></script>\n', "", html)
    html = html.replace("</body>", "  <script>__JS__</script>\n</body>")
    return html.replace("__CSS__", css).replace("__JS__", js)


def module_text() -> str:
    return HEAD + 'XAVIER_PAGE_HTML = r"""' + build() + '"""\n'


def main() -> int:
    page = build()
    if "script src=" in page or 'rel="stylesheet"' in page:
        print("the inlined page still references an external asset; the API "
              "origin serves none", file=sys.stderr)
        return 1
    if '"""' in page:
        print("the page contains a triple quote and cannot be inlined as a "
              "raw string", file=sys.stderr)
        return 1
    open(TARGET, "w").write(module_text())
    print("wrote %s (%d bytes of page)" % (TARGET, len(page)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
