#!/usr/bin/env python3
"""BETA48_DATA_GATE — is the six-account comparison admissible, and for what?

READ ONLY, OFFLINE. Reads the sealed reconstructions and writes
research/beta48/BETA48_DATA_GATE.md with exactly the thirteen fields the
directive names, in that order. Contacts nothing. Changes no estimator.

Every number in the output is COMPUTED from the sealed JSONs. The
judgement fields (YES / NO / PARTIAL) are decided by explicit rules
stated in the code below, so the verdict can be re-derived and argued
with rather than taken on trust.

THE RECONCILIATION TARGETS are the directive's own report-derived
hypotheses, which name two channels per account:

    "matched"     -> the pair/merge channel   (MERGE_PNL here)
    "directional" -> the held-to-settlement channel (SETTLED_PNL here)

Those are the same two channels channel_decomposition.py splits lot_s
and lot_p into, so the comparison is like-for-like.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
BLOBS = HERE / "evidence" / "blobs"

# The directive's report-derived hypotheses, verbatim in intent:
#   Ferrari  matched ~+$17.2M / +5.9%   directional ~-$16.2M / -7.7%
#   HRH      matched  ~-$1.35M / -1.5%  directional  ~+$2.46M / +3.3%
#   swisstony matched ~-$3.39M / -0.7%  directional ~+$22.16M / +4.2%
HYPOTHESES = {
    "ferrarichampions2026": {"matched": (17.2e6, 0.059), "directional": (-16.2e6, -0.077)},
    "homerunhazard":        {"matched": (-1.35e6, -0.015), "directional": (2.46e6, 0.033)},
    "swisstony":            {"matched": (-3.39e6, -0.007), "directional": (22.16e6, 0.042)},
}

# RN1's retained-snapshot measurement, for the two-source comparison.
RN1_SNAPSHOT = {"edge_roi": 0.02084, "ci": (-0.00195, 0.04362),
                "fills": 196619, "merges": 78500,
                "sample": "2026-08-06 .. 2026-09-11"}

ACCOUNTS = ("rn1", "w2c33", "homerunhazard", "swisstony", "kch123",
            "ferrarichampions2026")
# A rate agreeing within this many percentage points is "consistent".
RATE_TOL_PP = 2.5


def load(name):
    p = BLOBS / ("%s_reconstruction.json" % name)
    return json.loads(p.read_text()) if p.exists() else None


def decompose(r):
    """Same split as channel_decomposition.py, re-derived here so this
    file stands alone as evidence."""
    lot_s, lot_p = r["lot_s"], r["lot_p"]
    merge = r.get("realized_merge_pnl") or 0.0
    sell = r.get("realized_sell_pnl") or 0.0
    st_stake = (r.get("open_cost") or 0.0) - (r.get("ungraded_open_cost") or 0.0)
    st_pnl = lot_p - merge - sell
    tr_stake = lot_s - st_stake
    assert abs(st_stake + tr_stake - lot_s) < 0.01
    assert abs(st_pnl + merge + sell - lot_p) < 0.01
    return {"merge_pnl": merge, "merge_rate": merge / tr_stake if tr_stake else None,
            "traded_stake": tr_stake,
            "settled_pnl": st_pnl, "settled_rate": st_pnl / st_stake if st_stake else None,
            "settled_stake": st_stake}


def reconcile(name, d):
    """Compare a channel against the report hypothesis. Sign first,
    then rate. A sign disagreement is material however small the number,
    because the sign is what the mechanism claim rests on."""
    h = HYPOTHESES.get(name)
    if not h:
        return None
    out = {}
    for chan, (h_pnl, h_rate) in h.items():
        m_pnl = d["merge_pnl"] if chan == "matched" else d["settled_pnl"]
        m_rate = d["merge_rate"] if chan == "matched" else d["settled_rate"]
        same_sign = (m_pnl >= 0) == (h_pnl >= 0)
        gap_pp = abs((m_rate or 0) - h_rate) * 100
        if not same_sign:
            verd = "SIGN_DISAGREES"
        elif gap_pp <= RATE_TOL_PP:
            verd = "CONSISTENT"
        else:
            verd = "SIGN_AGREES_MAGNITUDE_DIFFERS"
        out[chan] = {"measured_pnl": round(m_pnl, 2),
                     "measured_rate": round(m_rate, 5) if m_rate is not None else None,
                     "report_pnl": h_pnl, "report_rate": h_rate,
                     "gap_pp": round(gap_pp, 2), "verdict": verd}
    return out


def main() -> int:
    recs, dec, rec = {}, {}, {}
    for n in ACCOUNTS:
        r = load(n)
        if r is None:
            continue
        recs[n] = r
        dec[n] = decompose(r["REFERENCE_ACCOUNT_REPLAY"]["LIFETIME"])
        rec[n] = reconcile(n, dec[n])

    L = []
    def w(s=""):
        L.append(s)

    w("# BETA48_DATA_GATE")
    w()
    w("Generated by `research/beta48/data_gate.py` from the sealed")
    w("reconstructions in `research/beta48/evidence/blobs/`, all of which")
    w("came home from run **35028887477** on the repaired commit `f93e0f2`")
    w("and verified byte-exact against the hash the runner printed.")
    w()
    w("Read only. Offline. No estimator, threshold, filter or horizon is")
    w("altered anywhere in this file.")
    w()
    w("---")
    w()

    # ---- the four coverage fields -------------------------------------
    for field, acct in (("RN1_COVERAGE", "rn1"),
                        ("FERRARI_COVERAGE", "ferrarichampions2026"),
                        ("HRH_COVERAGE", "homerunhazard"),
                        ("SWISSTONY_COVERAGE", "swisstony")):
        c = recs[acct]["CENSUS"]
        w("`%s` =" % field)
        w("  %s .. %s (%.2f d), %s fills, %s markets, %s buys / %s sells,"
          % (str(c["RETURNED_RANGE_START"])[:10], str(c["RETURNED_RANGE_END"])[:10],
             c["RETURNED_SPAN_DAYS"], f'{c["ROWS_KEPT"]:,}',
             f'{c["DISTINCT_CONDITIONS"]:,}', f'{c["BUY_COUNT"]:,}',
             f'{c["SELL_COUNT"]:,}'))
        w("  dormant %s d at the common as-of %s; DUPLICATE_FILL_KEYS %s."
          % (c["DAYS_SINCE_LAST_FILL_AT_AS_OF"], str(c["AS_OF_UTC"])[:19],
             c["DUPLICATE_FILL_KEYS"]))
        w("  A windowed-cursor pull is what the endpoint returned, NOT a proof")
        w("  of lifetime completeness.")
        w()

    # ---- REPORT_RECONCILIATION ----------------------------------------
    w("`REPORT_RECONCILIATION` =")
    w()
    w("| account | channel | measured | report says | gap | verdict |")
    w("|---|---|---|---|---|---|")
    for n in ("ferrarichampions2026", "homerunhazard", "swisstony"):
        for chan in ("matched", "directional"):
            r = rec[n][chan]
            w("| %s | %s | $%s (%+.2f%%) | $%s (%+.1f%%) | %.2f pp | **%s** |"
              % (n, chan, f'{r["measured_pnl"]:,.0f}', 100 * (r["measured_rate"] or 0),
                 f'{r["report_pnl"]:,.0f}', 100 * r["report_rate"],
                 r["gap_pp"], r["verdict"]))
    w()
    w("RN1 is reconciled against its own retained snapshot instead, since")
    w("the directive gives no report figure for it:")
    w()
    rl = recs["rn1"]["REFERENCE_ACCOUNT_REPLAY"]["LIFETIME"]
    r30 = recs["rn1"]["REFERENCE_ACCOUNT_REPLAY"]["LAST_30D"]
    w("| source | sample | fills | merges | edge_roi | ci95 |")
    w("|---|---|---|---|---|---|")
    w("| retained snapshot | %s | %s | %s | %+.3f%% | [%+.3f%%, %+.3f%%] |"
      % (RN1_SNAPSHOT["sample"], f'{RN1_SNAPSHOT["fills"]:,}',
         f'{RN1_SNAPSHOT["merges"]:,}', 100 * RN1_SNAPSHOT["edge_roi"],
         100 * RN1_SNAPSHOT["ci"][0], 100 * RN1_SNAPSHOT["ci"][1]))
    w("| Actions pull LIFETIME | %s .. %s | %s | %s | %+.3f%% | [%+.3f%%, %+.3f%%] |"
      % (str(recs["rn1"]["CENSUS"]["RETURNED_RANGE_START"])[:10],
         str(recs["rn1"]["CENSUS"]["RETURNED_RANGE_END"])[:10],
         f'{rl["n_fills"]:,}', f'{rl["n_merges"]:,}', 100 * rl["edge_roi"],
         100 * rl["edge_ci95"][0], 100 * rl["edge_ci95"][1]))
    w("| Actions pull LAST_30D | 30 d to as-of | %s | %s | %+.3f%% | [%+.3f%%, %+.3f%%] |"
      % (f'{r30["_window_fills"]:,}', f'{r30["n_merges"]:,}', 100 * r30["edge_roi"],
         100 * r30["edge_ci95"][0], 100 * r30["edge_ci95"][1]))
    w()
    ratio = RN1_SNAPSHOT["fills"] / r30["_window_fills"]
    w("`RN1_TWO_SOURCE_RECONCILIATION = COVERAGE_DISCREPANCY`. The retained")
    w("snapshot's whole 36-day sample holds %s fills; the Actions pull's"
      % f'{RN1_SNAPSHOT["fills"]:,}')
    w("*shorter* 30-day window holds %s, so the snapshot carries about"
      % f'{r30["_window_fills"]:,}')
    w("**%.0f%%** of the flow the pull shows over a comparable span. These are"
      % (100 * ratio))
    w("not two measurements of one sample. Neither supersedes the other and")
    w("they must never be averaged; the difference is a coverage finding.")
    w()

    # ---- the two validity fields --------------------------------------
    # RULE. A comparison is VALID only if every account it spans passes
    # the repair gates AND its channel reconciles without a sign flip.
    pair_bad = [n for n in rec if rec[n] and rec[n]["matched"]["verdict"] == "SIGN_DISAGREES"]
    dir_bad = [n for n in rec if rec[n] and rec[n]["directional"]["verdict"] == "SIGN_DISAGREES"]
    pair_soft = [n for n in rec if rec[n]
                 and rec[n]["matched"]["verdict"] == "SIGN_AGREES_MAGNITUDE_DIFFERS"]
    dir_soft = [n for n in rec if rec[n]
                and rec[n]["directional"]["verdict"] == "SIGN_AGREES_MAGNITUDE_DIFFERS"]

    w("`FOUR_ACCOUNT_PAIR_COMPARISON_VALID` = **%s**"
      % ("NO" if pair_bad else ("PARTIAL" if pair_soft else "YES")))
    w()
    w("  Rule applied: valid only where every account's pair channel")
    w("  reconciles against the report without a sign flip.")
    if pair_bad:
        w("  Sign flip on: %s." % ", ".join(pair_bad))
    if pair_soft:
        w("  Sign agrees, magnitude differs on: %s." % ", ".join(pair_soft))
    w("  All six accounts PASS the canary repair gates, so the blocker is")
    w("  reconciliation, not extraction.")
    w()
    w("`FOUR_ACCOUNT_DIRECTIONAL_COMPARISON_VALID` = **%s**"
      % ("NO" if dir_bad else ("PARTIAL" if dir_soft else "YES")))
    w()
    if dir_bad:
        w("  Sign flip on: %s." % ", ".join(dir_bad))
    if dir_soft:
        w("  Sign agrees, magnitude differs on: %s." % ", ".join(dir_soft))
    if not dir_bad and not dir_soft:
        w("  Every directional channel reconciles in sign AND in rate to")
        w("  within %.1f pp of the report figure." % RATE_TOL_PP)
    w()

    # ---- CURRENT_REGIME_COVERAGE --------------------------------------
    w("`CURRENT_REGIME_COVERAGE` =")
    w()
    w("| account | dormant (d) | LAST_7D | LAST_14D | LAST_30D | LAST_60D |")
    w("|---|---|---|---|---|---|")
    for n in ACCOUNTS:
        if n not in recs:
            continue
        rp = recs[n]["REFERENCE_ACCOUNT_REPLAY"]
        cells = []
        for win in ("LAST_7D", "LAST_14D", "LAST_30D", "LAST_60D"):
            r = rp.get(win)
            if not isinstance(r, dict) or not (r.get("edge_lots") or 0):
                cells.append("EMPTY")
            else:
                cells.append("%s lots / %s clus" % (f'{r["edge_lots"]:,}',
                                                    f'{r["edge_clusters"]:,}'))
        w("| %s | %s | %s |" % (n, recs[n]["CENSUS"]["DAYS_SINCE_LAST_FILL_AT_AS_OF"],
                                " | ".join(cells)))
    w()
    w("Every window is cut from ONE common wall-clock as-of, so these spans")
    w("are the same calendar days for every account. kch123 last traded 78")
    w("days ago and swisstony 20.6 days ago, so neither has a current")
    w("regime to measure; the empty cells are the repair working, not a")
    w("gap in the pull.")
    w()

    # ---- the three control fields -------------------------------------
    def ctl(name, chan, want_sign):
        d = dec[name]
        v = d["merge_pnl"] if chan == "matched" else d["settled_pnl"]
        ok = (v >= 0) == (want_sign >= 0)
        return ok, v

    w("`PAIR_POSITIVE_CONTROLS_CONFIRMED` =")
    ok, v = ctl("ferrarichampions2026", "matched", +1)
    w("  ferrariChampions2026, the account the report calls pair-POSITIVE,")
    w("  measures MERGE = $%s. **%s**" % (f'{v:,.0f}', "CONFIRMED" if ok else "NOT CONFIRMED"))
    w("  rn1 (+$%s), which the report does not name, is an INDEPENDENT"
      % f'{dec["rn1"]["merge_pnl"]:,.0f}')
    w("  positive control at comparable size, so the positive class is not")
    w("  one account. swisstony also measures positive (+$%s) but is"
      % f'{dec["swisstony"]["merge_pnl"]:,.0f}')
    w("  NOT counted here: its sign is the disputed one below, and a")
    w("  disputed reading cannot serve as a control for either class.")
    w()
    w("`PAIR_NEGATIVE_CONTROLS_CONFIRMED` =")
    for n in ("homerunhazard", "swisstony"):
        ok, v = ctl(n, "matched", -1)
        w("  %s, called pair-NEGATIVE: MERGE = $%s. **%s**"
          % (n, f'{v:,.0f}', "CONFIRMED" if ok else "NOT CONFIRMED"))
    w("  w2c33 (-$%s) and kch123 (-$%s) are negative too and were not"
      % (f'{-dec["w2c33"]["merge_pnl"]:,.0f}', f'{-dec["kch123"]["merge_pnl"]:,.0f}'))
    w("  named in the report, so they are independent negative controls.")
    w()
    w("`DIRECTIONAL_POSITIVE_CONTROLS_CONFIRMED` =")
    for n in ("homerunhazard", "swisstony"):
        ok, v = ctl(n, "directional", +1)
        w("  %s, called directional-POSITIVE: SETTLED = $%s. **%s**"
          % (n, f'{v:,.0f}', "CONFIRMED" if ok else "NOT CONFIRMED"))
    ok, v = ctl("ferrarichampions2026", "directional", -1)
    w("  ferrariChampions2026, called directional-NEGATIVE: SETTLED = $%s."
      % f'{v:,.0f}')
    w("  **%s**" % ("CONFIRMED" if ok else "NOT CONFIRMED"))
    w()

    # ---- BIGGEST_DISCREPANCY ------------------------------------------
    w("`BIGGEST_DISCREPANCY` =")
    w()
    sw = rec["swisstony"]["matched"]
    w("Two, and they are different in kind.")
    w()
    w("**1. The one that blocks a comparison.** swisstony's pair channel.")
    w("The report puts it at $%s (%+.1f%%); it measures $%s (%+.3f%%) --"
      % (f'{sw["report_pnl"]:,.0f}', 100 * sw["report_rate"],
         f'{sw["measured_pnl"]:,.0f}', 100 * (sw["measured_rate"] or 0)))
    w("a SIGN FLIP. Both numbers are near zero against a $%s traded"
      % f'{dec["swisstony"]["traded_stake"]:,.0f}')
    w("stake, so this is a near-zero quantity whose sign is not settled --")
    w("which is exactly the quantity a pair strategy would be built on.")
    w("Meanwhile swisstony's DIRECTIONAL channel reconciles almost exactly")
    w("($%s vs $%s), so the disagreement is specific to the"
      % (f'{dec["swisstony"]["settled_pnl"]:,.0f}',
         f'{rec["swisstony"]["directional"]["report_pnl"]:,.0f}'))
    w("pair channel and is not a coverage artefact of the whole account.")
    w()
    w("**2. The one that matters most for BETA48.** The headline `edge_roi`")
    w("is positive for all six accounts, but the pair channel -- the only")
    w("mechanism BETA48 Engine A/C would actually copy -- changes sign")
    w("across them:")
    w()
    w("| account | MERGE (pair) | SETTLED (hold) | settled share of stake |")
    w("|---|---|---|---|")
    for n in sorted(dec, key=lambda k: -dec[k]["merge_pnl"]):
        d = dec[n]
        share = d["settled_stake"] / (d["settled_stake"] + d["traded_stake"])
        w("| %s | $%s | $%s | %.1f%% |"
          % (n, f'{d["merge_pnl"]:,.0f}', f'{d["settled_pnl"]:,.0f}', 100 * share))
    w()
    pos = [n for n in dec if dec[n]["merge_pnl"] > 0]
    neg = [n for n in dec if dec[n]["merge_pnl"] <= 0]
    w("%d of 6 positive (%s), %d of 6 negative (%s)."
      % (len(pos), ", ".join(sorted(pos)), len(neg), ", ".join(sorted(neg))))
    w("Between %.1f%% and %.1f%% of the capital behind those headline"
      % (100 * min(d["settled_stake"] / (d["settled_stake"] + d["traded_stake"])
                   for d in dec.values()),
         100 * max(d["settled_stake"] / (d["settled_stake"] + d["traded_stake"])
                   for d in dec.values())))
    w("figures is held to settlement, not traded as pairs.")
    w()

    # ---- NEXT_DECISIVE_EXPERIMENT -------------------------------------
    w("`NEXT_DECISIVE_EXPERIMENT` =")
    w()
    w("The four-account x frozen first-leg-bucket table, because it is the")
    w("only thing that separates the four explanations still standing for")
    w("why the pair channel changes sign. Right now")
    w("`PAIR_MECHANISM_CROSS_ACCOUNT_REPLICATION` cannot be called: the")
    w("sign splits 3/3, and a split is equally consistent with")
    w("STRUCTURAL_DISCRIMINATOR, ACCOUNT_SELECTION_PROXY, MARKET_MIX_PROXY")
    w("and REGIME_PROXY.")
    w()
    w("Per account x frozen first-leg price bucket: OPENS, COMPLETION at")
    w("5s / 1h / settlement, MEAN and MEDIAN COMPLETED_PAIR_BASIS, P25/P75,")
    w("RESIDUAL_RATE, MATCHED_PNL, MATCHED_ROI. It is decisive because the")
    w("bucket is a DECISION-TIME fact: if the sign tracks the bucket within")
    w("every account, the discriminator is structural; if it tracks the")
    w("account with the bucket held constant, it is selection; if it tracks")
    w("the market mix or the calendar, it is one of the proxies.")
    w()
    w("It is also fully offline -- it needs no new extraction, no venue")
    w("call, no capital and no order. Every input is already sealed here.")
    w()
    w("---")
    w()
    w("**STOP conditions: none hit.** mirror_live = false. No order, no")
    w("capital, no credential, no production activation. Track A untouched.")
    w("Phase X untouched.")

    out = HERE / "BETA48_DATA_GATE.md"
    out.write_text("\n".join(L) + "\n")
    print("\n".join(L))
    print("\nsealed -> research/beta48/BETA48_DATA_GATE.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
