"""The rehearsal, driven through the REAL no-argument entry point.

WHAT MAKES THIS A REHEARSAL AND NOT A UNIT TEST. Every scenario calls
`bettor_live_loop.main()` WITH NO ARGUMENTS -- the exact call
`workers/all.py` makes in production. Nothing is injected through a
keyword, because a keyword is a seam production never uses and the
2026-09-22 NO_CONTROL_POOL failure came from exactly that: every local
proof had passed a pool, so the None-resolving path the service
actually takes had never been exercised and refused its first
reservation in the live probe.

    the entry point     `bettor_live_loop.main()`          -- real
    the mode switch     the process environment            -- real
    the control         Postgres `ingestion_state`         -- real
    the allowlist       a manifest file on disk            -- real
    the budget ledger   seeded from the real run row       -- real
    the journal         real files, real fsync             -- real

    THE TRANSPORT       A FAKE. `bettor_market_stream.MarketStream` is
                        replaced in THIS PROCESS by `FakeStream`. NO
                        SOCKET IS OPENED, NO VENUE BYTE IS RECEIVED,
                        AND NO CREDENTIAL IS USED -- the key id and
                        secret below are the literal strings
                        "REHEARSAL-KEY-ID" and "REHEARSAL-SECRET",
                        invented here and handed to a class that
                        ignores them. Every frame in the output was
                        generated by the loop below. The one thing this
                        rehearsal therefore CANNOT establish is that
                        the venue's socket behaves as `MarketStream`
                        assumes.

    THE CREDENTIAL CHECK is still real: scenario S0 runs with the
    placeholders removed and shows the runner refusing to start.

Run:  python research/beta48/incentive_rehearsal.py
"""
from __future__ import annotations

import asyncio
import json
import os
import shutil
import sys
import tempfile
import time
from datetime import datetime, timedelta, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "backend"))

PORT = os.environ.get("REHEARSAL_PG_PORT", "5433")
DSN = "postgresql://postgres@localhost:%s/rehearsal" % PORT
os.environ["DATABASE_URL"] = DSN
os.environ["PMUS_KEY_ID"] = "REHEARSAL-KEY-ID"
os.environ["PMUS_SECRET_KEY"] = "REHEARSAL-SECRET"

import asyncpg                                              # noqa: E402

from sportsassets import bettor_incentive_budget as bud     # noqa: E402
from sportsassets import bettor_incentive_journal as jrnl   # noqa: E402
from sportsassets import bettor_incentive_manifest as man   # noqa: E402
from sportsassets import bettor_incentive_state as st       # noqa: E402
from sportsassets import bettor_live_control as ctl         # noqa: E402
from sportsassets import bettor_market_stream as ms         # noqa: E402
from sportsassets.workers import bettor_live_loop as bll    # noqa: E402

RESULTS: list = []
WORK = tempfile.mkdtemp(prefix="incentive-rehearsal-")


# ── the fake transport, labelled at every exit ───────────────────────

class FakeStream:
    """The same surface `MarketStream` presents, and none of its socket.

    It emits synthetic ladders on a thread-free timer driven by the
    runner's own polling, and bumps its epoch once so the reconnect and
    resubscription paths are exercised. Every record it produces is
    stamped SIMULATED.
    """

    SIMULATED = True

    def __init__(self, key_id, secret_key, *, on_book=None, on_trade=None,
                 autostart=False):
        self.key_id_seen = key_id       # recorded to prove it was ignored
        self._cb = on_book
        self.epoch = 0
        self.connected = False
        self.reconnects = 0
        self.updates = 0
        self.heartbeats = 0
        self.last_heartbeat_at = None
        self.last_frame_at = None
        self.socket_closes = 0
        self.socket_closed_at_iso = None
        self.socket_close_ok = None
        self.subscribe_calls: list = []
        self.slugs: list = []
        self._books: dict = {}
        self._hb_cb = None
        self._t0 = None
        self._emitted = 0
        self._bumped = False

    # the API the runner uses
    def set_heartbeat_listener(self, cb):
        self._hb_cb = cb

    def subscribe(self, slugs):
        self.subscribe_calls.append(list(slugs))
        self.slugs = list(slugs)

    def start(self):
        self.connected = True
        self.epoch = 1
        self._t0 = time.time()
        self._emit_all()

    def stop(self):
        self.connected = False
        self.socket_closes += 1
        self.socket_close_ok = True
        self.socket_closed_at_iso = datetime.now(timezone.utc).isoformat()

    def book_at(self, slug, *, decided_at=None, max_source_age_s,
                max_receipt_age_s):
        rec = self._books.get(slug)
        if rec is None:
            return {"slug": slug, "eligible": False, "reason": ms.NO_BOOK,
                    "book": None, "venue_state": None, "source_ts": None}
        age = time.time() - rec["received_at"]
        eligible = self.connected and rec["epoch"] == self.epoch \
            and age <= max_receipt_age_s
        return {"slug": slug, "eligible": eligible,
                "reason": ms.ELIGIBLE if eligible else ms.STALE_RECEIPT,
                "book": rec["book"], "venue_state": rec["state"],
                "source_ts": rec["source_ts"], "epoch": rec["epoch"],
                "simulated": True}

    # driven by the runner's poll, through the heartbeat hook
    def tick(self):
        if not self.connected:
            return
        if not self._bumped and time.time() - self._t0 > 3.0:
            # ONE SIMULATED RECONNECT: the epoch advances, every book
            # from the old epoch is void, and every slug is resubscribed.
            self._bumped = True
            self.epoch += 1
            self.reconnects += 1
            self._emit_all()
            return
        if self._emitted < 40:
            self._emit_one(self.slugs[self._emitted % len(self.slugs)])
        self.heartbeats += 1
        self.last_heartbeat_at = time.time()
        if self._hb_cb:
            self._hb_cb({"heartbeat": {"simulated": True}})

    def _emit_all(self):
        for s in self.slugs:
            self._emit_one(s)

    def _emit_one(self, slug):
        now = time.time()
        rec = {"source_ts": datetime.now(timezone.utc).isoformat(),
               "received_at": now,
               "received_at_iso": datetime.now(timezone.utc).isoformat(),
               "state": "MARKET_STATE_OPEN", "stats": {},
               "book": {"bids": [{"px": "0.50", "qty": "400"},
                                 {"px": "0.49", "qty": "250"}],
                        "offers": [{"px": "0.52", "qty": "380"}]},
               "epoch": self.epoch, "replacement": ms.BOOK_REPLACEMENT,
               "simulated": True}
        self._books[slug] = rec
        self.updates += 1
        self._emitted += 1
        self.last_frame_at = now
        if self._cb:
            self._cb(slug, rec)


LIVE: dict = {}


def _factory(*a, **kw):
    s = FakeStream(*a, **kw)
    LIVE["stream"] = s
    return s


# ── the environment, set the way the service would be configured ─────

def _manifest_file(n_markets: int, et_date: str, path: str) -> str:
    progs = [{"market_slug": "rehearsal-market-%02d" % i,
              "program_id": "culture_low_20260921",
              "created_at": "2026-09-21T00:00:00Z",
              "period": man.PERIOD_DAILY, "reward_pool": 50.0,
              "discount_factor": 0.25, "target_size": 500,
              "start": et_date + "T04:00:00Z", "end": et_date + "T04:00:00Z",
              "status": "active",
              "event_start_time": "2026-12-27T04:59:00.000Z",
              "instrument_state": "INSTRUMENT_STATE_OPEN",
              "category": "culture"} for i in range(n_markets)]
    m = {"manifest": man.MANIFEST_VERSION,
         "manifest_id": "REHEARSAL%02d" % n_markets,
         "captured_at": datetime.now(timezone.utc).isoformat(),
         "source": man.INCENTIVES_URL, "authenticated": False,
         "response_digest": "sha256:REHEARSAL-FIXTURE-NOT-VENUE-CAPTURED",
         "et_date": et_date, "pages_read": 0,
         "FIXTURE": "SYNTHETIC. These slugs do not exist at the venue and "
                    "these terms were not retrieved from it.",
         "programs": progs}
    man.save(path, m)
    return path


def _configure(*, manifest_path, et_date, journal_dir, creds=True):
    os.environ.pop("BETTOR_LIVE_LOOP", None)
    os.environ[man.MANIFEST_ENV] = manifest_path or ""
    if not manifest_path:
        os.environ.pop(man.MANIFEST_ENV, None)
        os.environ[man.MANIFEST_ENV] = "/nonexistent/manifest.json"
    os.environ[man.ET_DATE_ENV] = et_date
    os.environ[man.WATCH_MAX_ENV] = "12"
    os.environ[jrnl.DIR_ENV] = journal_dir
    os.environ[jrnl.DISK_ENV] = "1"
    os.environ[bud.RECONNECT_ENV] = "20"
    os.environ[bud.RESUBSCRIBE_ENV] = "40"
    os.environ["PMUS_KEY_ID"] = "REHEARSAL-KEY-ID" if creds else ""
    os.environ["PMUS_SECRET_KEY"] = "REHEARSAL-SECRET" if creds else ""
    from sportsassets import config
    config.settings.cache_clear()


# ── the control row, written exactly as render-ops writes it ─────────

async def _sql(q, *args):
    conn = await asyncpg.connect(DSN)
    try:
        return await conn.fetch(q, *args)
    finally:
        await conn.close()


async def _set_control(value):
    if value is None:
        await _sql("DELETE FROM ingestion_state WHERE key=$1",
                   ctl.CONTROL_KEY)
        return
    await _sql("INSERT INTO ingestion_state (key, value) VALUES ($1,$2::jsonb)"
               " ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value",
               ctl.CONTROL_KEY, json.dumps(value))


async def _clear_run():
    await _sql("DELETE FROM ingestion_state WHERE key=$1", st.RUN_KEY)


async def _run_row():
    r = await _sql("SELECT value FROM ingestion_state WHERE key=$1",
                   st.RUN_KEY)
    return json.loads(r[0]["value"]) if r else None


def record(name, question, out, checks):
    ok = all(v for _, v in checks)
    RESULTS.append({"scenario": name, "question": question, "pass": ok,
                    "checks": [{"check": k, "pass": bool(v)}
                               for k, v in checks],
                    "why": out.get("why") or out.get("end_why"),
                    "started": out.get("started")})
    print("  %s  %-34s %s" % ("PASS" if ok else "FAIL", name, question))
    for k, v in checks:
        print("        %s %s" % ("ok " if v else "NO ", k))


# ── the scenarios ────────────────────────────────────────────────────

async def main() -> int:
    today = datetime.now(timezone.utc).astimezone(
        __import__("zoneinfo").ZoneInfo("America/New_York")).date().isoformat()
    yesterday = (datetime.strptime(today, "%Y-%m-%d").date()
                 - timedelta(days=1)).isoformat()
    m12 = _manifest_file(12, today, os.path.join(WORK, "m12.json"))
    m09 = _manifest_file(9, today, os.path.join(WORK, "m09.json"))
    m12y = _manifest_file(12, yesterday, os.path.join(WORK, "m12y.json"))
    jdir = os.path.join(WORK, "journal")

    print("\nREHEARSAL -- every call below is `bll.main()` with NO arguments")
    print("transport: FakeStream (SIMULATED; no socket, no venue, no "
          "credential)\n")

    # ── S0 control absent: absence is not permission ─────────────────
    await _set_control(None)
    await _clear_run()
    _configure(manifest_path=m12, et_date=today, journal_dir=jdir)
    out = await bll.main()
    record("S0 control absent", "does absence permit a run?", out, [
        ("did not start", out.get("started") is False),
        ("why is CONTROL_ROW_ABSENT", out.get("why") == ctl.W_ABSENT),
        ("no run row was created", (await _run_row()) is None),
        ("no journal directory was made", not os.path.isdir(jdir)),
    ])

    # ── S1 control false: the stop, read before anything ─────────────
    await _set_control(False)
    out = await bll.main()
    record("S1 control false", "does a stopped control cost anything?", out, [
        ("did not start", out.get("started") is False),
        ("why is STOPPED_BY_CONTROL", out.get("why") == ctl.W_STOPPED),
        ("no run row", (await _run_row()) is None),
    ])

    # ── S2 credentials: the stream authenticates ─────────────────────
    await _set_control(True)
    _configure(manifest_path=m12, et_date=today, journal_dir=jdir,
               creds=False)
    out = await bll.main()
    record("S2 no credentials", "does it degrade to a public client?", out, [
        ("did not start", out.get("started") is False),
        ("why is NO_CREDENTIALS", out.get("why") == "NO_CREDENTIALS"),
    ])

    # ── S3 manifest absent ───────────────────────────────────────────
    _configure(manifest_path=None, et_date=today, journal_dir=jdir)
    out = await bll.main()
    record("S3 manifest absent", "is an absent manifest an empty universe?",
           out, [
               ("did not start", out.get("started") is False),
               ("why is MANIFEST_ABSENT", out.get("why") == man.M_ABSENT),
           ])

    # ── S4 nine markets: INSUFFICIENT COVERAGE, and no fallback ──────
    _configure(manifest_path=m09, et_date=today, journal_dir=jdir)
    out = await bll.main()
    al = out.get("allowlist") or {}
    record("S4 nine markets", "does it top up from the general universe?",
           out, [
               ("did not start", out.get("started") is False),
               ("why is INSUFFICIENT_COVERAGE",
                out.get("why") == man.M_INSUFFICIENT),
               ("reports 9 markets against a gate of 10",
                al.get("markets") == 9 and al.get("min_markets") == 10),
               ("watched nothing at all", LIVE.get("stream") is None),
           ])

    # ── S5 the ET window has ended: the half-open bound ends the run ─
    _configure(manifest_path=m12y, et_date=yesterday, journal_dir=jdir)
    LIVE.clear()
    out = await bll.main()
    record("S5 window ended", "does a past ET date still collect?", out, [
        ("started", out.get("started") is True),
        ("ended on ET_DATE_ENDED", out.get("end_why") == "ET_DATE_ENDED"),
        ("ran for under a second", (out.get("ran_s") or 99) < 1.0),
        ("the socket was closed", (out.get("stream") or {}).get("stopped")),
    ])

    # ── S6 a real collection, stopped by the DATABASE ────────────────
    await _clear_run()
    _configure(manifest_path=m12, et_date=today, journal_dir=jdir)
    LIVE.clear()

    async def _drive():
        """Stand in for the venue: tick the fake stream while it runs."""
        while True:
            s = LIVE.get("stream")
            if s is not None:
                s.tick()
            await asyncio.sleep(0.2)

    driver = asyncio.create_task(_drive())
    task = asyncio.create_task(bll.main())
    await asyncio.sleep(5.0)
    stream = LIVE.get("stream")
    subs = list(stream.subscribe_calls) if stream else []
    # The operator's stop, written exactly as `render-ops sql obs-stop`
    # writes it. Nothing else is touched.
    t_stop = time.time()
    await _set_control(False)
    out = await asyncio.wait_for(task, timeout=ctl.CONTROL_EVERY_S + 20)
    latency = time.time() - t_stop
    driver.cancel()
    row = await _run_row()
    jfiles = []
    for root, _d, files in os.walk(jdir):
        jfiles += [os.path.join(root, f) for f in files]
    recs = []
    for f in jfiles:
        recs += [json.loads(x) for x in open(f, encoding="utf-8")]
    kinds = {}
    for r in recs:
        kinds[r["kind"]] = kinds.get(r["kind"], 0) + 1
    al = out.get("allowlist") or {}
    fd = out.get("feed") or {}
    bd = out.get("budget") or {}
    ladders = [r for r in recs if r["kind"] == jrnl.R_LADDER]
    initial = [r for r in ladders if r["ladder_class"] == "INITIAL_LADDER"]
    record("S6 collection + DB stop", "does it collect, and does the row "
           "stop it?", out, [
               ("started", out.get("started") is True),
               ("watched exactly the 12 allowlisted markets",
                al.get("markets") == 12 and len(al.get("slugs") or []) == 12),
               ("ONE subscribe call, one batch, 12 slugs",
                len(subs) == 1 and len(subs[0]) == 12),
               ("12 <= SUB_BATCH (%d)" % ms.SUB_BATCH,
                len(subs[0]) <= ms.SUB_BATCH),
               ("reports 12 markets / 1 programme / 1 event",
                (al.get("markets"), al.get("distinct_programs"),
                 al.get("distinct_events")) == (12, 1, 1)),
               ("independence is stated, not implied",
                "NOT independent" in (al.get("independence_note") or "")),
               ("ended on STOPPED_BY_CONTROL",
                out.get("end_why") == "STOPPED_BY_CONTROL"),
               ("stop landed within CONTROL_EVERY_S + poll",
                latency <= ctl.CONTROL_EVERY_S + 2.0),
               ("a reconnect was seen and a new epoch opened",
                fd.get("epoch_count", 0) >= 2),
               ("each epoch re-established an INITIAL_LADDER",
                len(initial) >= 24),
               ("LADDER, EPOCH and PROGRAM_VERSION were all persisted",
                all(k in kinds for k in (jrnl.R_LADDER, jrnl.R_EPOCH,
                                         jrnl.R_PROGRAM, jrnl.R_RUN_OPEN,
                                         jrnl.R_RUN_CLOSE))),
               ("HTTP spend is within the eight-request cap",
                bd.get("used", 99) <= bud.TOTAL_CAP),
               ("zero listing/BBO/settlement requests were made",
                bd.get("by_kind", {}).get("manifest", 0) == 0),
               ("the run row persisted the spend",
                (row or {}).get("http_spent") is not None),
               ("no orders", out.get("orders_submitted") == 0),
           ])
    spend_after_s6 = dict((row or {}).get("http_spent") or {})

    # ── S7 restart: the supervisor starts a returning loop again ─────
    await _set_control(True)
    LIVE.clear()
    driver = asyncio.create_task(_drive())
    task = asyncio.create_task(bll.main())
    await asyncio.sleep(2.0)
    await _set_control(False)
    out2 = await asyncio.wait_for(task, timeout=ctl.CONTROL_EVERY_S + 20)
    driver.cancel()
    row2 = await _run_row()
    b2 = out2.get("budget") or {}
    record("S7 restart", "does a restart re-grant the allowance?", out2, [
        ("started", out2.get("started") is True),
        ("resumed the SAME run", out2.get("resumed") is True),
        ("same run_id", out2.get("run_id") == out.get("run_id")),
        ("boot counter advanced", (row2 or {}).get("boots") == 2),
        # THE SEED IS THE CLAIM, NOT THE END STATE. Boot 2 legitimately
        # spends more than boot 1 ended on -- the mid-run recheck fires
        # once per boot -- so comparing end states proves nothing in
        # either direction. What must hold is that boot 2 STARTED from
        # boot 1's total rather than from zero.
        ("the ledger was seeded from the row, not reset",
         b2.get("seeded_from") == spend_after_s6),
        ("boot 2 did not get a fresh eight",
         b2.get("used", 0) > sum(spend_after_s6.values())),
        ("the cap still binds across boots",
         b2.get("used", 99) <= bud.TOTAL_CAP),
        ("the recheck sub-cap bounds repeated restarts",
         b2.get("by_kind", {}).get("recheck", 99)
         <= bud.SUBCAPS[bud.K_RECHECK]),
    ])

    # ── S8 the budget is durable and refuses when spent ──────────────
    L = bud.RequestLedger()
    L.seed({"manifest": 4, "recheck": 2, "retry": 2})
    refusals = [L.spend(k) for k in (bud.K_MANIFEST, bud.K_RECHECK,
                                     "listing", "bbo_attempt")]
    record("S8 exhausted budget", "can a spent allowance be spent again?",
           {}, [
               ("a spent ledger grants nothing",
                all(not r["ok"] for r in refusals)),
               ("listing is refused BY NAME, not merely uncalled",
                refusals[2]["verdict"] == bud.R_FORBIDDEN),
               ("settlement likewise",
                L.spend("settlement")["verdict"] == bud.R_FORBIDDEN),
           ])

    # ── S9 the general loop is untouched when unconfigured ───────────
    os.environ.pop(man.MANIFEST_ENV, None)
    record("S9 mode off", "is the deployment inert until configured?", {}, [
        ("unset manifest leaves incentive mode off",
         bll._incentive_mode() is False),
        ("a blank value is also off",
         (os.environ.update({man.MANIFEST_ENV: "  "}),
          bll._incentive_mode())[1] is False),
    ])
    os.environ.pop(man.MANIFEST_ENV, None)

    await _set_control(None)
    await _clear_run()

    passed = sum(1 for r in RESULTS if r["pass"])
    print("\n%d of %d scenarios passed" % (passed, len(RESULTS)))
    print("TRANSPORT WAS SIMULATED: no socket was opened, no venue byte was "
          "received,\nand the credentials were the invented strings "
          "'REHEARSAL-KEY-ID'/'REHEARSAL-SECRET'.")
    out_path = os.path.join(HERE, "acceptance",
                            "incentive_rehearsal_result.json")
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump({"rehearsal": "BETTOR_INCENTIVE_REHEARSAL_V1",
                   "at": datetime.now(timezone.utc).isoformat(),
                   "entry_point": "bettor_live_loop.main()  [no arguments]",
                   "transport": "SIMULATED -- FakeStream; no socket, no "
                                "venue byte, no credential",
                   "credentials": "invented placeholders, never dispatched",
                   "database": "local PostgreSQL 16, real ingestion_state",
                   "scenarios": RESULTS,
                   "passed": passed, "total": len(RESULTS)},
                  fh, indent=2)
    print("wrote %s" % out_path)
    shutil.rmtree(WORK, ignore_errors=True)
    return 0 if passed == len(RESULTS) else 1


if __name__ == "__main__":
    ms.MarketStream = _factory          # THE ONLY SUBSTITUTION
    sys.exit(asyncio.run(main()))
