"""Management finish: existing reads only; no execution or policy changes."""

CSS = r"""
.office-account-toggle{display:none}
@media(max-width:800px){.office-account:not([data-expanded=true]) .acct7>div:not([data-acct7=cash_usd]):not([data-acct7=total_equity_usd]){display:none}.office-account:not([data-expanded=true]) .note{display:none}.office-account-toggle{display:block;border:0;background:none;color:#c7ddeb;font:11px var(--display);padding:10px 0 0;cursor:pointer}}
.office-board{display:flex;flex-direction:column}.office-status{order:0}.desk-toolbar{order:1}#office-content,.desk-no-match{order:2}.desk-brief{order:3;margin-top:20px}.desk-activity{order:4}.office-side .cc-stage{height:180px;min-height:180px!important}.office-side #cc-hb{display:none}.office-account .failbox{padding:10px!important}
body.cc{background:#080f18;background-image:radial-gradient(ellipse at 70% -20%,#203c5444,transparent 60%)}
.office-heading{padding:20px 0 14px}.office-heading h1{font-size:clamp(30px,3vw,43px);letter-spacing:-.045em}.office-heading p{color:#a5bdce}.office-heading>a{border-radius:99px}
.office-layout{gap:24px}.office-board{min-width:0}.office-side{border-color:#334b5e;background:linear-gradient(160deg,#1c3143,#0e1a27 60%)}
.office-account{margin:0 0 24px;padding:16px 20px!important;border:1px solid #2c4255!important;border-radius:16px;background:linear-gradient(100deg,#142332,#101b28)!important}
.office-account .lbl{font-size:10px!important;letter-spacing:.075em;color:#acc6d9!important}.office-account .acct7{display:grid!important;grid-template-columns:repeat(7,minmax(0,1fr))!important;gap:16px;margin-top:12px}.office-account .acct7 small{display:block;font-size:10px;color:#9db1c3}.office-account .acct7 b{display:block;font:600 clamp(13px,1.25vw,19px)/1.5 var(--display);letter-spacing:-.035em;color:#edf6ff}.office-account .note{font-size:10px!important;color:#9eb0c0!important}
.office-status{padding:8px 0 15px;gap:8px;flex-wrap:wrap}.work-heading h2{font-size:23px;letter-spacing:-.03em}.work-heading p{max-width:330px}.work-item{border:1px solid #2d4356;border-radius:15px;background:#111f2d;margin-bottom:10px;box-shadow:0 7px 24px #0002}.work-item>summary{padding:19px 20px;transition:background .15s}.work-item>summary:hover{background:#1a2f41}.work-item[open]{border-color:#66879e}.work-item[open]>.work-detail{border-top:1px solid #334b5d;background:#0f1c29}.work-name h3{font-size:16px;letter-spacing:-.015em}.club-logo{background:#f5f7fa!important;box-shadow:0 3px 15px #0003;border:0!important}.work-number strong{font-size:23px;letter-spacing:-.045em}.work-signal{border-radius:6px;font-size:10px;letter-spacing:.035em}.work-decision p{font-size:12px;color:#dfedf6}.work-detail .work-rationale{font-size:14px;line-height:1.7}.office-summary{border-color:#2d4356;background:#0d1b28;border-radius:14px}.office-metric small{font-size:10px;letter-spacing:.025em}.office-metric strong{font-size:26px}.desk-brief{border-radius:16px}.desk-toolbar{padding-top:2px}.desk-activity{background:#0c1824;border:1px solid #263c4e;border-radius:16px;padding:18px 20px}.desk-event:last-child{border-bottom:0}
.office-side .talk-log{max-height:370px;scroll-behavior:smooth}.office-side .talk-msg{font-size:14px;line-height:1.65;padding:13px 14px}.talk-msg .who{font-size:10px;letter-spacing:.06em;margin-bottom:7px}.talk-msg .meta{font-size:10px}.talk-msg.err{border:1px solid #936449;background:#352721!important;color:#ffe5d0}.talk-pending{border:1px solid #45657b;min-height:68px}.talk-pending .body:before{content:'';display:inline-block;width:7px;height:7px;border-radius:50%;background:#bde8ff;margin-right:9px;animation:office-pulse 1.4s infinite}.talk-cancel,.talk-recovery button,.office-transcript,.talk-copy{border:1px solid #496177;border-radius:7px;background:#1b3042;color:#e6f3ff;padding:7px 10px;font:11px var(--display);cursor:pointer;margin-top:9px}.talk-recovery{display:flex;gap:7px;flex-wrap:wrap}.talk-recovery+small{display:block;margin-top:8px;font-size:9px;overflow-wrap:anywhere}.office-transcript{margin:4px 0 8px}.talk-copy{margin-left:8px;padding:4px 8px}.talk-state{background:#172b3b!important;color:#c5e0f2!important;border:1px solid #38566d!important;font-size:12px!important}.office-response-mode{display:flex;align-items:center;justify-content:space-between;font-size:11px}.office-response-mode select{padding:7px 10px;border:1px solid #476379;border-radius:8px;background:#0d1c2b;color:#dfedf8}.office-side textarea{min-height:76px!important}.office-side .talk-note{line-height:1.7}.desk-presence{border-bottom:1px solid #2d4457}.office-report-note{font:11px var(--display);color:#9ab4c9;margin:5px 0 12px}
button:focus-visible,summary:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid #a9dbfa!important;outline-offset:3px}
@keyframes office-pulse{50%{opacity:.3}}
@media(max-width:1100px){.office-account .acct7{grid-template-columns:repeat(4,minmax(0,1fr))!important}.office-layout{gap:18px}}
@media(max-width:800px){.office-heading{padding-top:14px}.office-heading h1{font-size:32px}.office-account{padding:14px!important;margin-bottom:16px}.office-account .acct7{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:12px}.office-account .acct7 b{font-size:19px}.office-account .note{line-height:1.6}.work-item>summary{padding:16px}.work-number strong{font-size:22px}.office-side.desk-conversation-open{background:#0d1b28}.office-side .cc-hero{padding-top:0}.office-side .cc-stage{height:136px;min-height:136px!important}.office-side .talk-log{max-height:40vh}.office-side #talk{padding-top:6px}.office-side .talk-form{position:sticky;top:48px;background:#0d1b28;z-index:1;padding:8px 0}.desk-activity{padding:16px}.work-name h3{font-size:16px}.talk-btns button{min-height:42px}.office-response-mode select{font-size:16px}.desk-conversation-close{min-height:40px}}
@media(prefers-reduced-motion:reduce){.talk-pending .body:before{animation:none}.office-side .talk-log{scroll-behavior:auto}.work-item>summary{transition:none}}
@media print{.office-side,.desk-mobile-talk,.cc-top,.desk-toolbar,.desk-actions,.office-heading>a{display:none!important}.office-layout{display:block}.work-item,.desk-brief,.office-account{break-inside:avoid}body.cc{background:white;color:black}.office-advanced{display:none}}
@media(max-width:800px){.office-heading{margin:10px 0 14px;padding:8px 0}.office-heading h1{font-size:28px}.office-heading p{font-size:12px;margin-top:4px}.office-heading .office-kicker{font-size:9px}.office-status{padding:8px 0;margin-bottom:10px}.desk-toolbar{gap:7px;margin-bottom:14px}.desk-filter{font-size:9px;padding:7px}.desk-filter-count{min-width:28px}.desk-tool{font-size:10px;padding:7px 8px}.office-metric{padding:12px}.office-metric strong{font-size:20px}.office-metric small{font-size:9px}.work-heading h2{font-size:21px}.desk-mobile-talk{padding:12px 16px}}
"""

JS = r"""
(function(){
 'use strict';
 var heading=document.querySelector('.office-heading'),account=document.getElementById('paper-acct'),talk=document.getElementById('talk');
 if(!heading||!talk||!window.CCOffice)return;
 if(account){heading.after(account);account.classList.add('office-account');account.addEventListener('click',function(e){if(!e.target.closest('.office-account-toggle'))return;account.dataset.expanded=account.dataset.expanded==='true'?'false':'true';e.target.setAttribute('aria-expanded',account.dataset.expanded);e.target.textContent=account.dataset.expanded==='true'?'Less account detail −':'Account details +';});}
 // Use the existing single-snapshot renderer. Never assemble balances from cards.
 var prior=CCOffice.render,last=null;
 function paintAccount(st){if(st&&st.json)last=st;var effective=st&&st.json?st:last?Object.assign({},last,{fail:st&&st.fail}):st;if(account&&CC.ops.accountStrip){var a=CC.ops.accountStrip(effective);account.dataset.status=a.status;account.innerHTML=a.html+(a.status==='OK'?'<button type="button" class="office-account-toggle" aria-expanded="'+(account.dataset.expanded==='true')+'">'+(account.dataset.expanded==='true'?'Less account detail −':'Account details +')+'</button>':'');}};
 CCOffice.render=function(st){prior(st);paintAccount(st);};
 var panels=CC.ops.panels;CC.ops.panels=function(kind,st){var result=panels(kind,st);if(kind===document.body.dataset.kind)paintAccount(st);return result;};
 var download=document.createElement('button');download.type='button';download.className='office-transcript';download.textContent='Download conversation ↓';
 talk.querySelector('.talk-log').before(download);
 function save(name,text){var url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
 download.onclick=function(){var rows=Array.from(talk.querySelectorAll('.talk-msg:not(.talk-pending)')).map(function(el){var copy=el.cloneNode(true);copy.querySelectorAll('button').forEach(function(b){b.remove();});return copy.textContent.trim();});save('bettor-'+talk.dataset.agent+'-conversation.txt','BETTOR COMMAND · '+talk.dataset.agent+'\nExported '+new Date().toISOString()+'\nVisible conversation only. Replies reference records at their answer time.\n\n'+rows.join('\n\n'));};
 // Copy the actual answer, not evidence panels or stale status messages.
 var log=talk.querySelector('.talk-log');function tools(){log.querySelectorAll('.talk-msg.a[data-mid]').forEach(function(row){if(row.querySelector('.talk-copy'))return;var b=document.createElement('button');b.type='button';b.className='talk-copy';b.textContent='Copy';b.onclick=async function(){try{await navigator.clipboard.writeText(row.querySelector('.body').innerText);b.textContent='Copied';}catch(e){b.textContent='Select text to copy';}setTimeout(function(){b.textContent='Copy';},2000);};row.querySelector('.meta').append(b);});}
 new MutationObserver(tools).observe(log,{childList:true});tools();
})();
"""
