"""Management office presentation over existing operations records.
No new reads, policy changes, orders, or synthesized recommendations.
"""
OFFICE_CSS = r"""
body.cc{--display:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;background:#080d15}
.office-heading{display:flex;justify-content:space-between;align-items:end;gap:18px;margin:28px 0 22px}.office-heading h1{font:650 clamp(28px,3vw,42px)/1.12 var(--display);letter-spacing:-.045em;margin:6px 0}.office-heading p{color:#9cafc3;margin:0;font-size:14px}.office-kicker{color:var(--acc);font-size:11px;letter-spacing:.17em;text-transform:uppercase}.office-heading a,.office-ask{border:1px solid #304355;border-radius:10px;padding:10px 14px;color:#d5e5f2;background:#142030;text-decoration:none;cursor:pointer;font:600 12px var(--display)}
.office-layout{display:grid;grid-template-columns:minmax(0,1fr) 370px;gap:24px;align-items:start}.office-board,.office-side{min-width:0}.office-side{position:sticky;top:80px;max-height:calc(100vh - 96px);overflow:auto;scrollbar-width:thin}.office-side .cc-hero{display:block;margin:0}.office-side .cc-stage{min-height:180px;height:180px;border-radius:18px 18px 0 0}.office-side .cc-ov{top:16px;left:18px}.office-side .cc-ov h1{font-size:28px}.office-side .cc-role{font-size:10px}.office-side .cc-cap{position:relative;font-size:10px}.office-side .cc-st{font-size:10px;padding:8px}.office-side .anim{display:none}.office-side .cc-placeholder{font-size:9px}.office-side #talk{margin:0;border-radius:0 0 18px 18px;border-color:#304355;padding:16px}.office-side .talk header{gap:5px}.office-side .talk header .key{display:none}.office-side .talk-ctl{margin:6px 0 0;width:100%}.office-side .talk-log{max-height:340px;min-height:120px}.office-side .talk-form{flex-direction:column;align-items:stretch}.office-side .talk-btns{justify-content:flex-end}.office-side .talk-note{font-size:11px}.office-side .talk-msg{font-size:14px}.office-side .talk-msg .meta{font-size:10px}.office-side .talk-ctl button{font-size:11px;padding:6px 8px}.office-side .talk-msg .body{line-height:1.65}
.office-status{padding:10px 14px;border:1px solid #273748;border-radius:10px;color:#a9becf;margin-bottom:16px;font-size:12px}.office-status.warn{border-color:#a06c27;color:#ffd38a}.office-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-bottom:18px}.office-metric{padding:15px;background:#101a27;border:1px solid #263444;border-radius:12px}.office-metric small{display:block;color:#96aabd;font-size:11px;margin-bottom:7px}.office-metric strong{font-size:21px;letter-spacing:-.02em;font-variant-numeric:tabular-nums}.office-card{scroll-margin-top:90px;background:linear-gradient(125deg,#122031,#0d1724);border:1px solid #293b4b;border-radius:16px;padding:20px;margin-bottom:16px;overflow-wrap:anywhere}.office-card header{display:flex;align-items:start;justify-content:space-between;gap:12px;margin-bottom:16px}.office-card h2{font:600 20px/1.3 var(--display);margin:5px 0}.office-card .event{color:#a6b8c9;font-size:12px}.office-badge{display:inline-block;border:1px solid #37505e;border-radius:6px;padding:4px 7px;font-size:10px;letter-spacing:.05em;color:#bbd2df}.office-badge.training{color:#e4c7ff;border-color:#654d82}.office-card .office-summary{margin:12px 0}.office-card .office-metric{padding:10px;background:#0a1420}.office-card .office-metric strong{font-size:16px}.office-plan{border-left:3px solid var(--acc);padding:12px 15px;background:#132333;border-radius:0 10px 10px 0;margin:14px 0}.office-plan strong{display:block;font-size:17px;margin:5px 0}.office-plan p,.office-note{font-size:12px;line-height:1.6;color:#afc1d0;margin:5px 0}.office-plan .stale{color:#ffcf80}.office-orders{width:100%;border-collapse:collapse;font-size:12px;margin:10px 0}.office-orders th{text-align:left;color:#8ea4b9;font-size:10px;font-weight:500;padding:8px}.office-orders td{padding:10px 8px;border-top:1px solid #233444}.office-orders-wrap{overflow:auto}.office-card details{font-size:12px;color:#9cb1c4;margin-top:14px}.office-card details pre{white-space:pre-wrap;max-height:260px;overflow:auto}.office-card footer{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:14px}.office-card footer time{font-size:11px;color:#8ea4b9}.office-advanced{margin-top:26px;border-top:1px solid #293b4b;padding-top:16px}.office-advanced>summary{color:#9fb5c9;cursor:pointer;font-size:13px;padding:10px 0}.office-empty{padding:30px 20px;border:1px dashed #34495c;border-radius:14px;color:#b3c4d4;line-height:1.7}.office-context{font-size:12px;padding:8px;border:1px solid var(--acc);border-radius:8px;margin-bottom:8px;color:#c8dfec}.office-context button{float:right}.office-response-mode{display:flex;align-items:center;gap:8px;font-size:11px;color:#a9bdcf;margin:8px 0}.office-response-mode select{background:#142131;color:#dae7f2;border:1px solid #34485c;border-radius:6px;padding:5px}.office-side .cc-stagewrap{margin:0}.office-board :focus-visible{outline:2px solid var(--acc);outline-offset:3px}
.office-talk-jump{display:none}
@media(max-width:780px){.office-talk-jump{display:block;position:fixed;right:14px;bottom:calc(14px + env(safe-area-inset-bottom));z-index:60;border:0;border-radius:999px;padding:12px 18px;font:600 14px/1 var(--display);color:#06121d;background:var(--acc,#7fd1ff);box-shadow:0 6px 22px rgba(0,0,0,.45)}.office-talk-jump.hidden{display:none}}
@media(max-width:1050px){.office-layout{grid-template-columns:minmax(0,1fr) 320px;gap:14px}.office-card{padding:14px}}
@media(max-width:780px){.office-layout{display:flex;flex-direction:column}.office-board,.office-side{width:100%}.office-side{position:static;max-height:none;overflow:visible}.office-heading{align-items:start;flex-direction:column}.office-heading a{white-space:nowrap}.office-heading h1{font-size:30px}.office-heading p{font-size:13px}.office-summary{gap:5px}.office-metric{padding:10px}.office-metric strong{font-size:17px}.office-card .office-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.office-card h2{font-size:18px}.office-side .cc-stage{height:260px;min-height:260px}.office-side .talk-log{max-height:50vh}body.cc main{padding-left:14px;padding-right:14px}.office-card footer{flex-wrap:wrap}}
"""
OFFICE_JS = r"""
(function(){
 'use strict';
 if(!window.CC||!CC.ops)return;
 var kind=document.body.dataset.kind, names={derek:'Derek',xavier:'Xavier',audrey:'Audrey'}, name=names[kind];if(!name)return;
 var main=document.getElementById('cc-main'),hero=main.querySelector('.cc-hero'),talk=document.getElementById('talk');
 var el=document.createElement('section');el.className='office-heading';
 el.innerHTML='<div><span class="office-kicker">Management office · '+name+'</span><h1>'+({derek:'Find the next opportunity.',xavier:'Every position. A clear plan.',audrey:'The account. The evidence. The next improvement.'}[kind])+'</h1><p>'+({derek:'Prices, fees and the reason behind each entry decision.',xavier:'Owned positions, working orders and the latest recorded exit decision.',audrey:'Reconciled performance and recommendations with accountable owners.'}[kind])+'</p></div><a href="#talk">Talk to '+name+' ↗</a>';
 hero.before(el);
 var layout=document.createElement('section');layout.className='office-layout';layout.innerHTML='<div class="office-board" aria-label="'+name+' workboard"><div id="office-status" class="office-status">Reading the recorded workspace…</div><div id="office-content"></div></div><aside class="office-side" aria-label="'+name+' office conversation"></aside>';
 el.after(layout);var side=layout.querySelector('aside');side.append(hero);side.append(talk);
 var advanced=document.createElement('details');advanced.className='office-advanced';advanced.innerHTML='<summary>All records, strategy detail and technical evidence</summary>';layout.after(advanced);
 var brief=hero.querySelector('.cc-brief');if(brief)advanced.append(brief);
 var node=advanced.nextElementSibling;while(node){var next=node.nextElementSibling;advanced.append(node);node=next;}
 var ctx=document.createElement('div');ctx.id='office-context';ctx.className='office-context';ctx.hidden=true;talk.querySelector('.talk-form').before(ctx);
 var note=talk.querySelector('.talk-note'),noteDetails=document.createElement('details');noteDetails.className='office-note';noteDetails.innerHTML='<summary>Conversation, memory & policy boundaries</summary>';note.before(noteDetails);noteDetails.append(note);var log=talk.querySelector('.talk-log');log.before(talk.querySelector('.talk-form'));
 var mode=document.createElement('label');mode.className='office-response-mode';mode.innerHTML='Answer style <select id="office-answer-style"><option value="brief">Conversational</option><option value="full">Full analysis</option></select>';talk.querySelector('.talk-form').before(ctx);talk.querySelector('.talk-form').before(mode);
 var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
 var num=function(v){return typeof v==='number'&&isFinite(v);},money=function(v){return num(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v):'Not recorded';};
 function human(v){return String(v||'Not recorded').replace(/_/g,' ').toLowerCase().replace(/^./,function(c){return c.toUpperCase();});}
 function data(s){return s&&(s.status==='OK'||s.status==='EMPTY')?s.data:null;}
 function list(s){var d=data(s);return Array.isArray(d)?d:[];}
 function metric(k,v){return '<div class="office-metric"><small>'+esc(k)+'</small><strong>'+esc(v)+'</strong></div>';}
 function time(v){var d=new Date(typeof v==='number'?v*1000:v);return v&&isFinite(d)?d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'not recorded';}
 function age(v){var t=typeof v==='number'?v*1000:Date.parse(v);return isFinite(t)?Math.max(0,(Date.now()-t)/1000):null;}
 function market(p){var m=p.market||{},l=p.label||{};return {name:m.selection||l.participant||p.participant||p.us_market_slug||'Position name unavailable',event:m.title||l.event||(p.us_market_slug?'Market '+p.us_market_slug:'Event name not recorded')};}
 function tag(s){return /EXPLORATION/.test(s||'')?'<span class="office-badge training">Training · simulated</span>':'<span class="office-badge">Simulated execution</span>';}
 function evidence(p){return '<details><summary>Decision evidence & identifiers</summary><pre>'+esc(JSON.stringify(p,null,2))+'</pre></details>';}
 function ask(p,q){return '<button class="office-ask" data-office-question="'+esc(q)+'">Ask '+name+' ↗</button>';}
 function orderTable(orders){return '<div class="office-orders-wrap"><table class="office-orders"><thead><tr><th>Standing order</th><th>Remaining</th><th>Limit</th><th>Status</th></tr></thead><tbody>'+orders.map(function(o){return '<tr><td>'+esc(human(o.role))+' · '+esc(human(o.direction))+'</td><td>'+esc(num(o.qty)&&num(o.filled_qty)?Math.max(0,o.qty-o.filled_qty):'Not recorded')+'</td><td>'+esc(money(o.limit_price))+'</td><td>'+esc(human(o.state))+'</td></tr>';}).join('')+'</tbody></table></div>';}
 function xavier(j){var ps=list(j.owned_positions).filter(function(p){return p.remaining&&p.remaining.open_qty>0;}),orders=list(j.standing_orders),ex=data(j.exposure)||{};
 var out='<div class="office-summary">'+metric('Positions in this view',data(j.owned_positions)!==null?ps.length:'Unavailable')+metric('Cost basis at risk',money(ex.cost_basis_at_risk_usd))+metric('Realized P&L',money(ex.realized_pnl_usd))+'</div>';
 if(!ps.length)return out+'<div class="office-empty">'+esc(j.owned_positions&&j.owned_positions.status==='UNAVAILABLE'?'Position read unavailable. This is not an empty portfolio.':'No open positions in this read. Filled positions appear here after handoff.')+'</div>';
 out+='<div class="office-card office-orders-wrap"><table class="office-orders"><thead><tr><th>Position</th><th>Marked value</th><th>Exit decision</th><th>Orders</th></tr></thead><tbody>'+ps.map(function(p){var r=p.remaining||{},rc=p.recommendation||{},reviewAge=age(rc.reviewed_at);return '<tr><td><a href="#office-pos-'+esc(p.group_id)+'">'+esc(market(p).name)+'</a></td><td>'+esc(money(r.marked_value_usd))+'</td><td>'+esc(human(rc.recommendation||'Awaiting review'))+(reviewAge===null||reviewAge>120?' · old / missing review':'')+'</td><td>'+esc(num(r.open_management_orders)?r.open_management_orders:'Unknown')+'</td></tr>';}).join('')+'</tbody></table></div>';
 return out+ps.map(function(p){var m=market(p),r=p.remaining||{},rc=p.recommendation||{},a=age(rc.reviewed_at),os=orders.filter(function(o){return o.group_id===p.group_id&&o.open===true;}),stale=a===null||a>120;
 return '<article class="office-card" id="office-pos-'+esc(p.group_id)+'" data-office-position="'+esc(p.group_id)+'"><header><div>'+tag(p.strategy)+'<h2>'+esc(m.name)+'</h2><div class="event">'+esc(m.event)+'</div></div><span class="office-badge">'+esc(r.open_qty)+' contracts</span></header><div class="office-summary">'+metric('Cost incl. fees',money(r.cost_basis_usd))+metric('Current marked value',money(r.marked_value_usd))+metric('Unrealized P&L',money(r.unrealized_pnl_usd))+'</div><div class="office-plan"><span class="office-kicker">Latest recorded exit decision</span><strong>'+esc(human(rc.recommendation||'Awaiting first review'))+'</strong><p>'+esc(rc.refusal_words||(rc.selection||{}).selection_reason||human(rc.refusal||rc.trigger||'No rationale recorded'))+'</p><p>Action: '+esc(human((rc.action||{}).taken||'No action recorded'))+'</p><p class="'+(stale?'stale':'')+'">Reviewed '+esc(time(rc.reviewed_at))+(stale?' · review older than 2 minutes or missing; refresh pending':' · last recorded decision, not a new quote')+'</p></div><b style="font-size:12px">Standing protection & exit orders · '+esc(num(r.open_management_orders)?r.open_management_orders:'not recorded')+'</b>'+(os.length?orderTable(os):'<p class="office-note">'+(r.open_management_orders===0?'No standing protection order recorded.': 'Order details unavailable in this read. Do not assume there is no protection.')+'</p>')+(num(r.open_management_orders)&&os.length<r.open_management_orders?'<p class="office-note">Showing '+os.length+' of '+r.open_management_orders+' working orders; full record below.</p>':'')+'<p class="office-note">Remaining ordinary-outcome P&L: win '+esc(money((r.ordinary_completion||{}).win_usd))+' / lose '+esc(money((r.ordinary_completion||{}).lose_usd))+'. Conditional scenarios, not locked profit.</p><footer>'+ask(p,'Explain your current exit plan, standing orders and remaining risk for '+m.name+'. Position group '+p.group_id+'.')+'<time>Latest review '+esc(time(rc.reviewed_at))+'</time></footer>'+evidence({group_id:p.group_id,review:rc,orders:os,exceptional_settlement:r.exceptional_settlement,exceptional_note:r.exceptional_note})+'</article>';}).join('');}
 function derek(j){var ss=j.strategies||[],rows=[];ss.forEach(function(s){list(s.recent).forEach(function(r){rows.push(Object.assign({},r,{office_policy_title:s.title||r.strategy,office_serving_version:s.version||null,office_historical:!!(s.version&&r.policy_version&&s.version!==r.policy_version)}));});});rows.sort(function(a,b){if(a.office_historical!==b.office_historical)return a.office_historical?1:-1;var av=num(a.edge_pp)?a.edge_pp:-Infinity,bv=num(b.edge_pp)?b.edge_pp:-Infinity;return bv-av;});var entries=list(j.standing_entry_orders);var working=entries.length?'<article class="office-card"><span class="office-kicker">Working entry orders</span>'+entries.map(function(o){var m=market(o);return '<h2>'+esc(m.name)+'</h2>'+orderTable([o]);}).join('')+'</article>':'';return working+'<div class="office-status">Closest recorded opportunities · serving policy versions first, then historical versions; ranked by gross edge within each group. These are recorded evaluations, not executable offers. Positive gross edge can still lose after fees.</div>'+(!rows.length?'<div class="office-empty">No opportunity records available in this read.</div>':rows.slice(0,12).map(function(r){var m=market(r),elapsed=age(r.decided_at);return '<article class="office-card" data-office-decision="'+esc(r.decision_id)+'"><header><div>'+tag(r.strategy)+'<h2>'+esc(m.name)+'</h2><div class="event">'+esc(m.event)+'</div></div><span class="office-badge">'+esc(human(r.verdict))+'</span></header><p class="office-note">'+esc(r.office_policy_title||'Strategy not recorded')+'<br>Recorded policy: <b>'+esc(r.policy_version||'Not recorded')+'</b>'+(r.office_historical?'<br><b>Historical policy version.</b> Its refusal uses the rules in effect at evaluation, not today’s rules.':'')+'</p><div class="office-summary">'+metric('Pinnacle estimate',num(r.p_pinnacle)?(r.p_pinnacle*100).toFixed(1)+'%':'Not recorded')+metric('Entry price',money(r.purchase_price))+metric('Gross edge',num(r.edge_pp)?r.edge_pp.toFixed(2)+' pp':'Not recorded')+'</div><div class="office-plan"><strong>'+esc(r.verdict==='ENTER'?'Entry approved by policy':r.refusal_words||human(r.refusal))+'</strong><p>'+esc(typeof r.explanation==='string'?r.explanation:'See the stored decision evidence below.')+'</p><p>Net expected profit '+esc(money(r.net_ev_usd))+' · Fees '+esc(money(r.fees_usd))+'</p></div><footer>'+ask(r,'Explain the price, fees, expected value and current status of '+m.name+'. Decision '+r.decision_id+'.')+'<time>Evaluated '+esc(time(r.decided_at))+(elapsed===null?' · age unknown':' · '+esc(Math.floor(elapsed/60))+' min ago')+'</time></footer>'+evidence(r)+'</article>';}).join(''));}
 function audrey(j){var recs=list(j.operational_audit),a=data(j.account)||{};return '<div class="office-summary">'+metric('Realized P&L',money(a.realized_pnl_usd))+metric('Unrealized P&L',money(a.unrealized_pnl_usd))+metric('Ledger',a.ledger_consistent===true?'Reconciled':a.ledger_consistent===false?'Needs attention':'Not recorded')+'</div>'+(!recs.length?'<div class="office-empty">No operational recommendations in this read. Audit findings and reports remain in All records below.</div>':recs.map(function(r){return '<article class="office-card"><header><div><span class="office-badge">'+esc(human(r.status))+'</span><h2>'+esc(human(r.kind||r.category))+'</h2></div><span class="office-badge">Owner · '+esc(r.owner_agent||'Not assigned')+'</span></header><p class="office-note">'+esc(r.recommendation||'Recommendation text not recorded')+'</p><div class="office-plan"><span class="office-kicker">Evidence → recommendation → measurement</span><p>Operational findings are not proof of improved profitability. Automated acknowledgements are not independent agent review.</p><p>Metric: '+esc(r.metric||'Not recorded')+' · baseline '+esc((r.baseline||{}).value==null?'Not recorded':r.baseline.value)+'</p>'+((r.events||[]).length?(r.events||[]).map(function(e){return '<p><b>'+esc(e.actor==='SYSTEM'?'Automated acknowledgement':e.actor)+' · '+esc(human(e.kind))+'</b><br>'+esc(e.body)+'</p>';}).join(''):'<p>No response or measurement recorded yet.</p>')+'</div><footer>'+ask(r,'Explain recommendation '+r.recommendation_id+', its evidence, genuine agent responses and subsequent measurements.')+'<time>'+esc(time(r.updated_at||r.created_at))+'</time></footer>'+evidence(r)+'</article>';}).join(''));}
 var lastMarkup='';
 function render(st){var status=document.getElementById('office-status'),j=st&&st.json;status.classList.toggle('warn',!!(st&&st.fail));status.textContent=st&&st.fail?'Read unavailable — '+(st.fail.why||st.fail.state||'connection error')+'. Last successful records retained.':j?'Connected to recorded workspace · refreshed '+time(st.okAt)+' · recommendations carry their own review times.':'Waiting for workspace records; no zero balance is assumed.';if(!j)return;var html=kind==='xavier'?xavier(j):kind==='derek'?derek(j):audrey(j);if(html!==lastMarkup){var content=document.getElementById('office-content'),open=[...content.querySelectorAll('details')].map(function(d,i){return d.open?i:-1;});content.innerHTML=html;open.forEach(function(i){if(i>=0&&content.querySelectorAll('details')[i])content.querySelectorAll('details')[i].open=true;});lastMarkup=html;}}
 document.addEventListener('click',function(e){var link=e.target.closest('a[href^="#"],#trace-btn');if(!link)return;var target=link.id==='trace-btn'?document.getElementById('trace'):document.getElementById(link.getAttribute('href').slice(1));if(target&&advanced.contains(target))advanced.open=true;});
 var original=CC.ops.panels;CC.ops.panels=function(k,st){var result=original(k,st);if(k===kind)render(st);return result;};
 layout.addEventListener('click',function(e){var b=e.target.closest('[data-office-question]');if(!b)return;var input=document.getElementById('talk-in');input.value=b.dataset.officeQuestion;ctx.hidden=false;ctx.textContent='Selected record attached to your question. Review it, then send.';input.focus();talk.scrollIntoView({behavior:'smooth',block:'nearest'});});
 // MOBILE: the conversation sits below the workboard; a fixed button reaches it.
 var jump=document.createElement('button');jump.type='button';jump.className='office-talk-jump';jump.textContent='Talk to '+name;jump.setAttribute('aria-label','Go to the conversation with '+name);
 jump.addEventListener('click',function(){talk.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(function(){var i=document.getElementById('talk-in');if(i)i.focus({preventScroll:true});},350);});
 document.body.append(jump);
 if('IntersectionObserver' in window){new IntersectionObserver(function(es){es.forEach(function(e){jump.classList.toggle('hidden',e.isIntersecting);});},{threshold:0.15}).observe(talk);}
 window.CCOffice={render:render};
})();
"""

# Progressive playback of the EXISTING authenticated streaming speech response.
# Text is still grounded and stored before it is spoken. No speculative tokens.
SPEECH_JS = r"""
window.CCStreamSpeech = async function(response, audio, signal, onStart) {
 var MS=window.MediaSource, url=null, reader=null, ms=null;
 var cleaned=false;var cleanup=function(){if(cleaned)return;cleaned=true;signal.removeEventListener('abort',cleanup);if(reader)reader.cancel().catch(function(){});audio.pause();audio.removeAttribute('src');audio.load();if(url)URL.revokeObjectURL(url);};
 signal.addEventListener('abort',cleanup,{once:true});
 try {
  if(!MS||!MS.isTypeSupported('audio/mpeg')||!response.body){
   var blob=await response.blob();if(signal.aborted)return;url=URL.createObjectURL(blob);audio.src=url;await audio.play();onStart(false);
   audio.addEventListener('ended',cleanup,{once:true});return;
  }
  ms=new MS();url=URL.createObjectURL(ms);audio.src=url;
  await new Promise(function(resolve,reject){ms.addEventListener('sourceopen',resolve,{once:true});signal.addEventListener('abort',function(){reject(new DOMException('Aborted','AbortError'));},{once:true});});
  if(signal.aborted)return;
  var sb=ms.addSourceBuffer('audio/mpeg'),started=false;reader=response.body.getReader();
  while(!signal.aborted){var part=await reader.read();if(part.done)break;if(!part.value.length)continue;
   await new Promise(function(resolve,reject){var off=function(){sb.removeEventListener('error',bad);sb.removeEventListener('updateend',done);signal.removeEventListener('abort',aborted);},done=function(){off();resolve();},bad=function(){off();reject(Error('Audio stream could not be decoded. Use replay or another browser.'));},aborted=function(){off();reject(new DOMException('Aborted','AbortError'));};signal.addEventListener('abort',aborted,{once:true});sb.addEventListener('updateend',done,{once:true});sb.addEventListener('error',bad,{once:true});try{sb.appendBuffer(part.value);}catch(e){off();reject(e);}});
   if(!signal.aborted&&!started&&sb.buffered.length){await audio.play();if(signal.aborted)return;started=true;onStart(true);}
  }
  if(!signal.aborted&&ms.readyState==='open')ms.endOfStream();
  audio.addEventListener('ended',cleanup,{once:true});
 } catch(e){cleanup();throw e;}
};
"""
