"""Management workbench for persistent plans, evidence and measured learning."""
CSS=r'''
.cap-panel{scroll-margin-top:110px;order:5;margin:22px 0;background:linear-gradient(135deg,#172b3c,#101d2b);border:1px solid #355269;border-radius:17px;padding:22px;color:#e7f0fa}.cap-panel h2{font:600 23px var(--display);letter-spacing:-.03em;margin:3px 0 8px}.cap-eyebrow{font:10px var(--mono);letter-spacing:.12em;color:#9cc6df}.cap-state,.cap-note{font:12px/1.6 var(--display);color:#a5bfd1}.cap-state[data-stale=true]{color:#ffd299}.cap-tabs{display:flex;gap:7px;flex-wrap:wrap;margin:16px 0}.cap-tabs button,.cap-panel button{font:12px var(--display);padding:9px 12px;border:1px solid #43647d;border-radius:8px;background:#152c40;color:#e5f3ff;cursor:pointer}.cap-tabs button[aria-selected=true]{background:#c2e8ff;color:#102030;border-color:#c2e8ff}.cap-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.cap-metric{background:#0e1b28;border:1px solid #2a4255;border-radius:10px;padding:13px}.cap-metric b{display:block;font:600 24px var(--display);margin-bottom:5px}.cap-card{border:1px solid #314c62;border-radius:11px;margin:9px 0;background:#101f2d;overflow:hidden}.cap-card summary{cursor:pointer;list-style:none;padding:14px;font:13px/1.5 var(--display);display:flex;gap:12px;justify-content:space-between}.cap-card summary small{flex-shrink:0;color:#a7c3d7;max-width:42%}.cap-detail{padding:0 15px 16px;font:12px/1.65 var(--display);overflow-wrap:anywhere}.cap-detail p{white-space:pre-wrap}.cap-tag{font:10px var(--mono);color:#b0d9ee}.cap-overdue{color:#ffd29a!important}.cap-panel pre{white-space:pre-wrap;overflow-wrap:anywhere;font:11px/1.6 var(--mono);max-height:360px;overflow:auto;background:#0b1825;border-radius:8px;padding:12px}.cap-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:15px 0}.cap-panel label{display:block;font:12px var(--display);margin-top:12px}.cap-panel input,.cap-panel textarea,.cap-panel select{display:block;width:100%;box-sizing:border-box;margin-top:5px;background:#0b1b29;color:#e6f3fc;border:1px solid #436078;border-radius:8px;padding:11px;font:14px var(--display)}.cap-panel textarea{min-height:90px}.cap-footer{font:10px/1.6 var(--display);color:#90aec3;border-top:1px solid #31495e;margin-top:18px;padding-top:12px}.cap-empty{padding:20px 0;color:#b2c4d2}.cap-columns{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:800px){.cap-panel{padding:16px}.cap-grid{grid-template-columns:1fr 1fr}.cap-columns{grid-template-columns:1fr}.cap-panel input,.cap-panel textarea,.cap-panel select{font-size:16px}.cap-card summary{display:block}.cap-card summary small{display:block;margin-top:6px;max-width:none}}
'''

JS=r'''
(function(){
 'use strict';
 var board=document.querySelector('.office-board');if(!board)return;
 var who=(document.body.dataset.kind||'derek').toUpperCase(),base='/api/command/agents/capabilities';
 var panel=document.createElement('section');panel.className='cap-panel';panel.id='agent-capabilities';panel.setAttribute('aria-label','Agent work and improvement');
 panel.innerHTML='<div class="cap-eyebrow">THE LEARNING WORKBENCH</div><h2>Work. Investigate. Improve.</h2><div class="cap-state" role="status">Reading the capability record…</div><div class="cap-tabs" role="tablist" aria-label="Capabilities"></div><div class="cap-body"></div><div class="cap-footer">Research reviews are attributed opinions backed by recorded evidence. Completed reviews are not proven performance gains. Policy activation remains separately controlled.</div>';
 board.append(panel);
 var heading=document.querySelector('.office-heading');if(heading){var jump=document.createElement('a');jump.href='#agent-capabilities';jump.className='btn office-cap-link';jump.textContent='Work & learning ↘';heading.append(jump);}
 panel.querySelector('.cap-body').setAttribute('role','tabpanel');
 var tabs=['Plans','Collaboration','Investigate','Intelligence','Experiments','Scorecard'],tab='Plans',last=null,inflight=false,goalKey=null;
 var state=panel.querySelector('.cap-state'),body=panel.querySelector('.cap-body');
 function esc(v){return String(v==null?'Not recorded':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
 function when(v){var d=typeof v==='number'?new Date(v*1000):new Date(v);return v&&Number.isFinite(d.getTime())?d.toLocaleString():'Not recorded';}
 function empty(s){return '<p class="cap-empty">'+esc(s)+'</p>';}
 function pretty(o){return '<pre>'+esc(JSON.stringify(o,null,2))+'</pre>';}
 function metric(n,label){return '<div class="cap-metric"><b>'+esc(n==null?'—':n)+'</b>'+esc(label)+'</div>';}
 tabs.forEach(function(name){var b=document.createElement('button');b.type='button';b.role='tab';b.textContent=name;b.setAttribute('aria-selected',String(name===tab));b.onclick=function(){tab=name;panel.querySelectorAll('[role=tab]').forEach(function(x){x.setAttribute('aria-selected',String(x.textContent===tab));});render();};panel.querySelector('.cap-tabs').append(b);});
 panel.querySelector('.cap-tabs').addEventListener('keydown',function(e){var bs=Array.from(this.querySelectorAll('button')),i=bs.indexOf(e.target);if(i<0)return;var n=e.key==='ArrowRight'?(i+1)%bs.length:e.key==='ArrowLeft'?(i+bs.length-1)%bs.length:e.key==='Home'?0:e.key==='End'?bs.length-1:null;if(n!==null){e.preventDefault();bs[n].focus();bs[n].click();}});
 function workCard(t){var o=t.outcome||{},s=t.spec||{},done=o.reviewed===true;return '<details class="cap-card" data-cap-task="'+esc(t.task_id)+'"><summary><span>'+esc(t.title)+'</span><small class="'+(t.overdue?'cap-overdue':'')+'">'+esc(t.assignee)+' · '+esc(done?'Reviewed':t.status.replaceAll('_',' '))+(t.overdue?' · Overdue':'')+'</small></summary><div class="cap-detail"><div class="cap-tag">'+esc(t.task_id)+'</div><p>Due '+esc(when(s.due_at))+' · Priority '+esc(s.priority)+'</p><p>'+esc(s.next_action)+'</p><p>Dependencies: '+esc((s.dependencies||[]).join(', ')||'None')+'</p>'+(done?'<p>'+esc(o.answer)+'</p><p>Model response '+esc(o.message_id)+' · '+esc((o.source_ids||[]).join(', '))+'</p>':o.error?'<p>Last attempt: '+esc(o.error)+'</p>':'')+(t.assignee===who?'<button type="button" data-cap-ask="'+esc(t.task_id)+'">Discuss this work ↗</button>':'')+'</div></details>';}
 function goalForm(){return '<details class="cap-card"><summary>Assign a research goal <small>Management control access</small></summary><form id="cap-goal" class="cap-detail"><label>Your name<input name="actor" required maxlength="100" autocomplete="name"></label><label>What should the team investigate?<textarea name="title" required maxlength="500" placeholder="Explain a recurring refusal and propose a measurable test."></textarea></label><div class="cap-columns"><label>First reviewer<select name="first">'+['DEREK','XAVIER','AUDREY'].map(function(a){return '<option '+(a===who?'selected':'')+'>'+a+'</option>';}).join('')+'</select></label><label>Priority<select name="priority"><option value="3">Normal</option><option value="4">High</option><option value="5">Urgent</option><option value="2">Low</option></select></label></div><label>Due within 30 days<input name="due" type="datetime-local" required></label><div class="cap-actions"><button type="submit">Create team work plan</button><span class="cap-note" role="status" id="cap-submit"></span></div><p class="cap-note">Creates one linked review per agent. It grants no trading authority.</p></form></details>';}
 function controlForm(){return '<details class="cap-card"><summary>Research schedule <small>Management control access</small></summary><form id="cap-control" class="cap-detail"><label>Your name<input name="actor" required maxlength="100"></label><div class="cap-columns"><label>Research worker<select name="enabled"><option value="true" '+(last.control.enabled?'selected':'')+'>Enabled</option><option value="false" '+(!last.control.enabled?'selected':'')+'>Paused</option></select></label><label>Maximum model requests per hour<input name="hourly_limit" type="number" min="1" max="120" value="'+esc(last.control.hourly_limit)+'" required></label></div><p class="cap-note">Applies to additional research reviews. Existing position management and operational audits keep their own schedules. Already-running read-only reviews may finish.</p><button type="submit">Save research schedule</button><p id="cap-control-state" role="status"></p></form></details>';}
 function bindControl(){var f=body.querySelector('#cap-control');f.oninput=function(){f.dataset.dirty='true';};f.onsubmit=async function(e){e.preventDefault();var b=f.querySelector('button'),s=f.querySelector('#cap-control-state');b.disabled=true;try{await request(base+'/control',{actor:f.actor.value,enabled:f.enabled.value==='true',hourly_limit:Number(f.hourly_limit.value)});s.textContent='Research schedule saved.';await load(false);}catch(err){s.textContent=err.message;}finally{b.disabled=false;}};}

 var intelResult=null,intelChoice='missed_opportunities',intelGroup='',intelGeneration=0;
 var intelNames={missed_opportunities:'Missed opportunities',cross_venue:'Cross-venue alternatives',forecast_evaluation:'Forecast evaluation',connector_health:'Connector health'};
 function intelligenceView(){
   body.innerHTML='<p class="cap-note">Recorded evidence for management and agent research. Comparisons do not place orders or activate policies.</p><form id="cap-intelligence"><label>Report<select name="report">'+Object.keys(intelNames).map(function(k){return '<option value="'+k+'" '+(k===intelChoice?'selected':'')+'>'+intelNames[k]+'</option>';}).join('')+'</select></label><label>Position group ID (cross-venue report only)<input name="group" maxlength="150" value="'+esc(intelGroup)+'"></label><button type="submit">Read report</button></form><div id="cap-intel-result" aria-live="polite"></div>';
   var f=body.querySelector('#cap-intelligence');
   f.onchange=function(){intelChoice=f.report.value;intelGroup=f.group.value;f.dataset.dirty='true';++intelGeneration;};
   f.onsubmit=async function(e){e.preventDefault();var gen=++intelGeneration;intelChoice=f.report.value;intelGroup=f.group.value;var box=body.querySelector('#cap-intel-result');box.textContent='Reading recorded evidence…';try{var j=await request(base+'/tools/'+encodeURIComponent(intelChoice)+'?agent='+who+(intelGroup?'&record_id='+encodeURIComponent(intelGroup):''));if(gen!==intelGeneration||tab!=='Intelligence'||!box.isConnected)return;intelResult=j;paintIntelligence(box,j);}catch(err){if(gen===intelGeneration&&box.isConnected){box.textContent='Report unavailable: '+err.message;}}};
   if(intelResult)paintIntelligence(body.querySelector('#cap-intel-result'),intelResult);
 }
 function paintIntelligence(box,j){
   var d=j.data||{},summary='';
   if(j.status!=='OK'){box.textContent='Report unavailable: '+String(j.why||j.status);return;}
   if(d.status==='UNAVAILABLE'||d.status==='NO_EVIDENCE'){box.textContent='No report evidence: '+String(d.reason||d.status);return;}
   if(j.tool==='missed_opportunities')summary=metric(d.distinct_candidate_keys,'Distinct candidate keys')+metric(d.latest_refused_before_valuation,'Latest state refused')+metric(d.unidentified_rows,'Rows missing identity');
   if(j.tool==='forecast_evaluation'){var cs=d.cohorts||[];summary=metric(cs.length,'Separate forecast cohorts')+metric(cs.reduce(function(n,x){return n+x.n_resolved;},0),'Resolved forecasts')+metric(cs.reduce(function(n,x){return n+x.n_pending;},0),'Pending outcomes');}
   if(j.tool==='cross_venue')summary=metric((d.actions||[]).filter(function(x){return x.status==='COMPARABLE';}).length,'Comparable recorded alternatives')+metric(d.best_recorded_action_or_hold||'—','Research comparison')+metric('Not guaranteed','Execution');
   if(j.tool==='connector_health')summary=metric(d.status,'Telemetry status')+metric(d.heartbeat_age_s==null?'—':Math.round(d.heartbeat_age_s)+'s','Heartbeat age')+metric((d.recorded_valuation_contributions||[]).length,'Provider/version cohorts');
   box.innerHTML='<p class="cap-note">'+esc(intelNames[j.tool]||j.tool)+' · read '+esc(when(j.read_at))+'</p><div class="cap-grid">'+summary+'</div><p class="cap-note">'+esc(d.reason||d.limitation||'No execution authority.')+'</p>'+(d.sample&&d.sample.truncated?'<p class="cap-note">Bounded sample: latest '+esc(d.sample.rows)+' rows. These are not population totals.</p>':'')+'<details class="cap-card"><summary>Evidence, source IDs and denominators</summary><div class="cap-detail">'+pretty(d)+'</div></details><button type="button" data-intel-download>Download report</button>';
   box.querySelector('[data-intel-download]').onclick=function(){var u=URL.createObjectURL(new Blob([JSON.stringify(j,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='bettor-'+j.tool+'-evidence.json';a.click();setTimeout(function(){URL.revokeObjectURL(u);},1000);};
 }
 function render(){
   if(!last){body.innerHTML=empty('No capability read is available yet.');return;}
   var work=last.work||[],own=work.filter(function(t){return t.assignee===who;});
   var open=new Set(Array.from(body.querySelectorAll('details[open][data-cap-task]')).map(function(x){return x.dataset.capTask;}));
   if(tab==='Plans'){body.innerHTML='<p class="cap-note">'+esc(last.control.enabled?'Research worker enabled':'Research worker paused')+' · '+esc(last.control.hourly_limit)+' model calls per hour maximum. Latest '+esc(last.work_limit)+' team tasks shown.</p>'+goalForm()+controlForm()+(own.length?own.map(workCard).join(''):empty('No research plan has been assigned to this agent.'));bindGoal();bindControl();}
   if(tab==='Collaboration'){body.innerHTML='<p class="cap-note">Recorded event → first reviewer → peer review → final review. Waiting work stays blocked until its dependencies have genuine, grounded responses.</p>'+(work.length?work.map(workCard).join(''):empty('No recorded collaboration yet.'))+'<p class="cap-note">Slack transport delivery is tracked by the receiver, separately from these canonical work records.</p>';}
   if(tab==='Intelligence')intelligenceView();
   if(tab==='Investigate'){body.innerHTML='<p class="cap-note">Evidence tools read persisted records from this experiment. They do not send venue orders. Source timestamps determine freshness.</p><form id="cap-tool"><label>Evidence tool<select name="tool">'+last.tool_names.map(function(t){return '<option>'+esc(t)+'</option>';}).join('')+'</select></label><label>Record ID, when required<input name="record" maxlength="150" placeholder="Position, decision or recommendation ID"></label><div class="cap-actions"><button type="submit">Read evidence</button></div></form><div id="cap-tool-result" role="status"></div>';body.querySelector('#cap-tool').onsubmit=async function(e){e.preventDefault();var f=e.target,r=body.querySelector('#cap-tool-result'),b=f.querySelector('button');b.disabled=true;r.textContent='Reading evidence…';try{var url=base+'/tools/'+encodeURIComponent(f.tool.value)+'?agent='+who+(f.record.value?'&record_id='+encodeURIComponent(f.record.value):'');r.innerHTML=pretty(await request(url));}catch(err){r.textContent='Evidence unavailable: '+err.message;}finally{b.disabled=false;}};}
   if(tab==='Experiments'){var ps=last.experiments||[];body.innerHTML='<p class="cap-note">Prospective hypotheses use the existing evaluator. The training period precedes the evaluation period. Missing outcomes remain insufficient evidence.</p>'+(ps.length?ps.map(function(p){return '<details class="cap-card"><summary>'+esc(p.rationale)+'<small>'+esc(p.status)+'</small></summary><div class="cap-detail"><div class="cap-tag">'+esc(p.proposal_id)+'</div><p>'+esc(p.agent_id)+' · '+esc(p.strategy)+'</p><p>Training: '+esc(when(p.training_start))+' → '+esc(when(p.training_end))+'<br>Evaluation: '+esc(when(p.evaluation_start))+' → '+esc(when(p.evaluation_end))+'</p>'+pretty({protocol:p.protocol,verdict:p.verdict,evaluation:p.evaluation,last_attempt:p.last_attempt})+'</div></details>';}).join(''):empty('No registered experiment yet. Nothing is reported as improved without forward outcomes.'))+'<details class="cap-card"><summary>Register a forward experiment <small>Management control access</small></summary><form id="cap-experiment" class="cap-detail"><label>Your name<input name="actor" required maxlength="100"></label><label>What should improve, and why?<textarea name="rationale" required minlength="10" maxlength="2000" placeholder="State a measurable hypothesis, not a promised gain."></textarea></label><label>Comparison<select name="change_class"><option value="DEREK_ENTRY_EDGE_THRESHOLD">Derek · entry edge threshold</option><option value="XAVIER_EXIT_WHEN_MEASURE_STALE">Xavier · stale-measure exit counterfactual</option></select></label><div class="cap-columns" id="cap-edge-values"><label>Baseline edge (percentage points)<input name="from_pp" type="number" min="0.5" max="6" step="0.5" value="0.5"></label><label>Candidate edge (percentage points)<input name="to_pp" type="number" min="0.5" max="6" step="0.5" value="1"></label></div><div class="cap-columns"><label>Training starts<input name="training_start" type="datetime-local" required></label><label>Training ends<input name="training_end" type="datetime-local" required></label><label>Evaluation starts (future)<input name="evaluation_start" type="datetime-local" required></label><label>Evaluation ends<input name="evaluation_end" type="datetime-local" required></label></div><label>Minimum outcomes<input name="min_outcomes" type="number" min="10" max="10000" value="10" required></label><p class="cap-note">Use the existing registered policy classes and bounds. Registration does not activate a policy.</p><button type="submit">Register protocol</button><p id="cap-experiment-state" role="status"></p></form></details>';bindExperiment();}
   if(tab==='Scorecard'){var s=last.scorecards,k=s[who.toLowerCase()];body.innerHTML='<p class="cap-note">'+esc(when(s.window.start))+' → '+esc(when(s.window.end))+' · each operational series is capped at 500 latest records; limits are disclosed below.</p><div class="cap-grid">'+(who==='DEREK'?metric(k.decisions,'Decisions read')+metric(k.entries.numerator,'Entry decisions')+metric(k.entries.denominator,'Decision denominator'):who==='XAVIER'?metric(k.reviews,'Reviews read')+metric(k.stale_measures.numerator,'Stale measures')+metric(k.missing_measures,'Missing measures'):metric(k.findings,'Findings read')+metric(k.critical_findings,'Critical findings')+metric(k.genuine_reviews_in_visible_work,'Team research reviews'))+'</div>'+pretty(k)+'<p class="cap-note">'+esc(s.forecast_quality.why)+'</p><p class="cap-note">'+esc(s.improvement_claim)+'</p><button type="button" id="cap-export">Download capability record ↓</button>';body.querySelector('#cap-export').onclick=function(){var u=URL.createObjectURL(new Blob([JSON.stringify(last,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='bettor-'+who.toLowerCase()+'-capabilities.json';a.click();setTimeout(function(){URL.revokeObjectURL(u);},1000);};}
   open.forEach(function(id){var el=Array.from(body.querySelectorAll('[data-cap-task]')).find(function(e){return e.dataset.capTask===id;});if(el)el.open=true;});
 }
 async function request(url,data){var c=new AbortController(),timer=setTimeout(function(){c.abort();},10000);try{var r=await fetch(url,{method:data?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:c.signal,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined}),j=await r.json();if(!r.ok)throw new Error(r.status===403?'Management control access is required':String(j.detail||r.status));return j;}finally{clearTimeout(timer);}}
 function key(){return 'cap-ui-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);}
 function bindGoal(){var f=body.querySelector('#cap-goal');f.oninput=function(){goalKey=null;f.dataset.dirty='true';};f.onsubmit=async function(e){e.preventDefault();var b=f.querySelector('button'),s=f.querySelector('#cap-submit');b.disabled=true;goalKey=goalKey||key();try{var r=await request(base+'/goals',{request_id:goalKey,actor:f.actor.value,title:f.elements.title.value,first:f.first.value,priority:Number(f.priority.value),due_at:new Date(f.due.value).getTime()/1000});s.textContent='Plan saved · '+r.task_ids.length+' linked reviews';goalKey=null;await load(false);}catch(err){s.textContent=err.message+'; retry uses the same request ID.';}finally{b.disabled=false;}};}
 function bindExperiment(){var f=body.querySelector('#cap-experiment'),id=null;f.oninput=function(){id=null;f.dataset.dirty='true';};var bounds=last.experiment_catalog.parameter_bounds.min_gross_edge_pp;['from_pp','to_pp'].forEach(function(n){f.elements[n].min=bounds[0];f.elements[n].max=bounds[1];f.elements[n].step=last.experiment_catalog.parameter_grid_pp;});f.change_class.onchange=function(){var cls=last.experiment_catalog.classes[f.change_class.value];f.min_outcomes.min=cls.min_evaluation_outcomes;f.min_outcomes.value=Math.max(Number(f.min_outcomes.value),cls.min_evaluation_outcomes);body.querySelector('#cap-edge-values').hidden=f.change_class.value!=='DEREK_ENTRY_EDGE_THRESHOLD';};f.onsubmit=async function(e){e.preventDefault();var b=f.querySelector('button'),s=f.querySelector('#cap-experiment-state');b.disabled=true;try{id=id||key();var data={request_id:id,actor:f.actor.value,change_class:f.change_class.value,strategy:last.experiment_catalog.parameter_policy,rationale:f.rationale.value,training:[new Date(f.training_start.value).getTime()/1000,new Date(f.training_end.value).getTime()/1000],evaluation:[new Date(f.evaluation_start.value).getTime()/1000,new Date(f.evaluation_end.value).getTime()/1000],min_outcomes:Number(f.min_outcomes.value),change:f.change_class.value==='DEREK_ENTRY_EDGE_THRESHOLD'?{parameter:'min_gross_edge_pp',from:Number(f.from_pp.value),to:Number(f.to_pp.value)}:{action:'COUNTERFACTUAL_EXIT_AT_RECORDED_BOOK'}};var r=await request(base+'/experiments',data);s.textContent='Registered '+r.proposal_id+'; awaiting forward evidence.';await load(false);}catch(err){s.textContent=err.message;}finally{b.disabled=false;}};}
 panel.addEventListener('click',function(e){var b=e.target.closest('[data-cap-ask]');if(!b)return;var talk=document.getElementById('talk'),input=document.getElementById('talk-in');talk.dataset.capabilityTask=b.dataset.capAsk;input.value='Explain the evidence, peer reviews and next step for this research task: '+b.dataset.capAsk;var launcher=document.querySelector('.desk-mobile-talk');if(launcher&&getComputedStyle(launcher).display!=='none')launcher.click();talk.scrollIntoView({block:'center',behavior:'smooth'});input.focus();});
 async function load(paint){if(inflight||document.hidden)return;inflight=true;try{var j=await request(base);if(j.status!=='OK')throw new Error('Capability record unavailable');last=j;state.dataset.stale='false';state.textContent='Records read '+when(j.read_at)+' · '+(j.control.enabled?'Research enabled':'Research paused');if(paint!==false&&!body.querySelector('form:focus-within,form[data-dirty=true]'))render();}catch(e){state.dataset.stale='true';state.textContent=(last?'Read failed — retaining records from '+when(last.read_at):'Capability read unavailable')+'. '+e.message;if(!last)render();}finally{inflight=false;}}
 window.CCCapabilities={refresh:function(){return load(true);}};
 load(true);setInterval(function(){load(true);},60000);document.addEventListener('visibilitychange',function(){if(!document.hidden)load(true);});
})();
'''
