"""Management office presentation over existing operations records.
No new reads, policy changes, orders, or synthesized recommendations.
"""
OFFICE_CSS = r"""
body.cc{--display:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;background:#080d15}
.office-heading{display:flex;justify-content:space-between;align-items:end;gap:18px;margin:28px 0 22px}.office-heading h1{font:650 clamp(28px,3vw,42px)/1.12 var(--display);letter-spacing:-.045em;margin:6px 0}.office-heading p{color:#9cafc3;margin:0;font-size:14px}.office-kicker{color:var(--acc);font-size:11px;letter-spacing:.17em;text-transform:uppercase}.office-heading a,.office-ask{border:1px solid #304355;border-radius:10px;padding:10px 14px;color:#d5e5f2;background:#142030;text-decoration:none;cursor:pointer;font:600 12px var(--display)}
.office-layout{display:grid;grid-template-columns:minmax(0,1fr) 370px;gap:24px;align-items:start}.office-board,.office-side{min-width:0}.office-side{position:sticky;top:80px;max-height:calc(100vh - 96px);overflow:auto;scrollbar-width:thin}.office-side .cc-hero{display:block;margin:0}.office-side .cc-stage{min-height:180px;height:180px;border-radius:18px 18px 0 0}.office-side .cc-ov{top:16px;left:18px}.office-side .cc-ov h1{font-size:28px}.office-side .cc-role{font-size:10px}.office-side .cc-cap{position:relative;font-size:10px}.office-side .cc-st{font-size:10px;padding:8px}.office-side .anim{display:none}.office-side .cc-placeholder{font-size:9px}.office-side #talk{margin:0;border-radius:0 0 18px 18px;border-color:#304355;padding:16px}.office-side .talk header{gap:5px}.office-side .talk header .key{display:none}.office-side .talk-ctl{margin:6px 0 0;width:100%}.office-side .talk-log{max-height:340px;min-height:120px}.office-side .talk-form{flex-direction:column;align-items:stretch}.office-side .talk-btns{justify-content:flex-end}.office-side .talk-note{font-size:11px}.office-side .talk-msg{font-size:14px}.office-side .talk-msg .meta{font-size:10px}.office-side .talk-ctl button{font-size:11px;padding:6px 8px}.office-side .talk-msg .body{line-height:1.65}
.office-status{padding:10px 14px;border:1px solid #273748;border-radius:10px;color:#a9becf;margin-bottom:16px;font-size:12px}.office-status.warn{border-color:#a06c27;color:#ffd38a}.office-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-bottom:18px}.office-metric{padding:15px;background:#101a27;border:1px solid #263444;border-radius:12px}.office-metric small{display:block;color:#96aabd;font-size:11px;margin-bottom:7px}.office-metric strong{font-size:21px;letter-spacing:-.02em;font-variant-numeric:tabular-nums}.office-card{scroll-margin-top:90px;background:linear-gradient(125deg,#122031,#0d1724);border:1px solid #293b4b;border-radius:16px;padding:20px;margin-bottom:16px;overflow-wrap:anywhere}.office-card header{display:flex;align-items:start;justify-content:space-between;gap:12px;margin-bottom:16px}.office-card h2{font:600 20px/1.3 var(--display);margin:5px 0}.office-card .event{color:#a6b8c9;font-size:12px}.office-badge{display:inline-block;border:1px solid #37505e;border-radius:6px;padding:4px 7px;font-size:10px;letter-spacing:.05em;color:#bbd2df}.office-badge.training{color:#e4c7ff;border-color:#654d82}.office-card .office-summary{margin:12px 0}.office-card .office-metric{padding:10px;background:#0a1420}.office-card .office-metric strong{font-size:16px}.office-plan{border-left:3px solid var(--acc);padding:12px 15px;background:#132333;border-radius:0 10px 10px 0;margin:14px 0}.office-plan strong{display:block;font-size:17px;margin:5px 0}.office-plan p,.office-note{font-size:12px;line-height:1.6;color:#afc1d0;margin:5px 0}.office-plan .stale{color:#ffcf80}.office-orders{width:100%;border-collapse:collapse;font-size:12px;margin:10px 0}.office-orders th{text-align:left;color:#8ea4b9;font-size:10px;font-weight:500;padding:8px}.office-orders td{padding:10px 8px;border-top:1px solid #233444}.office-orders-wrap{overflow:auto}.office-card details{font-size:12px;color:#9cb1c4;margin-top:14px}.office-card details pre{white-space:pre-wrap;max-height:260px;overflow:auto}.office-card footer{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:14px}.office-card footer time{font-size:11px;color:#8ea4b9}.office-advanced{margin-top:26px;border-top:1px solid #293b4b;padding-top:16px}.office-advanced>summary{color:#9fb5c9;cursor:pointer;font-size:13px;padding:10px 0}.office-empty{padding:30px 20px;border:1px dashed #34495c;border-radius:14px;color:#b3c4d4;line-height:1.7}.office-context{font-size:12px;padding:8px;border:1px solid var(--acc);border-radius:8px;margin-bottom:8px;color:#c8dfec}.office-context button{float:right}.office-response-mode{display:flex;align-items:center;gap:8px;font-size:11px;color:#a9bdcf;margin:8px 0}.office-response-mode select{background:#142131;color:#dae7f2;border:1px solid #34485c;border-radius:6px;padding:5px}.office-side .cc-stagewrap{margin:0}.office-board :focus-visible{outline:2px solid var(--acc);outline-offset:3px}
.office-talk-jump{display:none}
@media(max-width:780px){.office-talk-jump{display:block;position:fixed;right:14px;bottom:calc(14px + env(safe-area-inset-bottom));z-index:60;border:0;border-radius:999px;padding:12px 18px;font:600 14px/1 var(--display);color:#06121d;background:var(--acc,#7fd1ff);box-shadow:0 6px 22px rgba(0,0,0,.45)}.office-talk-jump.hidden{display:none}}
@media(max-width:1050px){.office-layout{grid-template-columns:minmax(0,1fr) 320px;gap:14px}.office-card{padding:14px}}
@media(max-width:780px){.office-layout{display:flex;flex-direction:column}.office-board,.office-side{width:100%}.office-side{position:static;max-height:none;overflow:visible}.office-heading{align-items:start;flex-direction:column}.office-heading a{white-space:nowrap}.office-heading h1{font-size:30px}.office-heading p{font-size:13px}.office-summary{gap:5px}.office-metric{padding:10px}.office-metric strong{font-size:17px}.office-card .office-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.office-card h2{font-size:18px}.office-side .cc-stage{height:260px;min-height:260px}.office-side .talk-log{max-height:50vh}body.cc main{padding-left:14px;padding-right:14px}.office-card footer{flex-wrap:wrap}}
/* Management reading hierarchy: compact work rows, details on demand. */
body.cc{background:radial-gradient(ellipse at 80% -20%,#152638 0,transparent 50%),#080d15}
body.cc main{max-width:1480px;padding:22px 36px 50px}
.office-heading{margin:8px 0 26px;align-items:center}.office-heading h1{font-size:38px;letter-spacing:-.045em}.office-heading p{font-size:14px}.office-kicker{font-family:var(--display);font-weight:600;letter-spacing:.14em}
.office-layout{grid-template-columns:minmax(0,1fr) 332px;gap:26px}.office-side{border:1px solid #2a3b4b;background:#0d1722;border-radius:20px;top:84px;max-height:calc(100vh - 100px)}
.office-side .cc-hero{padding:14px 14px 0}.office-side .cc-stage{min-height:156px;height:156px;border-radius:14px}.office-side .cc-ov{display:flex;align-items:center;gap:10px}.office-side .cc-ov h1{font:600 18px var(--display);margin:0}.office-side .cc-role{display:none}.office-side .cc-ai{font-size:8px}.office-side .cc-cap{font-size:8px;gap:4px}.office-side .cc-st{border:0;background:none;padding:4px 0}.office-side #cc-hb{font-size:9px}.office-side #talk{border:0;padding:12px 14px 16px;background:none}.office-side #talk header h3{font-size:16px}.office-side .talk-log{min-height:80px;max-height:200px}.office-side .talk-ctl{margin-top:0}.office-side .talk-empty{font-size:12px;margin-top:10px}.office-side .talk-form textarea{min-height:66px;height:66px}.office-side .office-note{font-size:10px}.office-side .talk-sugg{font-size:11px}
.office-status{border:0;border-bottom:1px solid #253746;background:none;border-radius:0;margin:0 0 18px;padding:0 0 12px;font-size:11px;display:flex;align-items:center;justify-content:space-between;gap:14px;color:#a1b7c9}.office-status.warn{color:#ffce80}.office-status .health-light{width:6px;height:6px;display:inline-block;margin-right:7px;border-radius:50%;background:#8cadbe}.office-status.warn .health-light{background:#f1b862}.office-summary{gap:0;border:1px solid #2a3b4b;border-radius:16px;background:linear-gradient(110deg,#142537,#0e1b28);overflow:hidden;margin-bottom:26px}.office-metric{border:0;border-radius:0;background:none;padding:20px 24px}.office-metric+.office-metric{border-left:1px solid #2a3b4b}.office-metric strong{font-size:30px;letter-spacing:-.04em;font-weight:600}.office-metric small{font-size:11px}
.work-heading{display:flex;justify-content:space-between;align-items:end;gap:20px;margin:0 0 14px}.work-heading h2{margin:5px 0 0;font:600 22px/1.2 var(--display);letter-spacing:-.03em}.work-heading p{max-width:290px;margin:0;color:#91a7ba;font-size:11px;line-height:1.5}.work-heading .office-kicker{font-size:9px;color:var(--acc)}
.work-list{border:1px solid #2b3c4b;border-radius:16px;overflow:hidden;background:#101b28}.work-item{background:#101b28;scroll-margin-top:96px;margin:0;border:0;overflow-wrap:anywhere}.work-item+.work-item{border-top:1px solid #263848}.work-item>summary{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(92px,.65fr) minmax(125px,1fr) 14px;align-items:center;gap:14px;padding:19px 20px;cursor:pointer;list-style:none;transition:background .15s}.work-item>summary::-webkit-details-marker{display:none}.work-item>summary:hover,.work-item[open]>summary{background:#172739}.work-item>summary:focus-visible{outline:2px solid var(--acc);outline-offset:-3px}.work-name{display:flex;align-items:center;gap:12px;min-width:0}.work-avatar{display:grid;place-items:center;flex:0 0 34px;height:34px;border:1px solid #385265;background:#20384a;color:#c2e2f5;font:600 10px var(--display);border-radius:10px}.work-name h3{font:600 15px/1.35 var(--display);letter-spacing:-.02em;margin:0 0 4px;color:#edf4fb}.work-name p{font-size:10px;line-height:1.5;color:#90a8bc;margin:0 0 5px}.office-badge{font-size:8px;letter-spacing:.03em;padding:2px 5px;border-radius:4px;border-color:#374755;color:#aebdca}.office-badge.training{color:#ccbfe5;border-color:#514361}.office-badge.historical{color:#ffce80;border-color:#69552d}.work-number small,.work-stat small{display:block;color:#8fa8bd;font-size:10px;margin-bottom:5px}.work-number strong{display:block;font:600 18px/1.2 var(--display);font-variant-numeric:tabular-nums;letter-spacing:-.025em}.work-number span{display:block;margin-top:5px;color:#97acc0;font-size:10px}.work-number .positive,.positive{color:#9cdec3}.work-number .negative,.negative{color:#e7ae9f}.work-decision p{font-size:11px;line-height:1.4;margin:6px 0;color:#b8c8d7}.work-decision small{font-size:10px;color:#8fa7bb}.work-decision small.review-old{color:#f1c37e}.work-signal{display:inline-flex;align-items:center;padding:4px 8px;border-radius:6px;background:#203548;border:1px solid #3a5368;color:#d7e9f6;font-size:10px;font-weight:600}.work-signal.attention{color:#f5ce8f;background:#342d22;border-color:#645039}.work-chevron{font-size:20px;font-weight:300;color:#8da6bc;justify-self:end}.work-item[open] .work-chevron{transform:rotate(45deg)}
.work-detail{border-top:1px solid #2c4053;padding:20px 24px;background:#0c1723}.work-detail-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.work-detail h4{font:600 13px var(--display);margin:12px 0;color:#dbe8f4}.work-detail h4 span{margin-left:7px;color:#95aec4}.work-rationale{font-size:13px;line-height:1.7;color:#c8d8e6;margin:10px 0 18px}.work-metrics{display:flex;flex-wrap:wrap;gap:24px;padding:12px 0}.work-stat{flex:1;min-width:120px}.work-stat strong{font-size:14px;font-weight:600}.work-detail details{margin-top:18px;color:#879fb4;font-size:11px}.work-detail details pre{max-height:240px;overflow:auto;white-space:pre-wrap}.office-ask{font-size:11px;padding:8px 12px;background:#1b3549;border-color:#3e5d75}.office-warning{font-size:12px;color:#f4cb86;background:#2a251e;padding:10px;border-radius:8px}.work-timeline{list-style:none;padding:0 0 0 15px;border-left:1px solid #3b5368}.work-timeline li{padding:10px 0;font-size:12px}.work-timeline li>div{display:flex;gap:12px;justify-content:space-between}.work-timeline time{color:#8fa7bb;font-size:10px}.work-timeline p{color:#b1c5d5;line-height:1.6}.office-advanced{border:1px solid #253544;padding:4px 16px;border-radius:12px;margin-top:22px}.office-advanced>summary{font-size:11px}.office-advanced .cc-fresh,.office-advanced .cc-acct{margin:12px 0}.office-advanced .cc-banner{font-size:12px}.cc-paper-banner{font:500 10px/1.3 var(--display);padding:7px 12px;border-radius:8px;margin-bottom:16px;letter-spacing:.05em}
@media(max-width:1120px){body.cc main{padding:20px}.office-layout{grid-template-columns:minmax(0,1fr) 300px;gap:18px}.work-item>summary{grid-template-columns:minmax(0,1.3fr) minmax(80px,.7fr) minmax(105px,1fr) 12px;padding:16px 14px;gap:10px}.work-avatar{display:none}.office-metric{padding:16px}.office-metric strong{font-size:25px}}
@media(max-width:800px){.office-layout{display:flex}.office-side{width:100%;max-height:none;overflow:visible}.office-heading{flex-direction:row;align-items:center;margin:6px 0 22px}.office-heading h1{font-size:29px}.office-heading p{font-size:12px}.office-heading>a{font-size:10px;padding:8px;white-space:nowrap}.office-heading .office-kicker{font-size:8px}.work-heading{align-items:start;flex-direction:column;gap:7px}.work-heading p{max-width:none}.work-heading h2{font-size:21px}.work-item>summary{grid-template-columns:minmax(0,1fr) 90px 12px;gap:10px;padding:16px}.work-name{grid-column:1}.work-name h3{font-size:15px}.work-name p{font-size:10px}.work-number{grid-column:2;text-align:right}.work-number strong{font-size:17px}.work-chevron{grid-column:3;grid-row:1}.work-decision{grid-column:1/3;display:flex;align-items:center;flex-wrap:wrap;gap:6px 10px}.work-decision p{margin:0;flex:1;min-width:120px}.work-decision small{flex-basis:100%}.office-summary{margin-bottom:23px}.office-metric{padding:14px 10px}.office-metric strong{font-size:22px}.office-metric small{font-size:9px}.office-status{font-size:10px}.work-detail{padding:14px}.work-detail-head{flex-wrap:wrap}.work-metrics{gap:16px}.office-side .cc-stage{height:180px;min-height:180px}.cc-top .cc-sub,.cc-top #readat,.cc-top .ro{display:none}.cc-top .cc-nav a{padding:8px 11px;font-size:12px}.cc-top .cc-nav a span{font-size:9px}.cc-top{gap:8px;padding:10px 14px}.cc-top .meta{font-size:10px}.cc-top .meta button{padding:5px 8px;font-size:11px}}
@media(prefers-reduced-motion:reduce){.work-item>summary{transition:none}}

.club-logo{position:relative;background:#e5edf2;border-color:#d7e5ef;padding:5px;flex-basis:42px;height:42px;border-radius:11px}.club-logo img{position:absolute;inset:5px;width:30px;height:30px;object-fit:contain;background:#e5edf2}.club-logo>span{font-size:9px;color:#2d4254}@media(max-width:1120px){.work-avatar.club-logo{display:grid;flex-basis:32px;height:32px}.club-logo img{width:22px;height:22px}}
"""
OFFICE_JS = r"""
(function(){
 'use strict';
 if(!window.CC||!CC.ops)return;
 var kind=document.body.dataset.kind, names={derek:'Derek',xavier:'Xavier',audrey:'Audrey'}, name=names[kind];if(!name)return;
 var main=document.getElementById('cc-main'),hero=main.querySelector('.cc-hero'),talk=document.getElementById('talk');
 var el=document.createElement('section');el.className='office-heading';
 el.innerHTML='<div><span class="office-kicker">Management office · '+name+'</span><h1>'+({derek:'Derek’s office',xavier:'Xavier’s office',audrey:'Audrey’s office'}[kind])+'</h1><p>'+({derek:'Discovery & entry',xavier:'Portfolio management',audrey:'Audit & intelligence'}[kind])+'</p></div><a href="#talk">Talk to '+name+' ↗</a>';
 hero.before(el);
 var layout=document.createElement('section');layout.className='office-layout';layout.innerHTML='<div class="office-board" aria-label="'+name+' workboard"><div id="office-status" class="office-status">Reading the recorded workspace…</div><div id="office-content"></div></div><aside class="office-side" aria-label="'+name+' office conversation"></aside>';
 el.after(layout);var side=layout.querySelector('aside');side.append(hero);side.append(talk);
 var advanced=document.createElement('details');advanced.className='office-advanced';advanced.innerHTML='<summary>All records, strategy detail and technical evidence</summary>';layout.after(advanced);
 var brief=hero.querySelector('.cc-brief');if(brief)advanced.append(brief);
 var node=advanced.nextElementSibling;while(node){var next=node.nextElementSibling;advanced.append(node);node=next;}
 ['paper-acct','paper-fresh','cc-banner'].forEach(function(id){var item=document.getElementById(id);if(item)advanced.append(item);});
 var ctx=document.createElement('div');ctx.id='office-context';ctx.className='office-context';ctx.hidden=true;talk.querySelector('.talk-form').before(ctx);
 var note=talk.querySelector('.talk-note'),noteDetails=document.createElement('details');noteDetails.className='office-note';noteDetails.innerHTML='<summary>Conversation, memory & policy boundaries</summary>';note.before(noteDetails);noteDetails.append(note);var log=talk.querySelector('.talk-log');log.before(talk.querySelector('.talk-form'));
 var mode=document.createElement('label');mode.className='office-response-mode';mode.innerHTML='Answer style <select id="office-answer-style"><option value="brief">Conversational</option><option value="full">Full analysis</option></select>';talk.querySelector('.talk-form').before(ctx);talk.querySelector('.talk-form').before(mode);
 var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
 var num=function(v){return typeof v==='number'&&isFinite(v);},money=function(v){return num(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v):'Not recorded';};
 function human(v){return String(v||'Not recorded').replace(/_/g,' ').toLowerCase().replace(/^./,function(c){return c.toUpperCase();});}
 function data(s){return s&&(s.status==='OK'||s.status==='EMPTY')?s.data:null;}
 function list(s){var d=data(s);return Array.isArray(d)?d:[];}
 function metric(k,v){return '<div class="office-metric"><small>'+esc(k)+'</small><strong>'+esc(v)+'</strong></div>';}
 function time(v){var d=new Date(typeof v==='number'?v*1000:v);return v&&isFinite(d)?d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'not recorded';}
 function age(v){var t=typeof v==='number'?v*1000:Date.parse(v);return isFinite(t)?Math.max(0,(Date.now()-t)/1000):null;}
 function market(p){var m=p.market||{},l=p.label||{};return {name:m.selection||l.participant||p.participant||p.us_market_slug||'Position name unavailable',event:m.title||l.event||(p.us_market_slug?'Market '+p.us_market_slug:'Event name not recorded')};}
 function tag(s){return /EXPLORATION/.test(s||'')?'<span class="office-badge training">Training · simulated</span>':'<span class="office-badge">Simulated execution</span>';}
 function evidence(p){return '<details><summary>Decision evidence & identifiers</summary><pre>'+esc(JSON.stringify(p,null,2))+'</pre></details>';}
 function ask(p,q){return '<button class="office-ask" data-office-question="'+esc(q)+'">Ask '+name+' ↗</button>';}
 function orderTable(orders){return '<div class="office-orders-wrap"><table class="office-orders"><thead><tr><th>Standing order</th><th>Remaining</th><th>Limit</th><th>Status</th></tr></thead><tbody>'+orders.map(function(o){return '<tr><td>'+esc(human(o.role))+' · '+esc(human(o.direction))+'</td><td>'+esc(num(o.qty)&&num(o.filled_qty)?Math.max(0,o.qty-o.filled_qty):'Not recorded')+'</td><td>'+esc(money(o.limit_price))+'</td><td>'+esc(human(o.state))+'</td></tr>';}).join('')+'</tbody></table></div>';}
 function elapsed(v){var a=age(v);return a===null?'Time not recorded':a<60?Math.floor(a)+'s ago':a<3600?Math.floor(a/60)+'m ago':Math.floor(a/3600)+'h ago';}
 function clubMark(p){var m=market(p),lb=p.label||{},selected=String(lb.participant||m.name||'').replace(/\s+(?:to win|moneyline|ml)$/i,'').trim().toLowerCase(),mlb=/^aec-mlb-/.test(p.us_market_slug||'')||/\bmlb\b/i.test(lb.competition||'')||/baseball/i.test(lb.sport_family||'');var aliases={"athletics":133,"ath":133,"pittsburgh pirates":134,"pirates":134,"pit":134,"san diego padres":135,"padres":135,"sd":135,"seattle mariners":136,"mariners":136,"sea":136,"san francisco giants":137,"giants":137,"sf":137,"st. louis cardinals":138,"cardinals":138,"stl":138,"tampa bay rays":139,"rays":139,"tb":139,"texas rangers":140,"rangers":140,"tex":140,"toronto blue jays":141,"blue jays":141,"tor":141,"minnesota twins":142,"twins":142,"min":142,"philadelphia phillies":143,"phillies":143,"phi":143,"atlanta braves":144,"braves":144,"atl":144,"chicago white sox":145,"white sox":145,"cws":145,"miami marlins":146,"marlins":146,"mia":146,"new york yankees":147,"yankees":147,"nyy":147,"milwaukee brewers":158,"brewers":158,"mil":158,"los angeles angels":108,"angels":108,"laa":108,"arizona diamondbacks":109,"d-backs":109,"az":109,"baltimore orioles":110,"orioles":110,"bal":110,"boston red sox":111,"red sox":111,"bos":111,"chicago cubs":112,"cubs":112,"chc":112,"cincinnati reds":113,"reds":113,"cin":113,"cleveland guardians":114,"guardians":114,"cle":114,"colorado rockies":115,"rockies":115,"col":115,"detroit tigers":116,"tigers":116,"det":116,"houston astros":117,"astros":117,"hou":117,"kansas city royals":118,"royals":118,"kc":118,"los angeles dodgers":119,"dodgers":119,"lad":119,"washington nationals":120,"nationals":120,"wsh":120,"new york mets":121,"mets":121,"nym":121};var id=mlb?aliases[selected]:null;if(!id)return '<span class="work-avatar" aria-hidden="true">'+esc(m.name.slice(0,2).toUpperCase())+'</span>';return '<span class="work-avatar club-logo"><span aria-hidden="true">'+esc(m.name.slice(0,2).toUpperCase())+'</span><img src="/api/command/agents/static/mlb-logo-'+id+'.svg" alt="'+esc(lb.participant||m.name)+' logo" width="34" height="34" loading="lazy"></span>';}
 function clock(v){return '<span data-work-age="'+esc(v==null?'':v)+'">'+esc(elapsed(v))+'</span>';}
 function mini(k,v,cls){return '<div class="work-stat '+(cls||'')+'"><small>'+esc(k)+'</small><strong>'+esc(v)+'</strong></div>';}
 function tone(v){return !num(v)?'':v>0?'positive':v<0?'negative':'';}
 function intro(label,title,note){return '<header class="work-heading"><div><span class="office-kicker">'+esc(label)+'</span><h2>'+esc(title)+'</h2></div><p>'+esc(note)+'</p></header>';}
 function signal(text,warning){return '<span class="work-signal '+(warning?'attention':'')+'">'+esc(text)+'</span>';}
 function xavier(j){
  var ps=list(j.owned_positions).filter(function(p){return p.remaining&&p.remaining.open_qty>0;}),orders=list(j.standing_orders),ex=data(j.exposure)||{},known=data(j.owned_positions)!==null;
  var stale=ps.filter(function(p){var a=age((p.recommendation||{}).reviewed_at);return a===null||a>120;}).length;
  var out='<div class="office-summary">'+metric('Open positions in view',known?ps.length:'Unavailable')+metric('Capital in positions',money(ex.cost_basis_at_risk_usd))+metric('Realized P&L',money(ex.realized_pnl_usd))+'</div>';
  out+=intro('Portfolio desk','Positions & exit plans',stale?stale+' review'+(stale===1?' is':'s are')+' older than 2 minutes or missing.':'Latest recorded decisions · select a position for the full plan.');
  if(!ps.length)return out+'<div class="office-empty">'+(known?'No open positions in this read.':'Positions could not be read. This is not an empty portfolio.')+'</div>';
  return out+'<div class="work-list">'+ps.map(function(p){
   var m=market(p),r=p.remaining||{},rc=p.recommendation||{},a=age(rc.reviewed_at),old=a===null||a>120,os=orders.filter(function(o){return o.group_id===p.group_id&&o.open===true;}),count=r.open_management_orders;
   var orderLine=os.length?os.map(function(o){var q=num(o.qty)&&num(o.filled_qty)?Math.max(0,o.qty-o.filled_qty):null;return human(o.direction)+' '+(q===null?'?':q)+' @ '+money(o.limit_price);}).join(' · '):count===0?'No working orders':'Order detail unavailable';
   return '<details class="work-item" id="office-pos-'+esc(p.group_id)+'" data-office-position="'+esc(p.group_id)+'" data-work-key="'+esc(p.group_id)+'"><summary><div class="work-name">'+clubMark(p)+'<div><h3>'+esc(m.name)+'</h3><p>'+esc(m.event)+' · '+esc(r.open_qty)+' contracts</p>'+tag(p.strategy)+'</div></div><div class="work-number"><small>Marked value</small><strong>'+esc(money(r.marked_value_usd))+'</strong><span class="'+tone(r.unrealized_pnl_usd)+'">'+esc(money(r.unrealized_pnl_usd))+' unrealized</span></div><div class="work-decision">'+signal(human(rc.recommendation||'Awaiting review'),old)+'<p>'+esc(orderLine)+'</p><small class="'+(old?'review-old':'')+'">Review '+clock(rc.reviewed_at)+'</small></div><span class="work-chevron" aria-hidden="true">+</span></summary><div class="work-detail"><div class="work-detail-head"><h4>Exit plan</h4>'+ask(p,'Explain your current exit plan, standing orders and remaining risk for '+m.name+'. Position group '+p.group_id+'.')+'</div><p class="work-rationale">'+esc(rc.refusal_words||(rc.selection||{}).selection_reason||human(rc.refusal||rc.trigger||'No rationale recorded'))+'</p><div class="work-metrics">'+mini('Action recorded',human((rc.action||{}).taken||'No action recorded'))+mini('Cost incl. fees',money(r.cost_basis_usd))+mini('Last review',time(rc.reviewed_at))+'</div>'+(old?'<p class="office-warning">This review is older than 2 minutes or missing. It is not a fresh recommendation.</p>':'')+'<h4>Working orders <span>'+esc(num(count)?count:'Unknown')+'</span></h4>'+(os.length?orderTable(os):'<p class="office-note">'+esc(orderLine)+'</p>')+'<p class="office-note">An unfilled exit order does not lock in a return.'+(num(count)&&os.length<count?' Only '+os.length+' of '+count+' orders are in this read.':'')+'</p><div class="work-metrics">'+mini('If ordinary outcome wins',money((r.ordinary_completion||{}).win_usd))+mini('If ordinary outcome loses',money((r.ordinary_completion||{}).lose_usd))+'</div><p class="office-note">Conditional P&L on remaining contracts; exceptional settlement may differ.</p>'+evidence({group_id:p.group_id,review:rc,orders:os,exceptional_settlement:r.exceptional_settlement,exceptional_note:r.exceptional_note})+'</div></details>';
  }).join('')+'</div>';
 }
 function derek(j){
  var rows=[];(j.strategies||[]).forEach(function(s){list(s.recent).forEach(function(r){rows.push(Object.assign({},r,{office_policy_title:s.title||r.strategy,office_historical:!!(s.version&&r.policy_version&&s.version!==r.policy_version)}));});});
  rows.sort(function(a,b){if(a.office_historical!==b.office_historical)return a.office_historical?1:-1;return (num(b.edge_pp)?b.edge_pp:-Infinity)-(num(a.edge_pp)?a.edge_pp:-Infinity);});
  var entries=list(j.standing_entry_orders),shown=rows.slice(0,12),out='<div class="office-summary">'+metric('Evaluations shown',shown.length)+metric('Working entry orders',data(j.standing_entry_orders)!==null?entries.length:'Unavailable')+metric('Approved in this view',shown.filter(function(r){return r.verdict==='ENTER';}).length)+'</div>';
  if(entries.length)out+='<details class="work-item" data-work-key="entries"><summary><div class="work-name"><div><h3>Working entry orders</h3><p>'+entries.length+' pending orders · an order is not a fill</p></div></div><span class="work-chevron">+</span></summary><div class="work-detail">'+entries.map(function(o){return '<h4>'+esc(market(o).name)+'</h4>'+orderTable([o]);}).join('')+'</div></details>';
  out+=intro('Discovery desk','Opportunity queue','Recorded evaluations · serving policy versions first, then historical; gross edge within each group.');
  if(!shown.length)return out+'<div class="office-empty">No evaluation records available in this read.</div>';
  return out+'<div class="work-list">'+shown.map(function(r){var m=market(r),why=r.verdict==='ENTER'?'Approved for entry':r.refusal_words||human(r.refusal);return '<details class="work-item" data-office-decision="'+esc(r.decision_id)+'" data-work-key="'+esc(r.decision_id)+'"><summary><div class="work-name">'+clubMark(r)+'<div><h3>'+esc(m.name)+'</h3><p>'+esc(m.event)+'</p>'+tag(r.strategy)+(r.office_historical?' <span class="office-badge historical">Historical policy version</span>':'')+'</div></div><div class="work-number"><small>Gross edge</small><strong>'+esc(num(r.edge_pp)?r.edge_pp.toFixed(2)+' pp':'Not recorded')+'</strong><span class="'+tone(r.net_ev_usd)+'">'+esc(money(r.net_ev_usd))+' net EV</span></div><div class="work-decision">'+signal(r.verdict==='ENTER'?'Approved':'Refused',false)+'<p>'+esc(why)+'</p><small>Evaluated '+clock(r.decided_at)+'</small></div><span class="work-chevron" aria-hidden="true">+</span></summary><div class="work-detail"><div class="work-detail-head"><h4>Decision breakdown</h4>'+ask(r,'Explain the price, fees, expected value and current status of '+m.name+'. Decision '+r.decision_id+'.')+'</div><p class="work-rationale">'+esc(typeof r.explanation==='string'?r.explanation:why)+'</p><div class="work-metrics">'+mini('Pinnacle estimate',num(r.p_pinnacle)?(100*r.p_pinnacle).toFixed(1)+'%':'Not recorded')+mini('Entry price',money(r.purchase_price))+mini('Fees',money(r.fees_usd))+'</div><p class="office-note">'+esc(r.office_policy_title)+' · recorded policy <b>'+esc(r.policy_version||'Not recorded')+'</b> · '+esc(time(r.decided_at))+'. '+(r.office_historical?'Historical decision: its refusal uses the rules at evaluation, not today’s rules.':'')+' This is a recorded observation, not an executable quote. Positive gross edge can lose after fees.</p>'+evidence(r)+'</div></details>';}).join('')+'</div>';
 }
 function audrey(j){
  var recs=list(j.operational_audit),a=data(j.account)||{},out='<div class="office-summary">'+metric('Ledger check',a.ledger_consistent===true?'Reconciled':a.ledger_consistent===false?'Needs attention':'Unavailable')+metric('Realized P&L',money(a.realized_pnl_usd))+metric('Unrealized P&L',money(a.unrealized_pnl_usd))+'</div>';
  out+=intro('Intelligence desk','Recommendations & follow-through','Recorded findings, accountable owners and measured outcomes.');
  if(!recs.length)return out+'<div class="office-empty">No operational recommendations in this read. Full audit records remain below.</div>';
  return out+'<div class="work-list">'+recs.map(function(r){var events=r.events||[],response=events.filter(function(e){return e.kind==='RESPONSE'&&e.actor!=='SYSTEM';})[0],measurement=events.filter(function(e){return /MEASUR/.test(e.kind);})[0];return '<details class="work-item" data-work-key="'+esc(r.recommendation_id)+'"><summary><div class="work-name"><span class="work-avatar" aria-hidden="true">↗</span><div><h3>'+esc(human(r.kind||r.category))+'</h3><p>'+esc(r.recommendation||'Recommendation text not recorded')+'</p></div></div><div class="work-number"><small>Responsible agent</small><strong>'+esc(r.owner_agent||'Unassigned')+'</strong><span>'+clock(r.created_at)+'</span></div><div class="work-decision">'+signal(human(r.status),r.status==='NOT_IMPROVED')+'<p>'+esc(measurement?'Measurement recorded':response?'Agent review recorded':'Awaiting response / measurement')+'</p></div><span class="work-chevron" aria-hidden="true">+</span></summary><div class="work-detail"><div class="work-detail-head"><h4>Improvement record</h4>'+ask(r,'Explain recommendation '+r.recommendation_id+', its evidence, genuine agent responses and subsequent measurements.')+'</div><div class="work-metrics">'+mini('Metric',r.metric||'Not recorded')+mini('Baseline',(r.baseline||{}).value==null?'Not recorded':r.baseline.value)+'</div><ol class="work-timeline">'+events.map(function(e){return '<li><div><b>'+esc(e.actor==='SYSTEM'?'Automated acknowledgement':e.actor)+' · '+esc(human(e.kind))+'</b><time>'+esc(time(e.at))+'</time></div><p>'+esc(e.body)+'</p></li>';}).join('')+'</ol>'+(!events.length?'<p class="office-note">No response or measurement is recorded in this read.</p>':'')+'<p class="office-note">Automated acknowledgements are not agent review. An operational improvement is not proof of better investment performance.</p>'+evidence(r)+'</div></details>';}).join('')+'</div>';
 }
 var lastMarkup='';
 function paintHealth(st){var status=document.getElementById('office-status'),j=st&&st.json,h=j&&data((j.freshness||{}).agent_heartbeat),hb=h&&h.heartbeat_at,hbAge=age(hb),old=hbAge===null||hbAge>(num(h&&h.stale_after_s)?h.stale_after_s:300);status.classList.toggle('warn',!!(st&&st.fail)||old);status.innerHTML=st&&st.fail?'<span>Read unavailable · '+esc(st.fail.why||st.fail.state||'connection error')+'. Last records retained.</span>':j?'<span><i class="health-light"></i>Records read '+clock(st.okAt)+'</span><span>Agent pass '+clock(hb)+(old?' · stale / unavailable':'')+'</span>':'Waiting for records · no zero balance assumed.';}
 var lastState=null;
 function render(st){lastState=st;paintHealth(st);var j=st&&st.json;if(!j)return;var html=kind==='xavier'?xavier(j):kind==='derek'?derek(j):audrey(j);if(html!==lastMarkup){var content=document.getElementById('office-content'),open=new Set([...content.querySelectorAll('[data-work-key][open]')].map(function(d){return d.dataset.workKey;}));content.innerHTML=html;content.querySelectorAll('[data-work-key]').forEach(function(d){d.open=open.has(d.dataset.workKey);});lastMarkup=html;}}
 // Advance recorded ages each second; this makes no provider or database request.
 setInterval(function(){if(document.hidden)return;document.querySelectorAll('[data-work-age]').forEach(function(el){var raw=el.dataset.workAge,v=raw!==''&&isFinite(Number(raw))?Number(raw):raw;el.textContent=elapsed(v);});if(lastState)paintHealth(lastState);},1000);
 document.addEventListener('click',function(e){var link=e.target.closest('a[href^="#"],#trace-btn');if(!link)return;var target=link.id==='trace-btn'?document.getElementById('trace'):document.getElementById(link.getAttribute('href').slice(1));if(target&&advanced.contains(target))advanced.open=true;});
 var original=CC.ops.panels;CC.ops.panels=function(k,st){var result=original(k,st);if(k===kind)render(st);return result;};
 layout.addEventListener('click',function(e){var b=e.target.closest('[data-office-question]');if(!b)return;var input=document.getElementById('talk-in');input.value=b.dataset.officeQuestion;ctx.hidden=false;ctx.textContent='Selected record attached to your question. Review it, then send.';input.focus();talk.scrollIntoView({behavior:'smooth',block:'nearest'});});
 // MOBILE: the conversation sits below the workboard; a fixed button reaches it.
 var jump=document.createElement('button');jump.type='button';jump.className='office-talk-jump';jump.textContent='Talk to '+name;jump.setAttribute('aria-label','Go to the conversation with '+name);
 jump.addEventListener('click',function(){talk.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(function(){var i=document.getElementById('talk-in');if(i)i.focus({preventScroll:true});},350);});
 document.body.append(jump);
 if('IntersectionObserver' in window){new IntersectionObserver(function(es){es.forEach(function(e){jump.classList.toggle('hidden',e.isIntersecting);});},{threshold:0.15}).observe(talk);}
 layout.addEventListener('error',function(e){if(e.target.matches('.club-logo img'))e.target.remove();},true);
 window.CCOffice={render:render};
})();
"""

# Progressive playback of the EXISTING authenticated streaming speech response.
# Text is still grounded and stored before it is spoken. No speculative tokens.
SPEECH_JS = r"""
window.CCStreamSpeech = async function(response, audio, signal, onStart) {
 var MS=window.MediaSource, url=null, reader=null, ms=null;
 var cleaned=false;var cleanup=function(){if(cleaned)return;cleaned=true;signal.removeEventListener('abort',cleanup);if(reader)reader.cancel().catch(function(){});audio.pause();audio.removeAttribute('src');audio.load();if(url)URL.revokeObjectURL(url);};
 signal.addEventListener('abort',cleanup,{once:true});
 try {
  if(!MS||!MS.isTypeSupported('audio/mpeg')||!response.body){
   var blob=await response.blob();if(signal.aborted)return;url=URL.createObjectURL(blob);audio.src=url;await audio.play();onStart(false);
   audio.addEventListener('ended',cleanup,{once:true});return;
  }
  ms=new MS();url=URL.createObjectURL(ms);audio.src=url;
  await new Promise(function(resolve,reject){ms.addEventListener('sourceopen',resolve,{once:true});signal.addEventListener('abort',function(){reject(new DOMException('Aborted','AbortError'));},{once:true});});
  if(signal.aborted)return;
  var sb=ms.addSourceBuffer('audio/mpeg'),started=false;reader=response.body.getReader();
  while(!signal.aborted){var part=await reader.read();if(part.done)break;if(!part.value.length)continue;
   await new Promise(function(resolve,reject){var off=function(){sb.removeEventListener('error',bad);sb.removeEventListener('updateend',done);signal.removeEventListener('abort',aborted);},done=function(){off();resolve();},bad=function(){off();reject(Error('Audio stream could not be decoded. Use replay or another browser.'));},aborted=function(){off();reject(new DOMException('Aborted','AbortError'));};signal.addEventListener('abort',aborted,{once:true});sb.addEventListener('updateend',done,{once:true});sb.addEventListener('error',bad,{once:true});try{sb.appendBuffer(part.value);}catch(e){off();reject(e);}});
   if(!signal.aborted&&!started&&sb.buffered.length){await audio.play();if(signal.aborted)return;started=true;onStart(true);}
  }
  if(!signal.aborted&&ms.readyState==='open')ms.endOfStream();
  audio.addEventListener('ended',cleanup,{once:true});
 } catch(e){cleanup();throw e;}
};
"""
