"""Additive management experience over the existing office/operations UI.

This module renders recorded rationale and activity, never private model
reasoning or invented work. It introduces no network call or execution path.
"""

CSS = r"""
.desk-search .sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.office-heading{padding:8px 0 0}.office-heading h1{font-weight:600;font-size:clamp(30px,3.4vw,46px)}
.office-layout{grid-template-columns:minmax(0,1fr) 356px;gap:24px}.office-side{background:linear-gradient(150deg,#182b3d,#0b1521 50%);box-shadow:0 16px 70px #0004}.office-side .cc-hero{padding:12px 12px 0}.office-side .cc-stage{height:228px;min-height:228px!important;background:radial-gradient(ellipse at 50% 40%,#314b63 0,transparent 65%),linear-gradient(115deg,#132639,#080f1a);border:1px solid #3d5162}.office-side .talk-log{max-height:260px}.office-side .talk-form textarea{background:#09121f;border-color:#3c5368;border-radius:12px}.office-side #talk-send{background:var(--acc);color:#08121c;font-weight:700;border-color:transparent;min-width:76px}.office-side .talk-msg.a{border-radius:3px 14px 14px 14px;background:#132536}.office-side .talk-msg.q{border-radius:14px 3px 14px 14px;background:#233647}.office-side #talk{padding:14px 16px 18px}
.desk-brief{position:relative;padding:25px 26px;border:1px solid #3d556b;border-radius:20px;background:radial-gradient(ellipse at 100% 0,#26476070,transparent 60%),linear-gradient(110deg,#14273a,#0c1724);margin:0 0 22px;overflow:hidden}.desk-brief:before{content:'';position:absolute;inset:0 auto 0 0;width:3px;background:var(--acc);opacity:.8}.desk-brief.new-record{animation:desk-arrival 1s ease-out}.desk-brief-top{display:flex;justify-content:space-between;align-items:center;gap:15px}.desk-eyebrow{font:600 10px var(--display);letter-spacing:.16em;text-transform:uppercase;color:var(--acc)}.desk-record-age{font-size:11px;color:#a5bacb}.desk-brief h2{font:550 clamp(22px,2.2vw,31px)/1.2 var(--display);letter-spacing:-.035em;max-width:720px;margin:15px 0 8px}.desk-subtitle{font-size:12px;line-height:1.6;color:#a9becf;margin:0 0 20px}.desk-insights{display:grid;grid-template-columns:1fr 1.5fr;gap:26px;border-top:1px solid #2c4257;padding-top:17px}.desk-insights small{display:block;color:#90a9be;font-size:10px;margin-bottom:7px}.desk-insights strong{font:600 17px/1.4 var(--display);color:#e4edf6}.desk-insights p{font-size:12px;line-height:1.65;margin:0;color:#bbccdc}.desk-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}.desk-actions button,.desk-tool,.desk-filter{border:1px solid #385168;border-radius:9px;padding:9px 12px;background:#14283a;color:#deebf7;font:500 11px var(--display);cursor:pointer}.desk-actions .primary{background:#d8edf8;color:#0c1b29;border-color:transparent}.desk-empty{color:#a8bbcb;font-size:13px;line-height:1.7}.desk-live-note{font-size:10px;color:#90a6b8;margin:15px 0 0}.desk-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:0 0 18px;flex-wrap:wrap}.desk-search{flex:1;max-width:340px;min-width:190px;position:relative}.desk-search input{box-sizing:border-box;width:100%;padding:11px 44px 11px 13px;border:1px solid #304659;border-radius:10px;background:#0b1622;color:#e6eff8;font:12px var(--display)}.desk-search kbd{position:absolute;right:12px;top:9px;color:#8ba1b5;font:12px var(--display);border:1px solid #344658;border-radius:4px;padding:2px 5px}.desk-filters{display:flex;gap:5px;flex-wrap:wrap}.desk-filter{background:transparent;padding:8px 10px;border-color:transparent;color:#91a8bc}.desk-filter[aria-pressed=true]{background:#21384c;color:#f0f6fb;border-color:#405a71}.desk-filter-count{font-size:10px;color:#91a8bc;min-width:45px;text-align:right}.desk-no-match{padding:22px;border:1px dashed #34495c;border-radius:12px;color:#b7c8d7;font-size:13px;margin:10px 0}.work-item[hidden]{display:none!important}.work-item[data-desk-selected=true]>summary{background:#1a3044;box-shadow:inset 3px 0 var(--acc)}
.desk-activity{margin:26px 0 0;border-top:1px solid #283c4d;padding-top:20px}.desk-section-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.desk-section-head h2{font:600 17px var(--display);letter-spacing:-.025em;margin:0}.desk-section-head span{font-size:10px;color:#8ca3b7}.desk-events{list-style:none;margin:0;padding:0}.desk-event{display:grid;grid-template-columns:10px minmax(0,1fr) 56px;align-items:start;gap:12px;padding:12px 0;border-bottom:1px solid #1c2e3e}.desk-event-dot{width:6px;height:6px;border-radius:50%;background:var(--acc);margin-top:6px;opacity:.75}.desk-event button{padding:0;border:0;background:none;color:#c7d9e8;text-align:left;font:500 12px/1.5 var(--display);cursor:pointer}.desk-event small{display:block;font-size:10px;color:#879fb4;line-height:1.6}.desk-event time{font-size:10px;color:#94aabd;text-align:right;padding-top:3px}.desk-conversation-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:13px 16px 0}.desk-conversation-head strong{font:600 11px var(--display);letter-spacing:.1em;text-transform:uppercase;color:var(--acc)}.desk-conversation-head span{font-size:10px;color:#a6bdcf}.desk-presence{padding:0 16px 12px;color:#9eb5c8;font-size:11px;line-height:1.5}.desk-question-chips{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0 11px}.desk-question-chips button{background:#172b3d;border:1px solid #31495f;color:#bdd3e4;border-radius:20px;padding:6px 9px;font:11px var(--display);cursor:pointer}.desk-conversation-close,.desk-mobile-talk,.desk-backdrop{display:none}.desk-toolbar button:focus-visible,.desk-actions button:focus-visible,.desk-question-chips button:focus-visible,.desk-event button:focus-visible{outline:2px solid var(--acc);outline-offset:3px}.desk-download-note{font-size:10px;color:#9ab0c2;margin:0 0 12px}
@keyframes desk-arrival{from{border-color:var(--acc);box-shadow:0 0 22px #b6eaff25}to{border-color:#3d556b;box-shadow:none}}
@media(min-width:801px){.desk-brief{display:grid;grid-template-columns:1fr 1.35fr;gap:10px 24px;padding:20px 22px}.desk-brief-top{grid-column:1/-1}.desk-brief h2{font-size:25px;margin:5px 0 0}.desk-subtitle{grid-column:1;margin:0}.desk-insights{grid-column:2;grid-row:2/4;grid-template-columns:.8fr 1.2fr;border:0;padding:0;gap:18px}.desk-insights p{font-size:11px}.desk-insights small{margin-bottom:4px}.desk-actions{margin-top:5px}.desk-live-note{margin:6px 0 0;align-self:center;font-size:9px}.office-summary{margin-bottom:20px}.office-metric{padding:15px 22px}.office-metric strong{font-size:27px}}
@media(max-width:1120px){.office-layout{grid-template-columns:minmax(0,1fr) 306px;gap:18px}.desk-brief{padding:20px}.desk-insights{grid-template-columns:1fr;gap:12px}.desk-brief h2{font-size:25px}}
@media(max-width:800px){.office-board{display:flex;flex-direction:column}.office-status{order:0}.desk-toolbar{order:1}#office-content,.desk-no-match{order:2}.desk-brief{order:3;margin-top:20px}.desk-activity{order:4}body.cc main{padding-bottom:110px}.office-layout{display:flex;flex-direction:column}.desk-brief{padding:19px 18px;margin-bottom:18px}.desk-brief h2{font-size:25px}.desk-subtitle{margin-bottom:14px}.desk-insights{grid-template-columns:1fr;gap:14px}.desk-brief-top{align-items:start}.desk-eyebrow{font-size:9px}.desk-record-age{font-size:10px;white-space:nowrap}.desk-toolbar{gap:10px}.desk-search{max-width:none;flex-basis:100%}.desk-search kbd{display:none}.desk-filters{gap:3px}.desk-filter{padding:7px 8px;font-size:10px}.desk-mobile-talk{position:fixed;z-index:80;display:flex;align-items:center;justify-content:space-between;gap:20px;left:16px;right:16px;bottom:max(16px,env(safe-area-inset-bottom));padding:15px 18px;border:1px solid #66849c;border-radius:16px;background:#192e42f5;box-shadow:0 10px 35px #0008;color:#f0f7ff;font:600 14px var(--display);cursor:pointer;backdrop-filter:blur(18px)}.desk-mobile-talk span{font:400 10px var(--display);color:#b8cdde}.desk-mobile-talk b{font-size:19px;color:var(--acc)}.office-side{display:none}.office-side.desk-conversation-open{display:block;position:fixed;inset:max(10px,env(safe-area-inset-top)) 10px max(10px,env(safe-area-inset-bottom));width:auto;max-height:none;z-index:100;overflow:auto;border-radius:20px;overscroll-behavior:contain}.desk-conversation-close{display:block;background:#223a4d;border:1px solid #476179;border-radius:8px;color:white;font:12px var(--display);padding:7px 10px}.desk-backdrop[data-open=true]{display:block;position:fixed;inset:0;z-index:99;background:#020813cc;backdrop-filter:blur(8px)}body.desk-chat-open{overflow:hidden}.office-side .cc-stage{height:170px;min-height:170px!important}.office-side .talk-log{max-height:34vh}.desk-conversation-head{position:sticky;top:0;background:#0f1e2df5;padding:12px 16px;z-index:2}.desk-presence{padding-bottom:5px}.office-heading>a{display:none}.desk-question-chips{margin-top:4px}.desk-event{grid-template-columns:8px minmax(0,1fr) 47px}}
@media(prefers-reduced-motion:reduce){.desk-brief.new-record{animation:none}.desk-backdrop{backdrop-filter:none}}
"""

JS = r"""
(function(){
 'use strict';
 var office=window.CCOffice,content=document.getElementById('office-content');
 if(!office||!content||!window.CC||!CC.ops)return;
 var kind=document.body.dataset.kind,name=kind.charAt(0).toUpperCase()+kind.slice(1);
 var board=document.querySelector('.office-board'),side=document.querySelector('.office-side'),talk=document.getElementById('talk'),input=document.getElementById('talk-in');
 if(!board||!side||!talk||!input)return;
 var E=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
 var n=function(v){return typeof v==='number'&&isFinite(v);};
 var data=function(s){return s&&(s.status==='OK'||s.status==='EMPTY')?s.data:null;};
 var list=function(s){var v=data(s);return Array.isArray(v)?v:[];};
 var human=function(s){return String(s||'Not recorded').replace(/_/g,' ').toLowerCase().replace(/^./,function(c){return c.toUpperCase();});};
 var money=function(v){return n(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v):'Not recorded';};
 function epoch(v){if(v===null||v===undefined||v==='')return null;var t=n(v)?v:Date.parse(v)/1000;return isFinite(t)?t:null;}
 function ago(v){var t=epoch(v);if(t===null)return 'Unknown time';var a=Math.max(0,Date.now()/1000-t);return a<60?Math.floor(a)+'s ago':a<3600?Math.floor(a/60)+'m ago':Math.floor(a/3600)+'h ago';}
 function ageSpan(v){return '<span data-desk-at="'+E(v==null?'':v)+'">'+E(ago(v))+'</span>';}
 function title(r){return (r.market||{}).selection||(r.label||{}).participant||r.us_market_slug||r.recommendation_id||'Record name unavailable';}
 function event(r){return (r.market||{}).title||(r.label||{}).event_title||'Event detail unavailable';}
 var state=null,lastReadAt=null,records=[],selected=null,filter='all',query='',seen=new Set(),first=true,lastBrief='',previousFocus=null;
 var brief=document.createElement('section');brief.className='desk-brief';brief.setAttribute('aria-label','Recorded decision briefing');brief.innerHTML='<div class="desk-eyebrow">At the desk</div><p class="desk-empty">Waiting for recorded work. A conversation is available on the right.</p>';content.before(brief);
 var filters=kind==='xavier'?[['all','All positions'],['attention','Needs review'],['orders','Working orders']]:kind==='derek'?[['all','All evaluations'],['current','Current policy'],['approved','Approved']]:[['all','All findings'],['pending','Awaiting response'],['measured','Measured']];
 var toolbar=document.createElement('div');toolbar.className='desk-toolbar';toolbar.innerHTML='<label class="desk-search"><span class="sr-only">Search '+E(name)+' records</span><input id="desk-search" type="search" placeholder="Search games, decisions or records…" aria-label="Search '+E(name)+' records"><kbd aria-hidden="true">/</kbd></label><div class="desk-filters" aria-label="Filter workboard">'+filters.map(function(f){return '<button type="button" class="desk-filter" data-desk-filter="'+f[0]+'" aria-pressed="'+(f[0]==='all')+'">'+f[1]+'</button>';}).join('')+'</div><span class="desk-filter-count" id="desk-count"></span><button type="button" class="desk-tool" id="desk-export">Export view ↓</button>';content.before(toolbar);
 var noMatch=document.createElement('p');noMatch.className='desk-no-match';noMatch.hidden=true;noMatch.textContent='No records match this view. Clear the search or choose another filter.';content.after(noMatch);
 var activity=document.createElement('section');activity.className='desk-activity';activity.setAttribute('aria-label','Recorded activity');noMatch.after(activity);
 var sideHead=document.createElement('div');sideHead.className='desk-conversation-head';sideHead.innerHTML='<strong id="desk-conversation-title">In conversation · '+E(name)+'</strong><button type="button" class="desk-conversation-close" aria-label="Close conversation">Close ×</button>';side.prepend(sideHead);
 var presence=document.createElement('p');presence.className='desk-presence';presence.id='desk-presence';presence.textContent='Conversation uses your signed-in session.';sideHead.after(presence);
 var chips=document.createElement('div');chips.className='desk-question-chips';chips.innerHTML=['Brief me','What changed?','What needs attention?'].map(function(t){return '<button type="button" data-desk-prompt="'+E(t)+'">'+E(t)+'</button>';}).join('');talk.querySelector('.talk-form').before(chips);
 var backdrop=document.createElement('div');backdrop.className='desk-backdrop';backdrop.dataset.open='false';document.body.append(backdrop);
 var dock=document.createElement('button');dock.type='button';dock.className='desk-mobile-talk';dock.setAttribute('aria-haspopup','dialog');dock.setAttribute('aria-expanded','false');dock.innerHTML='<div>Talk to '+E(name)+'<br><span>Ask about a game, decision or exit plan</span></div><b aria-hidden="true">↗</b>';document.body.append(dock);
 var media=window.matchMedia('(max-width:800px)'),inertNodes=[],sideHome=side.parentNode,sideAnchor=document.createComment('conversation home');side.before(sideAnchor);
 function openTalk(){if(side.classList.contains('desk-conversation-open')){input.focus({preventScroll:true});return;}previousFocus=document.activeElement;if(media.matches){document.body.append(side);side.classList.add('desk-conversation-open');side.setAttribute('role','dialog');side.setAttribute('aria-modal','true');side.setAttribute('aria-labelledby','desk-conversation-title');backdrop.dataset.open='true';document.body.classList.add('desk-chat-open');dock.setAttribute('aria-expanded','true');var cur=side;inertNodes=[];while(cur&&cur!==document.body){Array.from(cur.parentElement.children).forEach(function(s){if(s!==cur&&s!==backdrop&&s!==side&&!s.inert){s.inert=true;inertNodes.push(s);}});cur=cur.parentElement;}}else side.scrollIntoView({block:'nearest',behavior:'auto'});input.focus({preventScroll:media.matches});if(media.matches)input.closest('.talk-form').scrollIntoView({block:'nearest',behavior:'auto'});}
 function closeTalk(){if(side.parentNode!==sideHome&&sideAnchor.isConnected)sideHome.insertBefore(side,sideAnchor.nextSibling);side.classList.remove('desk-conversation-open');side.removeAttribute('role');side.removeAttribute('aria-modal');side.removeAttribute('aria-labelledby');backdrop.dataset.open='false';document.body.classList.remove('desk-chat-open');dock.setAttribute('aria-expanded','false');inertNodes.forEach(function(el){el.inert=false;});inertNodes=[];if(previousFocus&&previousFocus.isConnected)previousFocus.focus({preventScroll:true});}
 dock.addEventListener('click',openTalk);sideHead.querySelector('button').addEventListener('click',closeTalk);backdrop.addEventListener('click',closeTalk);media.addEventListener('change',function(){if(!media.matches)closeTalk();});
 function draft(q){input.value=q;var context=document.getElementById('office-context');if(context){context.hidden=false;context.textContent='Question drafted. Review it, then send.';}openTalk();}
 document.addEventListener('click',function(e){if(e.target.closest('a[href="#talk"],.office-mobile-talk')){e.preventDefault();openTalk();}else if(e.target.closest('[data-office-question]')){setTimeout(openTalk,0);}});
 document.addEventListener('keydown',function(e){if(e.key==='Escape'&&side.classList.contains('desk-conversation-open')){e.preventDefault();closeTalk();return;}if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!e.target.matches('input,textarea,select,[contenteditable=true]')){e.preventDefault();document.getElementById('desk-search').focus();}if(e.key==='Tab'&&side.classList.contains('desk-conversation-open')){var focus=Array.from(side.querySelectorAll('button:not([disabled]),a[href],input,textarea,select,[tabindex="0"]')).filter(function(el){return el.getClientRects().length&&!el.closest('[hidden]');});if(!focus.length)return;var firstEl=focus[0],lastEl=focus[focus.length-1];if(e.shiftKey&&document.activeElement===firstEl){e.preventDefault();lastEl.focus();}else if(!e.shiftKey&&document.activeElement===lastEl){e.preventDefault();firstEl.focus();}}});
 function recordRows(j){var rows=[];
  if(kind==='xavier')list(j.owned_positions).filter(function(p){return p.remaining&&p.remaining.open_qty>0;}).forEach(function(p){var rv=p.recommendation||{},orders=list(j.standing_orders).filter(function(o){return o.group_id===p.group_id&&o.open===true;});rows.push({id:p.group_id,at:rv.reviewed_at,label:title(p),event:event(p),decision:human(rv.recommendation||'Awaiting review'),why:rv.refusal_words||(rv.selection||{}).selection_reason||'No rationale recorded',detail:orders.length?orders.map(function(o){return human(o.direction)+' '+(n(o.qty)&&n(o.filled_qty)?Math.max(0,o.qty-o.filled_qty):'?')+' @ '+money(o.limit_price);}).join(' · '):p.remaining.open_management_orders===0?'No working order':'Working-order detail unavailable',attention:epoch(rv.reviewed_at)===null||Date.now()/1000-epoch(rv.reviewed_at)>120,orders:orders.length,original:p,type:'Position review'});});
  if(kind==='derek')(j.strategies||[]).forEach(function(s){list(s.recent).forEach(function(r){rows.push({id:r.decision_id,at:r.decided_at,label:title(r),event:event(r),decision:r.verdict==='ENTER'?'Approved for entry':r.verdict==='REFUSE'?'Refused':human(r.verdict),why:typeof r.explanation==='string'?r.explanation:r.refusal_words||human(r.refusal),detail:'Gross edge '+(n(r.edge_pp)?r.edge_pp.toFixed(2)+' pp':'not recorded')+' · net EV '+money(r.net_ev_usd),historical:!!(s.version&&r.policy_version&&s.version!==r.policy_version),current:!!(s.version&&r.policy_version&&s.version===r.policy_version),approved:r.verdict==='ENTER',original:r,type:'Entry decision'});});});
  if(kind==='audrey')list(j.operational_audit).forEach(function(r){var events=r.events||[],responses=events.filter(function(e){return e.kind==='RESPONSE'&&e.actor!=='SYSTEM';}),measurements=events.filter(function(e){return /MEASUR/.test(e.kind);});rows.push({id:r.recommendation_id,at:r.created_at,label:human(r.kind||r.category),event:'Responsible agent · '+(r.owner_agent||'Unassigned'),decision:human(r.status),why:r.recommendation||'No recommendation text recorded',detail:measurements.length?'Measurement recorded':responses.length?'Agent review recorded':'Awaiting genuine agent review',pending:!responses.length,measured:!!measurements.length,original:r,type:'Recommendation'});});
  return rows.filter(function(r){return r.id;});
 }
 function newest(rows){return rows.slice().sort(function(a,b){return (epoch(b.at)||0)-(epoch(a.at)||0);});}
 function selectedRow(){return records.find(function(r){return r.id===selected;})||newest(records)[0];}
 function renderBrief(){var r=selectedRow();if(!r){brief.innerHTML='<div class="desk-eyebrow">At the desk · '+E(name)+'</div><h2>Waiting for recorded work.</h2><p class="desk-empty">'+(state&&state.fail?'The latest read failed. Earlier records remain visible when available.':'No record is available in this snapshot. Ask '+name+' for a status briefing.')+'</p>';return;}var html='<div class="desk-brief-top"><span class="desk-eyebrow">'+(selected?'Selected record':'Latest recorded work')+' · '+E(name)+'</span><span class="desk-record-age">'+ageSpan(r.at)+'</span></div><h2>'+E(r.label)+'</h2><p class="desk-subtitle">'+E(r.event)+'</p><div class="desk-insights"><div><small>'+E(r.type)+'</small><strong>'+E(r.decision)+'</strong><p>'+E(r.detail)+'</p></div><div><small>Recorded rationale</small><p>'+E(r.why)+'</p></div></div><div class="desk-actions"><button type="button" class="primary" data-desk-ask="'+E(r.id)+'">Explain this decision ↗</button><button type="button" data-desk-open="'+E(r.id)+'">Open full record</button></div><p class="desk-live-note">'+(state&&state.fail?'Connection interrupted · displaying the last successful records.':r.attention?'Review is older than 2 minutes or missing. This is not a fresh recommendation.':'Recorded rationale · freshness shown above.')+'</p>';
  if(html!==lastBrief){brief.innerHTML=html;lastBrief=html;}
 }
 function matches(r){var text=[r.label,r.event,r.id,r.decision,r.why,r.original.us_market_slug,r.original.strategy].join(' ').toLowerCase();return (!query||text.includes(query))&&(filter==='all'||filter==='attention'&&r.attention||filter==='orders'&&r.orders>0||filter==='current'&&r.current||filter==='approved'&&r.approved||filter==='pending'&&r.pending||filter==='measured'&&r.measured);}
 function applyFilters(){var byId=new Map(records.map(function(r){return [r.id,r];})),shown=0,total=0;content.querySelectorAll('.work-item[data-work-key]').forEach(function(el){var r=byId.get(el.dataset.workKey);if(!r)return;total++;el.hidden=!matches(r);if(!el.hidden)shown++;el.dataset.deskSelected=String(r.id===selected);});document.getElementById('desk-count').textContent=shown+' / '+total;noMatch.hidden=!(total&&shown===0);toolbar.querySelectorAll('[data-desk-filter]').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.deskFilter===filter));});}
 function renderActivity(){var events=newest(records).slice(0,6);activity.innerHTML='<div class="desk-section-head"><h2>Activity journal</h2><span>Latest records in this read</span></div>'+(events.length?'<ol class="desk-events">'+events.map(function(r){return '<li class="desk-event"><i class="desk-event-dot" aria-hidden="true"></i><div><button type="button" data-desk-select="'+E(r.id)+'">'+E(r.decision)+' · '+E(r.label)+'</button><small>'+E(r.type)+(r.historical?' · historical policy':'')+'</small></div><time>'+ageSpan(r.at)+'</time></li>';}).join('')+'</ol>':'<p class="desk-empty">No activity records available.</p>');}
 function enhance(st){state=st;if(!st||!st.json){renderBrief();return;}if(st.okAt!=null)lastReadAt=st.okAt;var next=recordRows(st.json),ids=new Set(next.map(function(r){return r.id+'|'+r.at;})),changed=!first&&Array.from(ids).some(function(id){return !seen.has(id);});seen=ids;first=false;records=next;if(selected&&!records.some(function(r){return r.id===selected;}))selected=null;renderBrief();applyFilters();renderActivity();if(changed){brief.classList.remove('new-record');void brief.offsetWidth;brief.classList.add('new-record');}}
 function select(id,open){selected=id;renderBrief();applyFilters();var el=Array.from(content.querySelectorAll('[data-work-key]')).find(function(x){return x.dataset.workKey===id;});if(open&&el){query='';filter='all';document.getElementById('desk-search').value='';applyFilters();el.open=true;el.scrollIntoView({block:'nearest',behavior:'auto'});}else brief.scrollIntoView({block:'nearest',behavior:'auto'});}
 toolbar.addEventListener('click',function(e){var b=e.target.closest('[data-desk-filter]');if(b){filter=b.dataset.deskFilter;applyFilters();}});document.getElementById('desk-search').addEventListener('input',function(e){query=e.target.value.trim().toLowerCase();applyFilters();});
 board.addEventListener('click',function(e){var b=e.target.closest('[data-desk-select],[data-desk-open],[data-desk-ask]');if(b){var id=b.dataset.deskSelect||b.dataset.deskOpen||b.dataset.deskAsk;if(b.dataset.deskAsk){var r=records.find(function(x){return x.id===id;});draft('Explain your recorded decision for '+(r?r.label:id)+', record '+id+'. What evidence supports it, what is uncertain, and what would change the action?');}else select(id,!!b.dataset.deskOpen);}else{var row=e.target.closest('.work-item[data-work-key] > summary');if(row){selected=row.parentElement.dataset.workKey;renderBrief();applyFilters();}}});
 chips.addEventListener('click',function(e){var b=e.target.closest('[data-desk-prompt]');if(!b)return;var r=selectedRow(),q=b.dataset.deskPrompt==='Brief me'?'Give me a concise management briefing: current work, recorded decisions, and outstanding risks.':b.dataset.deskPrompt==='What changed?'?'What changed in the latest recorded work? Cite the timestamps and distinguish it from earlier records.':'What needs management attention, based on the current records? Distinguish verified issues from unknowns.';if(selected&&r)q+=' Focus on record '+r.id+'.';draft(q);});
 function csvCell(v){var text=String(v==null?'':v);if(/^[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';}
 document.getElementById('desk-export').addEventListener('click',function(){var rows=[['Agent','Record ID','Market / finding','Event / owner','Decision','Rationale','Recorded time','Policy version','Purpose','Read time','Read status']];var visible=new Set(Array.from(content.querySelectorAll('.work-item[data-work-key]:not([hidden])')).map(function(el){return el.dataset.workKey;}));records.filter(function(r){return visible.has(r.id);}).forEach(function(r){rows.push([name,r.id,r.label,r.event,r.decision,r.why,r.at,r.original.policy_version||'',/EXPLORATION/.test(r.original.strategy||'')?'Training / simulated':'Simulated execution',lastReadAt,state&&state.fail?'STALE LAST SUCCESSFUL READ':'RECORDED SNAPSHOT']);});var blob=new Blob(['\ufeff'+rows.map(function(r){return r.map(csvCell).join(',');}).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name+'-recorded-work-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);});
 var oldPanels=CC.ops.panels;CC.ops.panels=function(k,st){var result=oldPanels(k,st);if(k===kind)enhance(st);return result;};var oldRender=office.render;office.render=function(st){oldRender(st);enhance(st);};
 var stateEl=document.getElementById('talk-state');function conversationState(){presence.textContent=stateEl&&!stateEl.hidden&&stateEl.textContent?stateEl.textContent:'Ready for your next question · uses recorded evidence.';}
 if(stateEl)new MutationObserver(conversationState).observe(stateEl,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});conversationState();
 setInterval(function(){if(document.hidden)return;document.querySelectorAll('[data-desk-at]').forEach(function(el){var v=el.dataset.deskAt;el.textContent=ago(v!==''&&isFinite(Number(v))?Number(v):v);});},1000);
 window.CCDesk={render:enhance,openConversation:openTalk,closeConversation:closeTalk};
})();
"""
