"""THE XAVIER PANEL, SERVED FROM THE API'S OWN ORIGIN.

GENERATED by `tools/build_xavier_page.py` from `frontend/public/command/`
xavier.html, xavier.css and xavier.js; a test compares this copy with a fresh
build, so editing it by hand is how the two would diverge. The route that
serves it sits behind `require_command`, and the page's only fetch is the one
same-origin read of `/api/command/xavier`. It sends no order and holds no
credential.
"""

XAVIER_PAGE_HTML = r"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#0b0f17">
  <meta name="robots" content="noindex,nofollow">
  <meta name="description" content="Xavier — the position manager's decisions, alternatives and daily review. Read-only.">
  <title>Xavier | BETTOR Command</title>
  <style>/* XAVIER PANEL · presentation only. Every class is prefixed `xv-` so it can
 * sit inside the Command Centre shell without touching its rules, and the
 * tokens are its own so the standalone page needs no other stylesheet. */

.xv-root, .xv-page {
  --xv-bg: #0b0f17;
  --xv-surface: #111723;
  --xv-line: #1f2a3a;
  --xv-ink: #e6ebf2;
  --xv-ink-2: #9fb0c8;
  --xv-good: #3ddc97;
  --xv-warn: #f2b544;
  --xv-bad: #ff6b6b;
  --xv-accent: #4c9ffe;
  color: var(--xv-ink);
}

.xv-page {
  margin: 0;
  padding: 16px;
  background: var(--xv-bg);
  font: 14px/1.45 system-ui, -apple-system, "Segoe UI", sans-serif;
}

.xv-root { display: grid; gap: 14px; max-width: 1100px; margin: 0 auto; }

.xv-panel, .xv-card {
  background: var(--xv-surface);
  border: 1px solid var(--xv-line);
  border-radius: 10px;
  padding: 14px 16px;
  min-width: 0;
}

.xv-head h2 { margin: 0 0 4px; font-size: 20px; }
.xv-card h4, .xv-panel h4 { margin: 14px 0 6px; font-size: 13px;
  text-transform: uppercase; letter-spacing: .04em; color: var(--xv-ink-2); }
.xv-panel h3 { margin: 0 0 8px; font-size: 16px; }

.xv-card-head { display: flex; justify-content: space-between; gap: 12px;
  align-items: flex-start; flex-wrap: wrap; }
.xv-slug { margin: 0; font-weight: 600; word-break: break-all; }
.xv-sub, .xv-note { margin: 4px 0; color: var(--xv-ink-2); font-size: 13px; }

.xv-chosen-action { font-size: 20px; font-weight: 700; padding: 6px 12px;
  border-radius: 8px; border: 1px solid var(--xv-line); }
.xv-hold { color: var(--xv-accent); }
.xv-act { color: var(--xv-warn); }
.xv-wait { color: var(--xv-ink-2); }

.xv-badge { display: inline-block; padding: 2px 8px; border-radius: 999px;
  border: 1px solid currentColor; font-size: 12px; margin-right: 8px; }
.xv-good { color: var(--xv-good); }
.xv-bad { color: var(--xv-bad); }

.xv-scroll { overflow-x: auto; -webkit-overflow-scrolling: touch; }
.xv-table { width: 100%; border-collapse: collapse; font-size: 13px; }
.xv-table th, .xv-table td { text-align: left; padding: 6px 8px;
  border-bottom: 1px solid var(--xv-line); white-space: nowrap; }
.xv-table th { color: var(--xv-ink-2); font-weight: 600; }
.xv-chosen td { background: rgba(76, 159, 254, .08); }

.xv-grid { display: grid; gap: 12px;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); }
.xv-grid dl, .xv-inline { display: grid; grid-template-columns: auto 1fr;
  gap: 2px 12px; margin: 0; }
.xv-grid dt, .xv-inline dt { color: var(--xv-ink-2); }
.xv-grid dd, .xv-inline dd { margin: 0; text-align: right; }

.xv-unknown { color: var(--xv-warn); font-style: normal; font-weight: 600; }
.xv-json { max-height: 180px; overflow: auto; background: var(--xv-bg);
  border: 1px solid var(--xv-line); border-radius: 6px; padding: 8px;
  font-size: 12px; white-space: pre-wrap; word-break: break-word; }
.xv-blockers { margin: 0; padding-left: 18px; }
.xv-kind { color: var(--xv-ink-2); font-size: 12px; }
.xv-hypo { border-left: 3px solid var(--xv-warn); padding: 6px 10px;
  background: rgba(242, 181, 68, .08); margin: 6px 0; }
.xv-empty h3 { color: var(--xv-warn); }
.xv-unavailable h3 { color: var(--xv-bad); }
.xv-root code { word-break: break-all; }
</style>
</head>
<body class="xv-page">
  <!-- Read-only. The session is the existing HttpOnly COMMAND cookie, scoped
       to Path=/api/command; this page holds no credential and sends no
       custom header. A 401 means "sign in on the main Command page first". -->
  <div id="xv-root"><p>Opening Xavier…</p></div>
  <script>/* XAVIER · the position manager's decisions, read-only.
 *
 * One card per position under Xavier's responsibility: the chosen action,
 * every alternative (value, change vs HOLD, worst case, capital, blocker),
 * the reasoning, expected against realised economics, the unpaired
 * residual, the next review and what blocks it. Below, the latest daily
 * review, whose alternative figures are HYPOTHETICAL ESTIMATES and say so
 * on every row: an eventual winning outcome does not show that an order
 * which was never placed would have filled.
 *
 * UNKNOWN IS NOT ZERO. A figure the record does not carry renders as
 * UNKNOWN, never as 0 or a dash that could be read as one.
 *
 * Transport is the same as the rest of COMMAND: same-origin, the HttpOnly
 * cookie the browser attaches, no custom header, no credential in
 * JavaScript, nothing cached. It reads one route and writes nothing.
 */
(function (root) {
  'use strict';

  var API = '/api/command/xavier';
  var st = { data: null, error: null, at: null, loading: false };

  function esc(v) {
    return String(v === null || v === undefined ? '' : v)
      .replace(/[&<>"']/g, function (c) {
        return { '&': '&amp;', '<': '&lt;', '>': '&gt;',
                 '"': '&quot;', "'": '&#39;' }[c];
      });
  }

  function unknown(why) {
    return '<em class="xv-unknown"' + (why ? ' title="' + esc(why) + '"'
      : '') + '>UNKNOWN</em>';
  }

  function usd(v, why) {
    if (typeof v !== 'number' || !isFinite(v)) return unknown(why);
    var s = Math.abs(v).toFixed(2);
    return (v < 0 ? '−$' : '$') + s;
  }

  function num(v) {
    if (typeof v !== 'number' || !isFinite(v)) return unknown();
    return esc(String(Math.round(v * 1e6) / 1e6));
  }

  function when(iso) {
    if (!iso) return unknown();
    var t = Date.parse(iso);
    if (!isFinite(t)) return esc(iso);
    return esc(new Date(t).toISOString().replace('T', ' ').slice(0, 16)
      + 'Z');
  }

  function tone(action) {
    if (!action) return 'xv-wait';
    if (action === 'HOLD') return 'xv-hold';
    return 'xv-act';
  }

  function eligTone(e) {
    e = String(e || '');
    if (e === 'DISPATCHED') return 'xv-good';
    if (e.indexOf('BLOCKED') === 0 || e.indexOf('NOT_DISPATCHED') === 0) {
      return 'xv-bad';
    }
    return 'xv-wait';
  }

  function json(v) {
    if (v === null || v === undefined) return unknown();
    return '<pre class="xv-json">' + esc(JSON.stringify(v, null, 1))
      + '</pre>';
  }

  function altTable(alts) {
    if (!alts || !alts.length) {
      return '<p class="xv-note">The record lists no alternatives.</p>';
    }
    return '<div class="xv-scroll"><table class="xv-table"><thead><tr>'
      + '<th>Action</th><th>Value</th><th>Δ vs HOLD</th>'
      + '<th>Worst case</th><th>Capital</th><th>Blocker</th>'
      + '</tr></thead><tbody>' + alts.map(function (a) {
        return '<tr' + (a.chosen ? ' class="xv-chosen"' : '') + '><td>'
          + esc(a.action) + (a.chosen ? ' <b>chosen</b>' : '') + '</td><td>'
          + (a.blocker && a.value_usd === null ? '—'
             : usd(a.value_usd, 'not in the record')) + '</td><td>'
          + (a.increment_vs_hold_usd === null ? unknown()
             : usd(a.increment_vs_hold_usd)
               + (a.increment_basis && a.increment_basis !== 'RECORDED'
                  ? ' <small title="' + esc(a.increment_basis)
                    + '">derived</small>' : ''))
          + '</td><td>' + usd(a.worst_case_usd, 'not in the record')
          + '</td><td>' + usd(a.capital_usd, 'not in the record')
          + '</td><td>' + (a.blocker ? '<code>' + esc(a.blocker)
                           + '</code>' : '') + '</td></tr>';
      }).join('') + '</tbody></table></div>';
  }

  function blockers(list) {
    if (!list || !list.length) return '<p class="xv-note">None recorded.</p>';
    return '<ul class="xv-blockers">' + list.map(function (b) {
      return '<li><span class="xv-kind">' + esc(b.kind) + '</span> <code>'
        + esc(b.name) + '</code>' + (b.action ? ' (' + esc(b.action) + ')'
        : '') + '</li>';
    }).join('') + '</ul>';
  }

  function card(p) {
    var ex = p.expected_economics || {};
    var re = p.realised || {};
    var rx = p.residual_exposure || {};
    var reasoning = p.reasoning || {};
    return '<article class="xv-card">'
      + '<header class="xv-card-head"><div>'
      + '<p class="xv-slug">' + esc(p.us_market_slug || p.intent_id) + '</p>'
      + '<p class="xv-sub">' + esc(p.responsibility_state) + ' · decided '
      + when(p.decided_at) + '</p></div>'
      + '<div class="xv-chosen-action ' + tone(p.chosen_action) + '">'
      + esc(p.chosen_action || 'NOTHING SELECTABLE') + '</div></header>'
      + '<p class="xv-elig"><span class="xv-badge ' + eligTone(
        p.execution_eligibility) + '">' + esc(p.execution_eligibility)
      + '</span> next review ' + when(p.next_review_at) + '</p>'
      + (p.execution ? '<p class="xv-sub">execution ' + esc(
        p.execution.status) + ' · filled ' + num(p.execution.filled_qty)
        + '</p>' : '')
      + '<h4>Alternatives</h4>' + altTable(p.alternatives)
      + '<h4>Reasoning</h4>'
      + (reasoning.why ? '<p>' + esc(reasoning.why) + '</p>' : '')
      + json(reasoning)
      + '<div class="xv-grid">'
      + '<div><h4>Expected</h4><dl>'
      + '<dt>expected net</dt><dd>' + usd(ex.expected_net_usd) + '</dd>'
      + '</dl></div>'
      + '<div><h4>Realised so far (book)</h4><dl>'
      + '<dt>realised</dt><dd>' + usd(re.realised_usd) + '</dd>'
      + '<dt>basis still held</dt><dd>' + usd(re.remaining_basis_usd)
      + '</dd><dt>unrealised</dt><dd>'
      + (re.unrealised_usd === null || re.unrealised_usd === undefined
         ? unknown(re.unrealised_status) : usd(re.unrealised_usd))
      + '</dd><dt>provisional events</dt><dd>'
      + num(re.provisional_events) + '</dd></dl></div>'
      + '<div><h4>Residual exposure</h4><dl>'
      + '<dt>matched</dt><dd>' + num(rx.matched_qty) + '</dd>'
      + '<dt>unpaired</dt><dd>' + num(
        rx.unpaired_qty !== undefined ? rx.unpaired_qty
        : rx.unpaired_residual_qty) + '</dd></dl></div>'
      + '</div>'
      + '<h4>Blockers</h4>' + blockers(p.blockers)
      + '<p class="xv-sub">record <code>' + esc(p.xavier_decision_id)
      + '</code> · history <code>' + esc(API + '/' + p.intent_id)
      + '</code></p></article>';
  }

  function emptyState(w) {
    w = w || {};
    return '<section class="xv-panel xv-empty"><h3>No position is under '
      + 'Xavier’s responsibility</h3><p>This is not an all-clear. '
      + 'Why nothing is managed:</p><ul>' + (w.reasons || []).map(function (r) {
        return '<li><code>' + esc(r) + '</code></li>';
      }).join('') + '</ul>'
      + (w.account_why ? '<p class="xv-note">' + esc(w.account_why) + '</p>'
        : '')
      + '<p class="xv-note">Last cycle: ' + esc((w.last_cycle || {})
        .cycle_state || 'none recorded') + (w.last_cycle && w.last_cycle
        .servicing_refusal ? ' · servicing refused <code>'
        + esc(w.last_cycle.servicing_refusal) + '</code>' : '') + '</p>'
      + '</section>';
  }

  function review(r) {
    r = r || {};
    if (!r.available) {
      return '<section class="xv-panel"><h3>Daily review</h3><p>'
        + esc(r.why || 'no review recorded') + '</p></section>';
    }
    var fe = (r.forecast_error || {}).all || {};
    var alts = r.alternatives || {};
    return '<section class="xv-panel"><h3>Daily review · '
      + esc(r.review_date) + '</h3><p>' + esc(r.summary) + '</p>'
      + '<dl class="xv-inline"><dt>decisions reviewed</dt><dd>'
      + num(r.decisions_reviewed) + '</dd><dt>with outcomes</dt><dd>'
      + num(r.decisions_with_outcomes) + '</dd><dt>invalidated</dt><dd>'
      + num(r.invalidated) + '</dd><dt>mean error (per fixture)</dt><dd>'
      + usd(fe.mean_error_usd) + '</dd><dt>status</dt><dd>'
      + esc(fe.status || '') + '</dd></dl>'
      + '<h4>Alternatives not taken</h4>'
      + '<p class="xv-hypo" role="note"><b>HYPOTHETICAL ESTIMATES.</b> '
      + esc(alts.label || '') + '</p>'
      + '<div class="xv-scroll"><table class="xv-table"><thead><tr>'
      + '<th>Action</th><th>Estimate</th><th>Label</th><th>Fill basis</th>'
      + '<th>Could have filled</th></tr></thead><tbody>'
      + (alts.rows || []).map(function (a) {
        return '<tr><td>' + esc(a.action) + '</td><td>'
          + (a.estimate_usd === null || a.estimate_usd === undefined
             ? '<code>' + esc(a.no_estimate_because || '') + '</code>'
             : usd(a.estimate_usd)) + '</td><td>' + esc(a.kind)
          + '</td><td>' + esc(a.fill_basis || '') + '</td><td>'
          + esc(a.could_have_filled || '') + '</td></tr>';
      }).join('') + '</tbody></table></div>'
      + '<p class="xv-note">Models: '
      + esc((r.models || {}).promotion || '') + '</p></section>';
  }

  function render(data) {
    var d = data || st.data;
    if (st.error) {
      return '<section class="xv-panel xv-unavailable"><h3>XAVIER '
        + 'UNAVAILABLE</h3><p>' + esc(st.error.reason) + '</p><p class='
        + '"xv-note">' + esc(st.error.detail || '') + '</p><p class="xv-note">'
        + 'The read did not produce the records, so nothing is shown.</p>'
        + '</section>';
    }
    if (!d) return '<section class="xv-panel"><p>Reading Xavier…</p></section>';
    var sw = d.submission_switches || {};
    return '<div class="xv-root">'
      + '<section class="xv-panel xv-head"><h2>Xavier</h2><p class="xv-sub">'
      + esc((d.xavier || {}).what_it_is || '') + '</p><p class="xv-sub">'
      + 'Read-only · ' + num(d.position_count) + ' position(s) · as of '
      + when(d.as_of) + ' · funded submission '
      + (sw.FUNDED_SUBMISSION_ENABLED ? 'ENABLED' : 'DISABLED')
      + ' · exit submission '
      + (sw.FUNDED_EXIT_SUBMISSION_ENABLED ? 'ENABLED' : 'DISABLED')
      + '</p></section>'
      + (d.empty ? emptyState(d.why_nothing_is_managed)
         : (d.positions || []).map(card).join(''))
      + review(d.daily_review) + '</div>';
  }

  async function load(done) {
    st.loading = true;
    st.error = null;
    try {
      var res = await fetch(API, {
        credentials: 'same-origin', cache: 'no-store',
        headers: { 'Accept': 'application/json' }
      });
      if (res.status === 401 || res.status === 403) {
        st.error = { reason: 'COMMAND UNLOCK REQUIRED',
                     detail: 'Sign in on the main Command page first.' };
      } else if (!res.ok) {
        var body = null;
        try { body = await res.json(); } catch (e) { body = null; }
        var det = (body && body.detail) || {};
        st.error = { reason: det.reason || ('HTTP ' + res.status),
                     detail: det.detail || det.note || '' };
      } else {
        st.data = await res.json();
        st.at = new Date().toISOString();
      }
    } catch (e) {
      st.error = { reason: 'FEED UNREACHABLE', detail: String(e) };
    }
    st.loading = false;
    if (typeof done === 'function') done();
  }

  /* THE COMMAND CENTRE'S TAB: returns what to show now and loads once,
   * re-rendering the host when the read lands. */
  function panel(rerender) {
    if (!st.data && !st.error && !st.loading) load(rerender);
    return render();
  }

  root.BTXavier = { API: API, load: load, render: render, panel: panel,
                    state: st };

  function standalone() {
    var el = document.getElementById('xv-root');
    if (!el) return;
    el.innerHTML = render();
    load(function () { el.innerHTML = render(); });
  }
  if (typeof document !== 'undefined') {
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', standalone);
    } else {
      standalone();
    }
  }
})(window);
</script>
</body>
</html>
"""
